== The Internals of Kafka Streams {{ book.kafka_version }}

Welcome to *The Internals of Kafka Streams* gitbook! I'm very excited to have you here and hope you will enjoy exploring the internals of Kafka Streams as much as I have.

[quote, Flannery O'Connor]
I write to discover what I know.

I'm https://pl.linkedin.com/in/jaceklaskowski[Jacek Laskowski], a freelance IT consultant, software engineer and technical instructor specializing in Apache Spark, Apache Kafka and *Kafka Streams* (with Scala and sbt).

I offer software development and consultancy services with hands-on in-depth workshops and mentoring. Reach out to me at jacek@japila.pl or https://twitter.com/jaceklaskowski[@jaceklaskowski] to discuss opportunities.

Consider joining me at http://www.meetup.com/WarsawScala/[Warsaw Scala Enthusiasts] and http://www.meetup.com/Warsaw-Spark[Warsaw Spark] meetups in Warsaw, Poland.

TIP: I'm also writing other books in the "The Internals of" series about https://bit.ly/apache-kafka-internals[Apache Kafka], http://books.japila.pl/apache-spark-internals/[Apache Spark], https://bit.ly/spark-sql-internals[Spark SQL], and https://bit.ly/spark-structured-streaming[Spark Structured Streaming].

Expect text and code snippets from a variety of public sources. Attribution follows.

Now, let me introduce you to <<kafka-streams.adoc#, Kafka Streams>>.
