== [[UnwindowedChangelogTopicConfig]] UnwindowedChangelogTopicConfig

`UnwindowedChangelogTopicConfig` is an link:kafka-streams-InternalTopicConfig.adoc[InternalTopicConfig] that...FIXME

`UnwindowedChangelogTopicConfig` is <<creating-instance, created>> exclusively when `InternalTopologyBuilder` is requested for link:kafka-streams-InternalTopologyBuilder.adoc#createChangelogTopicConfig[create an InternalTopicConfig (for a given name and StateStoreFactory)].

[[internal-registries]]
[[UNWINDOWED_STORE_CHANGELOG_TOPIC_DEFAULT_OVERRIDES]]
When <<creating-instance, created>>, `UnwindowedChangelogTopicConfig` creates a `UNWINDOWED_STORE_CHANGELOG_TOPIC_DEFAULT_OVERRIDES` configuration properties that...FIXME

=== [[creating-instance]] Creating UnwindowedChangelogTopicConfig Instance

`UnwindowedChangelogTopicConfig` takes the following when created:

* [[name]] Name
* [[topicConfigs]] Topic configs (as `Map<String, String>`)

`UnwindowedChangelogTopicConfig` initializes the <<internal-registries, internal registries and counters>>.
