== [[KGroupedStream]] KGroupedStream -- Basic Aggregations

`KGroupedStream` is the <<contract, abstraction>> of <<implementations, grouped record stream>> (of key-value pairs) that allows Kafka Streams developers for <<aggregate, aggregate>>, <<count, count>>, <<reduce, reduce>> and <<windowedBy, windowedBy>> aggregations over a record stream.

`KGroupedStream` is the result of the following aggregate stream operators:

* <<kafka-streams-KStream.adoc#groupBy, KStream.groupBy>>
* <<kafka-streams-KStream.adoc#groupByKey, KStream.groupByKey>>

[source, java]
----
// FIXME Demo
----

TIP: Use <<kafka-streams-scala.adoc#, Scala API for Kafka Streams>> to make your Kafka Streams development more pleasant if Scala is your programming language.

[[contract]]
.KGroupedStream Operators
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| aggregate
a| [[aggregate]]

[source, java]
----
KTable<K, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator)
KTable<K, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator,
  final Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

Creates a <<kafka-streams-KTable.adoc#, KTable>> for an `Initializer`, an `Aggregator` and a <<kafka-streams-Materialized.adoc#, Materialized>> (view of a <<kafka-streams-StateStore-KeyValueStore.adoc#, KeyValueStore>>)

| count
a| [[count]]

[source, java]
----
KTable<K, Long> count()
KTable<K, Long> count(
  final Materialized<K, Long, KeyValueStore<Bytes, byte[]>> materialized)
----

Creates a <<kafka-streams-KTable.adoc#, KTable>> for a <<kafka-streams-Materialized.adoc#, Materialized>> (view of a <<kafka-streams-StateStore-KeyValueStore.adoc#, KeyValueStore>>)

| reduce
a| [[reduce]]

[source, java]
----
KTable<K, V> reduce(final Reducer<V> reducer)
KTable<K, V> reduce(
  final Reducer<V> reducer,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
----

Creates a <<kafka-streams-KTable.adoc#, KTable>> for a `Reducer` and a <<kafka-streams-Materialized.adoc#, Materialized>> (view of a <<kafka-streams-StateStore-KeyValueStore.adoc#, KeyValueStore>>)

| windowedBy
a| [[windowedBy]][[windowedBy-SessionWindowedKStream]]

[source, java]
----
SessionWindowedKStream<K, V> windowedBy(final SessionWindows windows)
----
Creates a <<kafka-streams-SessionWindowedKStream.adoc#, SessionWindowedKStream>> for a `SessionWindows` specification

| windowedBy
a| [[windowedBy-TimeWindowedKStream]]

[source, java]
----
<W extends Window> TimeWindowedKStream<K, V> windowedBy(final Windows<W> windows)
----

Creates a <<kafka-streams-TimeWindowedKStream.adoc#, TimeWindowedKStream>> for a <<kafka-streams-Windows.adoc#, Windows>> specification
|===

[[implementations]]
NOTE: <<kafka-streams-KGroupedStreamImpl.adoc#, KGroupedStreamImpl>> is the one and only known implementation of the <<contract, KGroupedStream Contract>> in Kafka Streams {{ book.kafka_version }}.
