== [[AssignedStreamsTasks]] AssignedStreamsTasks -- AssignedTasks For StreamTasks

`AssignedStreamsTasks` is a link:kafka-streams-AssignedTasks.adoc[AssignedTasks] for link:kafka-streams-StreamTask.adoc[StreamTasks] that...FIXME

`AssignedStreamsTasks` is <<creating-instance, created>> along with a link:kafka-streams-StreamThread.adoc#create[StreamThread] (when `KafkaStreams` is link:kafka-streams-KafkaStreams.adoc#creating-instance[created]).

`AssignedStreamsTasks` is a `RestoringTasks` that...FIXME

It _appears_ that `AssignedStreamsTasks` simply operates on the running tasks (i.e. the tasks that are in link:kafka-streams-AssignedTasks.adoc#running[running] internal registry). When requested to <<process, process>> or <<punctuate, punctuate>> `AssignedStreamsTasks` simply walks over the `running` internal registry and triggers execution of every task.

[[maybeCommitAction]]
`AssignedStreamsTasks` uses a `TaskAction<StreamTask>` called *maybeCommit* that is used in <<maybeCommit, maybeCommit>>. The task action takes a link:kafka-streams-StreamTask.adoc[stream task] and checks if the task link:kafka-streams-StreamTask.adoc#commitNeeded[needs a commit]. If so, the action does the following:

1. Increments <<committed, committed>> counter

1. Requests the stream task to link:kafka-streams-StreamTask.adoc#commit[commit]

1. Prints out the following DEBUG message to the logs:
+
```
Committed active task [id] per user request in
```

[[logContext]]
[[creating-instance]]
`AssignedStreamsTasks` takes a `LogContext` when created.

`AssignedStreamsTasks` uses *stream task* for link:kafka-streams-AssignedTasks.adoc#taskTypeName[taskTypeName].

[[internal-registries]]
.AssignedStreamsTasks's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `committed`
| [[committed]] Number of...FIXME

| `log`
| [[log]]
|===

[[logging]]
[TIP]
====
Enable any of `ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE` logging levels for `org.apache.kafka.streams.processor.internals.AssignedStreamsTasks` logger to see what happens inside.

Add the following line to `log4j.properties`:

```
log4j.logger.org.apache.kafka.streams.processor.internals.AssignedStreamsTasks=TRACE
```

Refer to link:kafka-logging.adoc#log4j.properties[Application Logging Using log4j].
====

=== [[process]] Requesting Stream Tasks to Process Records -- `process` Method

[source, java]
----
int process()
----

`process` requests every link:kafka-streams-AssignedTasks.adoc#running[running] stream task to link:kafka-streams-StreamTask.adoc#process[process a single record].

In the end, `process` gives the number of stream tasks that processed a single record successfully.

NOTE: `process` is used exclusively when `TaskManager` is requested to link:kafka-streams-TaskManager.adoc#process[process records].

==== [[process-TaskMigratedException]] process and TaskMigratedException

In case of a `TaskMigratedException`, `process` prints out the following INFO message to the logs:

```
Failed to process stream task [id] since it got migrated to another thread already. Closing it as zombie before triggering a new rebalance.
```

`process` then link:kafka-streams-AssignedTasks.adoc#closeZombieTask[closes the task] (considering the task a zombie). If this reports a `RuntimeException`, `process` re-throws it.

`process` removes the task from link:kafka-streams-AssignedTasks.adoc#running[running] and throws the `TaskMigratedException`.

==== [[process-RuntimeException]] process and RuntimeException

In case of a `RuntimeException`, `process` prints out the following ERROR message to the logs followed by the exception.

```
Failed to process stream task [id] due to the following error:
```

`process` re-throws the `RuntimeException`.

=== [[maybeCommit]] Committing Running Stream Tasks that Requested It -- `maybeCommit` Method

[source, java]
----
int maybeCommit()
----

`maybeCommit` resets <<committed, committed>> to 0 and link:kafka-streams-AssignedTasks.adoc#applyToRunningTasks[executes] the <<maybeCommitAction, maybeCommitAction>> task action (that modifies <<committed, committed>>).

In the end, `maybeCommit` gives the number of running stream tasks that link:kafka-streams-StreamTask.adoc#commitNeeded[needed a commit].

NOTE: `maybeCommit` is used exclusively when `TaskManager` is requested to link:kafka-streams-TaskManager.adoc#maybeCommitActiveTasks[maybeCommitActiveTasks].

=== [[creating-instance]] Creating AssignedStreamsTasks Instance

`AssignedStreamsTasks` takes the following when created:

* AssignedStreamsTasks

`AssignedStreamsTasks` initializes the <<internal-registries, internal registries and counters>>.

`AssignedStreamsTasks` is <<creating-instance, created>> when...MEFIXME

`AssignedStreamsTasks` is <<creating-instance, created>> along with...MEFIXME

=== [[punctuate]] `punctuate` Method

[source, java]
----
int punctuate()
----

`punctuate`...FIXME

NOTE: `punctuate` is used exclusively when `TaskManager` is requested to link:kafka-streams-TaskManager.adoc#punctuate[punctuate].
