== [[InternalTopologyBuilder]] InternalTopologyBuilder

`InternalTopologyBuilder` is...FIXME

[[creating-instance]]
When created, `InternalTopologyBuilder` simply initializes the <<internal-registries, internal registries and counters>>.

[[internal-registries]]
.InternalTopologyBuilder's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[globalTopics]] `globalTopics`
a| Names of global topics

* A new name is added when `InternalTopologyBuilder` <<addGlobalStore, addGlobalStore>>

* Used when `InternalTopologyBuilder` <<isGlobalSource, isGlobalSource>>

| [[internalTopicNames]] `internalTopicNames`
a| Names of...FIXME

* New element is added when `InternalTopologyBuilder` is requested to <<addInternalTopic, addInternalTopic>>

| [[nodeFactories]] `nodeFactories`
| Collection of named link:kafka-streams-NodeFactory.adoc[NodeFactories]

Used when...FIXME

| [[nodeGrouper]] `nodeGrouper`
| Names of...FIXME

Used when...FIXME

| [[nodeToSourceTopics]] `nodeToSourceTopics`
| Names of source nodes and their topics

Used when...FIXME

| [[sourceTopicNames]] `sourceTopicNames`
| Collection of <<addSource, registered>> topic names

Used when...FIXME

| [[topicPattern]] `topicPattern`
a| Source topic pattern to subscribe to

* Initialized the first time when `InternalTopologyBuilder` is requested for the <<sourceTopicPattern, source topic pattern>>
|===

=== [[addGlobalStore]] `addGlobalStore` Method

[source, java]
----
void addGlobalStore(
  final StoreBuilder<KeyValueStore> storeBuilder,
  final String sourceName,
  final TimestampExtractor timestampExtractor,
  final Deserializer keyDeserializer,
  final Deserializer valueDeserializer,
  final String topic,
  final String processorName,
  final ProcessorSupplier stateUpdateSupplier)
void addGlobalStore(
  final org.apache.kafka.streams.processor.StateStoreSupplier<KeyValueStore> storeSupplier,
  final String sourceName,
  final TimestampExtractor timestampExtractor,
  final Deserializer keyDeserializer,
  final Deserializer valueDeserializer,
  final String topic,
  final String processorName,
  final ProcessorSupplier stateUpdateSupplier)
// private
private void addGlobalStore(
  final String sourceName,
  final TimestampExtractor timestampExtractor,
  final Deserializer keyDeserializer,
  final Deserializer valueDeserializer,
  final String topic,
  final String processorName,
  final ProcessorSupplier stateUpdateSupplier,
  final String name,
  final KeyValueStore store)
----

`addGlobalStore`...FIXME

NOTE: `addGlobalStore` is used when...FIXME

=== [[addProcessor]] `addProcessor` Method

[source, java]
----
void addProcessor(
  final String name,
  final ProcessorSupplier supplier,
  final String... predecessorNames)
----

`addProcessor`...FIXME

NOTE: `addProcessor` is used when...FIXME

=== [[addInternalTopic]] `addInternalTopic` Method

[source, java]
----
final void addInternalTopic(final String topicName)
----

`addInternalTopic`...FIXME

[NOTE]
====
`addInternalTopic` is used when:

1. `KStreamImpl` is requested to link:kafka-streams-KStreamImpl.adoc#createReparitionedSource[createReparitionedSource]
1. `KGroupedTableImpl` is requested to `buildAggregate`
====

=== [[buildSourceNode]] `buildSourceNode` Internal Method

[source, java]
----
void buildSourceNode(
  final Map<String, SourceNode> topicSourceMap,
  final Set<String> repartitionTopics,
  final SourceNodeFactory sourceNodeFactory,
  final SourceNode node)
----

`buildSourceNode`...FIXME

NOTE: `buildSourceNode` is used exclusively when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#build[build a topology of processor tasks] (aka *processor topology*).

=== [[addSink]] `addSink` Method

[source, java]
----
void addSink(
  final String name,
  final String topic,
  final Serializer<K> keySerializer,
  final Serializer<V> valSerializer,
  final StreamPartitioner<? super K, ? super V> partitioner,
  final String... predecessorNames)
----

`addSink`...FIXME

NOTE: `addSink` is used when...FIXME

=== [[addSource]] Registering New Source Topic -- `addSource` Method

[source, scala]
----
void addSource(
  final Topology.AutoOffsetReset offsetReset,
  final String name,
  final TimestampExtractor timestampExtractor,
  final Deserializer keyDeserializer,
  final Deserializer valDeserializer,
  final String... topics)
----

For every topic name in the input `topics`, `addSource`:

1. <<validateTopicNotAlreadyRegistered, validateTopicNotAlreadyRegistered>>
1. <<maybeAddToResetList, maybeAddToResetList>>
1. Adds the topic name to <<sourceTopicNames, sourceTopicNames>>

`addSource` registers a link:kafka-streams-SourceNodeFactory.adoc[SourceNodeFactory] under the `name` in <<nodeFactories, nodeFactories>> registry.

`addSource` registers `topics` under the `name` in <<nodeToSourceTopics, nodeToSourceTopics>> registry.

`addSource` adds `name` to <<nodeGrouper, nodeGrouper>> registry.

[NOTE]
====
`addSource` is used when:

* `Topology` is rquested to link:kafka-streams-Topology.adoc#addSource[add a source node]
* `InternalStreamsBuilder` is requested to link:kafka-streams-InternalStreamsBuilder.adoc#createKTable[createKTable] or link:kafka-streams-InternalStreamsBuilder.adoc#stream[stream]
* `KGroupedTableImpl` is requested to `buildAggregate`
* `KStreamImpl` is requested to link:kafka-streams-KStreamImpl.adoc#createReparitionedSource[createReparitionedSource]
====

=== [[maybeAddToResetList]] `maybeAddToResetList` Internal Method

[source, scala]
----
void maybeAddToResetList(
  final Collection<T> earliestResets,
  final Collection<T> latestResets,
  final Topology.AutoOffsetReset offsetReset,
  final T item)
----

`maybeAddToResetList`...FIXME

NOTE: `maybeAddToResetList` is used when...FIXME

=== [[validateTopicNotAlreadyRegistered]] `validateTopicNotAlreadyRegistered` Internal Method

[source, scala]
----
void validateTopicNotAlreadyRegistered(final String topic)
----

`validateTopicNotAlreadyRegistered`...FIXME

NOTE: `validateTopicNotAlreadyRegistered` is used when...FIXME

=== [[build]] Building Processor Task Topology -- `build` Factory Method

[source, java]
----
synchronized ProcessorTopology build()
synchronized ProcessorTopology build(final Integer topicGroupId)
ProcessorTopology build(final Set<String> nodeGroup)
----

`build`...FIXME

NOTE: `nodeGroup` can be either <<globalNodeGroups, global node groups>> (aka _global state topology_) or a concrete or all <<nodeGroups, topic node group>>.

[NOTE]
====
`build` is used internally when:

* `InternalTopologyBuilder` is requested to <<buildGlobalStateTopology, build a global processor task topology>>
* `StandbyTaskCreator` is requested to link:kafka-streams-StandbyTaskCreator.adoc#createTask[create a StandbyTask for a topic group]
* `TaskCreator` is requested to link:kafka-streams-TaskCreator.adoc#createTask[create a StreamTask for a topic group]
====

=== [[buildGlobalStateTopology]] Building Global Processor Task Topology -- `buildGlobalStateTopology` Method

[source, java]
----
synchronized ProcessorTopology buildGlobalStateTopology()
----

`buildGlobalStateTopology`...FIXME

[NOTE]
====
`buildGlobalStateTopology` is used when:

* `KafkaStreams` is link:kafka-streams-KafkaStreams.adoc#creating-instance[created]
* `ProcessorTopology` is requested to `buildGlobalStateTopology`
====

=== [[sourceTopicPattern]] Getting Source Topic Pattern -- `sourceTopicPattern` Method

[source, java]
----
synchronized Pattern sourceTopicPattern()
----

`sourceTopicPattern`...FIXME

[NOTE]
====
`sourceTopicPattern` is used when:

1. `StreamThread` is started (and requested to link:kafka-streams-StreamThread.adoc#runLoop[run the main event loop])

1. `TaskManager` is requested for link:kafka-streams-TaskManager.adoc#updateSubscriptionsFromAssignment[updateSubscriptionsFromAssignment] and link:kafka-streams-TaskManager.adoc#updateSubscriptionsFromMetadata[updateSubscriptionsFromMetadata]
====

=== [[addStateStore]] `addStateStore` Method

[source, java]
----
void addStateStore(
  final org.apache.kafka.streams.processor.StateStoreSupplier supplier,
  final String... processorNames)
void addStateStore(
  final StoreBuilder storeBuilder,
  final String... processorNames)
----

`addStateStore`...FIXME

NOTE: `addStateStore` is used when...FIXME

=== [[connectProcessorAndStateStores]] `connectProcessorAndStateStores` Method

[source, java]
----
void connectProcessorAndStateStores(
  final String processorName,
  final String... stateStoreNames)
----

`connectProcessorAndStateStores` simply <<connectProcessorAndStateStore, connectProcessorAndStateStore>> with `processorName` and every state store name in `stateStoreNames`.

`connectProcessorAndStateStores` reports a `NullPointerException` when `processorName`, `stateStoreNames` or any state store name are `nulls`.

`connectProcessorAndStateStores` reports a `TopologyException` when `stateStoreNames` is an empty collection.

NOTE: `connectProcessorAndStateStores` (plural) is a public method that uses the internal <<connectProcessorAndStateStore, connectProcessorAndStateStore>> (singular) for a "bulk connect".

[NOTE]
====
`connectProcessorAndStateStores` is used when:

* `KStreamImpl` is requested to link:kafka-streams-KStreamImpl.adoc#doStreamTableJoin[doStreamTableJoin], link:kafka-streams-KStreamImpl.adoc#process[process], link:kafka-streams-KStreamImpl.adoc#transform[transform], link:kafka-streams-KStreamImpl.adoc#transformValues[transformValues]

* `KTableImpl` is requested to link:kafka-streams-KTableImpl.adoc#buildJoin[buildJoin]

* `Topology` is requested to link:kafka-streams-Topology.adoc#connectProcessorAndStateStores[connectProcessorAndStateStores]
====

=== [[connectProcessorAndStateStore]] `connectProcessorAndStateStore` Internal Method

[source, java]
----
void connectProcessorAndStateStore(
  final String processorName,
  final String stateStoreName)
----

`connectProcessorAndStateStore`...FIXME

NOTE: `connectProcessorAndStateStore` (singular) is an internal method that is used by the public <<connectProcessorAndStateStores, connectProcessorAndStateStores>> (plural).

NOTE: `connectProcessorAndStateStore` is used when `InternalTopologyBuilder` is requested to <<addStateStore, addStateStore>> and <<connectProcessorAndStateStores, connectProcessorAndStateStores>>
