== [[StreamsGraphNode]] StreamsGraphNode Contract -- Graph Nodes that Write to Topology

`StreamsGraphNode` is the <<contract, abstraction>> of <<implementations, graph nodes>> that can <<writeToTopology, write to a topology>>.

[[contract]]
.StreamsGraphNode Contract (Abstract Methods Only)
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| writeToTopology
a| [[writeToTopology]]

[source, java]
----
void writeToTopology(
  InternalTopologyBuilder topologyBuilder)
----

Used exclusively when `InternalStreamsBuilder` is requested to <<kafka-streams-internals-InternalStreamsBuilder.adoc#buildAndOptimizeTopology, build a topology>>

|===

`StreamsGraphNode` is used in <<kafka-streams-internals-InternalStreamsBuilder.adoc#, InternalStreamsBuilder>> to <<kafka-streams-internals-InternalStreamsBuilder.adoc#buildAndOptimizeTopology, build a topology>>. `InternalStreamsBuilder` uses the <<kafka-streams-internals-InternalStreamsBuilder.adoc#root, root node>> internally that all child `StreamsGraphNodes` can be <<kafka-streams-internals-InternalStreamsBuilder.adoc#addGraphNode, added to>>.

[source, scala]
----
import org.apache.kafka.streams.processor.internals.InternalTopologyBuilder
val intTopologyBuilder = new InternalTopologyBuilder

import org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder
val intStreamsBuilder = new InternalStreamsBuilder(intTopologyBuilder)

import org.apache.kafka.streams.state.Stores
val storeName = "input-stream"
val lruMapSupplier = Stores.lruMap(storeName, 5)
import org.apache.kafka.common.serialization.Serdes
import org.apache.kafka.streams.state.{KeyValueStore, StoreBuilder}
val storeBuilder = Stores.keyValueStoreBuilder(
  lruMapSupplier,
  Serdes.Long(),
  Serdes.Long())

intStreamsBuilder.addStateStore(storeBuilder)

val root = intStreamsBuilder.root
import org.apache.kafka.streams.kstream.internals.graph.StreamsGraphNode
assert(root.isInstanceOf[StreamsGraphNode])
scala> println(root.toString)
StreamsGraphNode{nodeName='root', buildPriority=null, hasWrittenToTopology=true, keyChangingOperation=false, valueChangingOperation=false, mergeNode=false, parentNodes=[]}

val children = root.children
assert(children.isInstanceOf[java.util.Collection[StreamsGraphNode]])

import scala.collection.JavaConverters._
val stateStoreNode = children.asScala.head
import org.apache.kafka.streams.kstream.internals.graph.StateStoreNode
assert(stateStoreNode.isInstanceOf[StateStoreNode])
scala> println(stateStoreNode)
StateStoreNode{ name='input-stream', logConfig={}, loggingEnabled='true'}

// Triggers StreamsGraphNode.writeToTopology of all nodes
intStreamsBuilder.buildAndOptimizeTopology

intTopologyBuilder.setApplicationId("required to complete optimization")

assert(intTopologyBuilder.allStateStoreName.asScala.head == storeName)
----

[[implementations]]
.StreamsGraphNodes (Direct Implementations and Extensions Only)
[cols="1,2",options="header",width="100%"]
|===
| StreamsGraphNode
| Description

| <<kafka-streams-internals-BaseJoinProcessorNode.adoc#, BaseJoinProcessorNode>>
| [[BaseJoinProcessorNode]] Base of <<kafka-streams-internals-KTableKTableJoinNode.adoc#, KTableKTableJoinNode>> and <<kafka-streams-internals-StreamStreamJoinNode.adoc#, StreamStreamJoinNode>>

| <<kafka-streams-internals-BaseRepartitionNode.adoc#, BaseRepartitionNode>>
| [[BaseRepartitionNode]] Base of <<kafka-streams-internals-GroupedTableOperationRepartitionNode.adoc#, GroupedTableOperationRepartitionNode>> and <<kafka-streams-internals-OptimizableRepartitionNode.adoc#, OptimizableRepartitionNode>>

| <<kafka-streams-internals-ProcessorGraphNode.adoc#, ProcessorGraphNode>>
| [[ProcessorGraphNode]] Represents stateless operators in <<kafka-streams-internals-KStreamImpl.adoc#, KStreamImpl>> and <<kafka-streams-internals-KTableImpl.adoc#, KTableImpl>>

Base of <<kafka-streams-internals-StatefulProcessorNode.adoc#, StatefulProcessorNode>>

| <<kafka-streams-internals-StateStoreNode.adoc#, StateStoreNode>>
| [[StateStoreNode]] Represents <<kafka-streams-StreamsBuilder.adoc#addStateStore, StreamsBuilder.addStateStore>> operator

Base of <<kafka-streams-internals-GlobalStoreNode.adoc#, GlobalStoreNode>>

| <<kafka-streams-internals-StreamSinkNode.adoc#, StreamSinkNode>>
| [[StreamSinkNode]] Represents <<kafka-streams-internals-KStreamImpl.adoc#to, KStreamImpl.to>> operator

| <<kafka-streams-internals-StreamSourceNode.adoc#, StreamSourceNode>>
| [[StreamSourceNode]] Represents <<kafka-streams-StreamsBuilder.adoc#stream, StreamsBuilder.stream>> and <<kafka-streams-internals-KStreamImpl.adoc#through, KStreamImpl.through>> operators

Base of <<kafka-streams-internals-TableSourceNode.adoc#, TableSourceNode>>

| <<kafka-streams-internals-StreamTableJoinNode.adoc#, StreamTableJoinNode>>
| [[StreamTableJoinNode]] Represents <<kafka-streams-internals-KStreamImpl.adoc#join, KStreamImpl.join>> and <<kafka-streams-internals-KStreamImpl.adoc#leftJoin, KStreamImpl.leftJoin>> operators

| <<kafka-streams-internals-TableProcessorNode.adoc#, TableProcessorNode>>
| [[TableProcessorNode]] Represents <<kafka-streams-internals-KTableImpl.adoc#filter, KTableImpl.filter>>, <<kafka-streams-internals-KTableImpl.adoc#filterNot, KTableImpl.filterNot>>, <<kafka-streams-internals-KTableImpl.adoc#mapValues, KTableImpl.mapValues>>, and <<kafka-streams-internals-KTableImpl.adoc#transformValues, KTableImpl.transformValues>> operators

|===

[[creating-instance]][[nodeName]]
`StreamsGraphNode` takes a single *node name* to be created.

NOTE: `StreamsGraphNode` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete StreamsGraphNodes>> and as the <<kafka-streams-internals-InternalStreamsBuilder.adoc#root, root node of InternalStreamsBuilder>>.

=== [[isValueChangingOperation]] `isValueChangingOperation` Method

[source, java]
----
boolean isValueChangingOperation()
----

`isValueChangingOperation` simply returns the <<valueChangingOperation, valueChangingOperation>> internal flag.

NOTE: `isValueChangingOperation` is used exclusively when `InternalStreamsBuilder` is requested to <<kafka-streams-internals-InternalStreamsBuilder.adoc#getKeyChangingParentNode, find the key-changing parent node>>.

=== [[setValueChangingOperation]] `setValueChangingOperation` Method

[source, java]
----
void setValueChangingOperation(
  boolean valueChangingOperation)
----

`setValueChangingOperation` simply sets the <<valueChangingOperation, valueChangingOperation>> internal flag to the given `valueChangingOperation` value.

NOTE: `setValueChangingOperation` is used when `KStreamImpl` is requested to <<kafka-streams-internals-KStreamImpl.adoc#mapValues, mapValues>>, <<kafka-streams-internals-KStreamImpl.adoc#flatMapValues, flatMapValues>>, <<kafka-streams-internals-KStreamImpl.adoc#doTransformValues, doTransformValues>>, and <<kafka-streams-internals-KStreamImpl.adoc#doFlatTransformValues, doFlatTransformValues>>

=== [[addChild]] Adding Child Node -- `addChild` Method

[source, java]
----
void addChild(
  StreamsGraphNode childNode)
----

`addChild`...FIXME

NOTE: `addChild` is used when `InternalStreamsBuilder` is requested to <<kafka-streams-internals-InternalStreamsBuilder.adoc#addGraphNode, add a child node>> and <<maybeOptimizeRepartitionOperations, maybeOptimizeRepartitionOperations>>.

=== [[toString]] Describing Itself (Textual Representation) -- `toString` Method

[source, java]
----
String toString()
----

NOTE: `toString` is part of the link:++https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Object.html#toString()++[java.lang.Object] for a string representation of the object.

`toString`...FIXME

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| valueChangingOperation
a| [[valueChangingOperation]] Represents whether the `StreamsGraphNode` is *value-changing* and changes record values (`true`) or not (`false`)

* Set via <<setValueChangingOperation, setValueChangingOperation>>

* Available as <<isValueChangingOperation, isValueChangingOperation>>

Used when `StreamsGraphNode` is requested for the <<toString, textual representation>>

|===
