== [[Materialized]] Materialized -- State Store Materialization

`Materialized` is the <<interface, interface>> to describe how to materialize a <<kafka-streams-StateStore.adoc#, state store>> (for a <<kafka-streams-KTable.adoc#, KTable>>).

`Materialized` is used for the following:

* In <<kafka-streams-StreamsBuilder.adoc#, StreamsBuilder>> high-level stream processing DSL to create <<kafka-streams-StreamsBuilder.adoc#table, KTables>> (incl. <<kafka-streams-StreamsBuilder.adoc#globalTable, global KTables>>)

* <<kafka-streams-KTable.adoc#, KTable>>

* For `count`, `reduce` and `aggregate` operators in <<kafka-streams-KGroupedStream.adoc#, KGroupedStream>>, <<kafka-streams-KGroupedTable.adoc#, KGroupedTable>>, <<kafka-streams-SessionWindowedKStream.adoc#, SessionWindowedKStream>>, <<kafka-streams-TimeWindowedKStream.adoc#, TimeWindowedKStream>>

`Materialized` is <<creating-instance, created>> using the <<factory-methods, factory methods>>.

[[factory-methods]]
.Materialized Factory Methods
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| as
a| [[as-KeyValueStore]]

[source, java]
----
Materialized<K, V, KeyValueStore<Bytes, byte[]>> as(final KeyValueBytesStoreSupplier supplier)
----

Creates a `Materialized` with a <<kafka-streams-StateStore-KeyValueStore.adoc#, KeyValueStore>> for a given <<kafka-streams-KeyValueBytesStoreSupplier.adoc#, KeyValueBytesStoreSupplier>>

| as
a| [[as-SessionStore]]

[source, java]
----
Materialized<K, V, SessionStore<Bytes, byte[]>> as(final SessionBytesStoreSupplier supplier)
----

Creates a `Materialized` with a <<kafka-streams-StateStore-SessionStore.adoc#, SessionStore>> for a given <<kafka-streams-SessionBytesStoreSupplier.adoc#, SessionBytesStoreSupplier>>

| as
a| [[as-String]]

[source, java]
----
Materialized<K, V, S> as(final String storeName)
----

Creates a `Materialized` for the <<kafka-streams-StateStore.adoc#, StateStore>> with the `storeName`

| as
a| [[as-WindowStore]]

[source, java]
----
Materialized<K, V, WindowStore<Bytes, byte[]>> as(final WindowBytesStoreSupplier supplier)
----

Creates a `Materialized` with a <<kafka-streams-StateStore-WindowStore.adoc#, WindowStore>> for a given <<kafka-streams-WindowBytesStoreSupplier.adoc#, WindowBytesStoreSupplier>>

| with
a| [[with]]

[source, java]
----
Materialized<K, V, S> with(final Serde<K> keySerde, final Serde<V> valueSerde)
----

Creates a `Materialized` with the ``Serde``s (for the keys and values)
|===

[[with-methods]]
.Materialized's with Methods
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| withCachingDisabled
a| [[withCachingDisabled]]

[source, java]
----
Materialized<K, V, S> withCachingDisabled()
----

Creates a `Materialized` with <<cachingEnabled, caching disabled>>

| withCachingEnabled
a| [[withCachingEnabled]]

[source, java]
----
Materialized<K, V, S> withCachingEnabled()
----

Creates a `Materialized` with <<cachingEnabled, caching enabled>>

| withKeySerde
a| [[withKeySerde]]

[source, java]
----
Materialized<K, V, S> withKeySerde(final Serde<K> keySerde)
----

Creates a `Materialized` with the <<keySerde, Serde for keys>>

| withLoggingDisabled
a| [[withLoggingDisabled]]

[source, java]
----
Materialized<K, V, S> withLoggingDisabled()
----

Creates a `Materialized` with <<loggingEnabled, logging disabled>>

| withLoggingEnabled
a| [[withLoggingEnabled]]

[source, java]
----
Materialized<K, V, S> withLoggingEnabled(final Map<String, String> config)
----

Creates a `Materialized` with <<loggingEnabled, logging enabled>>

| withValueSerde
a| [[withValueSerde]]

[source, java]
----
Materialized<K, V, S> withValueSerde(final Serde<V> valueSerde)
----

Creates a `Materialized` with the <<valueSerde, Serde for values>>
|===

=== [[creating-instance]] Creating Materialized Instance

`Materialized` takes one of the following when created:

* [[storeName]] Name of the <<kafka-streams-StateStore.adoc#, state store>>
* [[storeSupplier]] <<kafka-streams-StoreSupplier.adoc#, StoreSupplier>>
