== [[TaskManager]] TaskManager

`TaskManager` is...FIXME

[[logging]]
[TIP]
====
Enable `TRACE` logging level for `org.apache.kafka.streams.processor.internals.TaskManager` logger to see what happens inside.

Add the following line to `log4j.properties`:

```
log4j.logger.org.apache.kafka.streams.processor.internals.TaskManager=TRACE
```

Refer to link:kafka-logging.adoc#log4j.properties[Application Logging Using log4j].
====

=== [[addStreamTasks]] `addStreamTasks` Internal Method

[source, java]
----
void addStreamTasks(final Collection<TopicPartition> assignment)
----

`addStreamTasks`...FIXME

NOTE: `addStreamTasks` is used exclusively when `TaskManager` is requested to <<createTasks, create processor tasks for assigned topic partitions>>.

=== [[updateSubscriptionsFromAssignment]] `updateSubscriptionsFromAssignment` Method

[source, java]
----
void updateSubscriptionsFromAssignment(List<TopicPartition> partitions)
----

`updateSubscriptionsFromAssignment`...FIXME

NOTE: `updateSubscriptionsFromAssignment` is used exclusively when `StreamPartitionAssignor` is requested to link:kafka-streams-StreamPartitionAssignor.adoc#onAssignment[onAssignment]

=== [[updateSubscriptionsFromMetadata]] `updateSubscriptionsFromMetadata` Method

[source, java]
----
void updateSubscriptionsFromMetadata(Set<String> topics)
----

`updateSubscriptionsFromMetadata`...FIXME

NOTE: `updateSubscriptionsFromMetadata` is used when `StreamPartitionAssignor` is requested to link:kafka-streams-StreamPartitionAssignor.adoc#subscription[subscription]

=== [[createTasks]] Creating Processor Tasks for Assigned Topic Partitions -- `createTasks` Method

[source, java]
----
void createTasks(final Collection<TopicPartition> assignment)
----

`createTasks`...FIXME

NOTE: `createTasks` is used exclusively when `RebalanceListener` handles link:kafka-streams-StreamThread-RebalanceListener.adoc#onPartitionsAssigned[onPartitionsAssigned].

=== [[addStandbyTasks]] `addStandbyTasks` Internal Method

[source, java]
----
void addStreamTasks(final Collection<TopicPartition> assignment)
----

`addStandbyTasks`...FIXME

NOTE: `addStandbyTasks` is used exclusively when `TaskManager` is requested to <<createTasks, create tasks for assigned topic partitions>>.

=== [[process]] `process` Method

[source, java]
----
int process()
----

`process`...FIXME

NOTE: `process` is used exclusively when `StreamThread` is requested to link:kafka-streams-StreamThread.adoc#processAndMaybeCommit[processAndMaybeCommit].

=== [[updateNewAndRestoringTasks]] `updateNewAndRestoringTasks` Method

[source, java]
----
boolean updateNewAndRestoringTasks()
----

`updateNewAndRestoringTasks`...FIXME

NOTE: `updateNewAndRestoringTasks` is used exclusively when `StreamThread` is requested to link:kafka-streams-StreamThread.adoc#runOnce[consume records once].

=== [[activeTask]] Getting Active Stream Processor Task for Topic Partition -- `activeTask` Method

[source, java]
----
StreamTask activeTask(final TopicPartition partition)
----

`activeTask`...FIXME

NOTE: `activeTask` is used exclusively when `StreamThread` is requested to link:kafka-streams-StreamThread.adoc#addRecordsToTasks[addRecordsToTasks].

=== [[hasActiveRunningTasks]] `hasActiveRunningTasks` Method

[source, java]
----
boolean hasActiveRunningTasks()
----

`hasActiveRunningTasks`...FIXME

NOTE: `hasActiveRunningTasks` is used exclusively when `StreamThread` is requested to link:kafka-streams-StreamThread.adoc#runOnce[consume records once].
