== [[SessionWindowedKStreamImpl]] SessionWindowedKStreamImpl -- Default SessionWindowedKStream

`SessionWindowedKStreamImpl` is a concrete link:kafka-streams-AbstractStream.adoc[AbstractStream] and a link:kafka-streams-SessionWindowedKStream.adoc[SessionWindowedKStream] (with the default implementation of <<aggregate, aggregate>>, <<count, count>> and <<reduce, reduce>> operators).

`SessionWindowedKStreamImpl` is <<creating-instance, created>> exclusively when `KGroupedStreamImpl` is requested to link:kafka-streams-internals-KGroupedStreamImpl.adoc#windowedBy[windowedBy].

[[internal-registries]]
.SessionWindowedKStreamImpl's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `countMerger`
| [[countMerger]] `Merger` of `K` keys and `Long` values that simply adds two values together.

Used as the merger in <<count, count>>

| `reduceInitializer`
| [[reduceInitializer]] `Initializer<V>` that simply returns `null` when executed.

Used as the initializer in <<reduce, reduce>>
|===

=== [[aggregate]] `aggregate` Method

[source, java]
----
KTable<Windowed<K>, T> aggregate(
  final Initializer<T> initializer,
  final Aggregator<? super K, ? super V, T> aggregator,
  final Merger<? super K, T> sessionMerger)
KTable<Windowed<K>, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator,
  final Merger<? super K, VR> sessionMerger,
  final Materialized<K, VR, SessionStore<Bytes, byte[]>> materialized)
----

NOTE: `aggregate` is part of link:kafka-streams-SessionWindowedKStream.adoc#aggregate[SessionWindowedKStream Contract] to...FIXME.

`aggregate`...FIXME

=== [[count]] `count` Method

[source, java]
----
KTable<Windowed<K>, Long> count()
KTable<Windowed<K>, Long> count(final Materialized<K, Long, SessionStore<Bytes, byte[]>> materialized)
----

NOTE: `count` is part of link:kafka-streams-SessionWindowedKStream.adoc#count[SessionWindowedKStream Contract] to...FIXME.

`count`...FIXME

=== [[reduce]] `reduce` Method

[source, java]
----
KTable<Windowed<K>, V> reduce(final Reducer<V> reducer)
KTable<Windowed<K>, V> reduce(
  final Reducer<V> reducer,
  final Materialized<K, V, SessionStore<Bytes, byte[]>> materialized)
----

NOTE: `reduce` is part of link:kafka-streams-SessionWindowedKStream.adoc#reduce[SessionWindowedKStream Contract] to...FIXME.

`reduce`...FIXME

=== [[creating-instance]] Creating SessionWindowedKStreamImpl Instance

`SessionWindowedKStreamImpl` takes the following when created:

* [[windows]] `SessionWindows`
* [[builder]] link:kafka-streams-InternalStreamsBuilder.adoc[InternalStreamsBuilder]
* [[sourceNodes]] Names of the source nodes
* [[name]] Name
* [[keySerde]] Key Serde (`Serde<K>`)
* [[valSerde]] Value Serde (`Serde<V>`)
* [[aggregateBuilder]] link:kafka-streams-internals-GroupedStreamAggregateBuilder.adoc[GroupedStreamAggregateBuilder<K, V>]

`SessionWindowedKStreamImpl` initializes the <<internal-registries, internal registries and counters>>.

=== [[doAggregate]] `doAggregate` Internal Method

[source, java]
----
KTable<Windowed<K>, VR> doAggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator,
  final Merger<? super K, VR> merger,
  final Serde<VR> serde)
----

`doAggregate`...FIXME

NOTE: `doAggregate` is used when `SessionWindowedKStreamImpl` is requested to <<count, count>>, <<aggregate, aggregate>> and <<reduce, reduce>>.

=== [[materialize]] Materializing StoreBuilder (of SessionStores) -- `materialize` Internal Method

[source, java]
----
StoreBuilder<SessionStore<K, VR>> materialize(
  final MaterializedInternal<K, VR, SessionStore<Bytes, byte[]>> materialized)
----

`materialize`...FIXME

NOTE: `materialize` is used exclusively when `SessionWindowedKStreamImpl` is requested to <<aggregate, aggregate>>.

=== [[storeBuilder]] `storeBuilder` Internal Method

[source, java]
----
StoreBuilder<SessionStore<K, VR>> storeBuilder(
  final String storeName,
  final Serde<VR> aggValueSerde)
----

`storeBuilder`...FIXME

NOTE: `storeBuilder` is used exclusively when `SessionWindowedKStreamImpl` is requested to <<doAggregate, doAggregate>> (when requested to <<count, count>>, <<aggregate, aggregate>> and <<reduce, reduce>>).

=== [[aggregatorForReducer]] `aggregatorForReducer` Internal Method

[source, java]
----
Aggregator<K, V, V> aggregatorForReducer(final Reducer<V> reducer)
----

`aggregatorForReducer`...FIXME

NOTE: `aggregatorForReducer` is used when...FIXME

=== [[mergerForAggregator]] `mergerForAggregator` Internal Method

[source, java]
----
Merger<K, V> mergerForAggregator(final Aggregator<K, V, V> aggregator)
----

`mergerForAggregator`...FIXME

NOTE: `mergerForAggregator` is used when...FIXME

=== [[doCount]] `doCount` Internal Method

[source, java]
----
KTable<Windowed<K>, Long> doCount(final Materialized<K, Long, SessionStore<Bytes, byte[]>> materialized)
----

`doCount`...FIXME

NOTE: `doCount` is used exclusively when `SessionWindowedKStreamImpl` is requested to <<count, count>>.
