== [[StateStoreFactory]] StateStoreFactory

`StateStoreFactory` is the <<contract, contract>> for...FIXME

NOTE: `StateStoreFactory` is an internal interface of link:kafka-streams-InternalTopologyBuilder.adoc[InternalTopologyBuilder].

[[contract]]
[source, java]
----
package org.apache.kafka.streams.processor.internals;

interface StateStoreFactory {
  Set<String> users();
  boolean loggingEnabled();
  StateStore build();
  String name();
  boolean isWindowStore();
  Map<String, String> logConfig();
  long retentionPeriod();
}
----

.StateStoreFactory Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| `isWindowStore`
| [[isWindowStore]]

| `logConfig`
| [[logConfig]]

| `loggingEnabled`
| [[loggingEnabled]]

| `retentionPeriod`
| [[retentionPeriod]] Used exclusively when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#createChangelogTopicConfig[createChangelogTopicConfig].

| `users`
| [[users]] Names of the processors that are connected to a state store

Used when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#connectProcessorAndStateStore[connect a state store with a processor node] and link:kafka-streams-InternalTopologyBuilder.adoc#topicGroups[topicGroups]
|===

[[implementations]]
.StateStoreFactories
[cols="1,2",options="header",width="100%"]
|===
| StateStoreFactory
| Description

| [[AbstractStateStoreFactory]] link:kafka-streams-AbstractStateStoreFactory.adoc[AbstractStateStoreFactory]
|

| [[StoreBuilderFactory]] link:kafka-streams-StoreBuilderFactory.adoc[StoreBuilderFactory]
|

| [[StateStoreSupplierFactory]] link:kafka-streams-StateStoreSupplierFactory.adoc[StateStoreSupplierFactory]
|
|===
