== [[SinkNode]] SinkNode -- ProcessorNode with no Child Nodes

`SinkNode` is a custom <<kafka-streams-internals-ProcessorNode.adoc#, ProcessorNode>> with no <<addChild, child processor nodes>>.

`SinkNode` is <<creating-instance, created>> exclusively when `SinkNodeFactory` is requested to <<kafka-streams-internals-InternalTopologyBuilder-SinkNodeFactory.adoc#build, build a processor node>> (when `InternalTopologyBuilder` is requested to <<kafka-streams-internals-InternalTopologyBuilder.adoc#build, build a topology of processor nodes>>).

`SinkNode` uses a <<topicExtractor, TopicNameExtractor>> for *dynamic routing* when <<process, processing a record>>.

=== [[process]] Processing Record -- `process` Method

[source, java]
----
void process(final K key, final V value)
----

NOTE: `process` is part of <<kafka-streams-internals-ProcessorNode.adoc#process, ProcessorNode Contract>> to process a record.

`process`...FIXME

=== [[creating-instance]] Creating SinkNode Instance

`SinkNode` takes the following when created:

* [[name]] Name of the sink
* [[topicExtractor]] <<kafka-streams-TopicNameExtractor.adoc#, TopicNameExtractor>>
* [[keySerializer]] Kafka `Serializer` for keys
* [[valSerializer]] Kafka `Serializer` for values
* [[partitioner]] <<kafka-streams-StreamPartitioner.adoc#, StreamPartitioner>>

=== [[addChild]] Adding Child Processor Node -- `addChild` Method

[source, java]
----
void addChild(final ProcessorNode<?, ?> child)
----

NOTE: `addChild` is part of link:kafka-streams-internals-ProcessorNode.adoc#addChild[ProcessorNode Contract] to add a child processor node.

`addChild` simply throws an `UnsupportedOperationException` with the following message:

```
sink node does not allow addChild
```

=== [[init]] Initializing Processor Node -- `init` Method

[source, java]
----
void init(final ProcessorContext context)
----

NOTE: `init` is part of link:kafka-streams-internals-ProcessorNode.adoc#init[ProcessorNode Contract] to...FIXME.

`init`...FIXME

=== [[toString]] Describing Itself (Textual Representation) -- `toString` Method

[source, java]
----
void toString(final ProcessorContext context)
----

NOTE: `toString` is part of link:kafka-streams-internals-ProcessorNode.adoc#toString[ProcessorNode Contract] for the human-friendly / textual representation of a `ProcessorNode`.

`toString`...FIXME
