== [[KGroupedStreamImpl]] KGroupedStreamImpl

`KGroupedStreamImpl` is a concrete link:kafka-streams-AbstractStream.adoc[AbstractStream] and a link:kafka-streams-KGroupedStream.adoc[KGroupedStream].

=== [[repartitionIfRequired]] `repartitionIfRequired` Internal Method

[source, java]
----
String repartitionIfRequired(final String queryableStoreName)
----

`repartitionIfRequired`...FIXME

NOTE: `repartitionIfRequired` is used when...FIXME

=== [[aggregate]] `aggregate` Method

[source, java]
----
KTable<K, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator)
KTable<K, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator,
  final Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
// DEPRECATED ARE NOT LISTED HERE
----

NOTE: `aggregate` is part of link:kafka-streams-KGroupedStream.adoc#aggregate[KGroupedStream Contract] to...FIXME.

`aggregate`...FIXME

=== [[reduce]] `reduce` Method

[source, java]
----
KTable<K, V> reduce(final Reducer<V> reducer)
KTable<K, V> reduce(
  final Reducer<V> reducer,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
// DEPRECATED ARE NOT LISTED HERE
----

NOTE: `reduce` is part of link:kafka-streams-KGroupedStream.adoc#reduce[KGroupedStream Contract] to...FIXME.

`reduce`...FIXME

=== [[windowedBy]] `windowedBy` Method

[source, java]
----
SessionWindowedKStream<K, V> windowedBy(final SessionWindows windows)
<W extends Window> TimeWindowedKStream<K, V> windowedBy(final Windows<W> windows)
----

NOTE: `windowedBy` is part of link:kafka-streams-KGroupedStream.adoc#windowedBy[KGroupedStream Contract] to...FIXME.

`windowedBy`...FIXME
