== [[PartitionGroup]] PartitionGroup

`PartitionGroup` manages <<partitionQueues, RecordQueues per Kafka TopicPartition>> (as given when <<creating-instance, created>> for a <<kafka-streams-StreamTask.adoc#partitionGroup, StreamTask>>).

[[creating-instance]]
[[partitionQueues]]
`PartitionGroup` takes a collection of <<kafka-streams-RecordQueue.adoc#, RecordQueues>> per Kafka https://kafka.apache.org/20/javadoc/org/apache/kafka/common/TopicPartition.html[TopicPartition] when created.

[[internal-registries]]
.PartitionGroup's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `queuesByTime`
| [[queuesByTime]] A Java https://docs.oracle.com/javase/8/docs/api/java/util/PriorityQueue.html[PriorityQueue] that is an unbounded priority queue that uses link:kafka-streams-RecordQueue.adoc#timestamp[partition timestamps] for ordering.

| `totalBuffered`
| [[totalBuffered]]
|===

=== [[nextRecord]] `nextRecord` Method

[source, java]
----
StampedRecord nextRecord(final RecordInfo info)
----

`nextRecord`...FIXME

NOTE: `nextRecord` is used exclusively when `StreamTask` is link:kafka-streams-StreamTask.adoc#process[processing]...FIXME

=== [[addRawRecords]] Adding Records to RecordQueue (For Kafka Partition) -- `addRawRecords` Method

[source, scala]
----
int addRawRecords(
  final TopicPartition partition,
  final Iterable<ConsumerRecord<byte[], byte[]>> rawRecords)
----

`addRawRecords` looks up the <<kafka-streams-RecordQueue.adoc#, RecordQueue>> for the input Kafka link:https://kafka.apache.org/20/javadoc/org/apache/kafka/common/TopicPartition.html[TopicPartition] (in the <<partitionQueues, partitionQueues>>).

`addRawRecords` requests the `RecordQueue` for the link:kafka-streams-RecordQueue.adoc#size[size] and to link:kafka-streams-RecordQueue.adoc#addRawRecords[add Kafka ConsumerRecords (as StampedRecords)].

`addRawRecords` inserts the `RecordQueue` into the <<queuesByTime, queuesByTime>> priority queue only if the `RecordQueue` was empty before.

`addRawRecords` adds the difference between the old and current sizes to <<totalBuffered, totalBuffered>>.

`addRawRecords` returns the current (new) size of the `RecordQueue`.

NOTE: `addRawRecords` is used exclusively when `StreamTask` is requested to link:kafka-streams-StreamTask.adoc#addRecords[addRecords].

=== [[clear]] `clear` Method

[source, java]
----
void clear()
----

`clear` removes all of the elements from the <<queuesByTime, queuesByTime>> and requests every link:kafka-streams-RecordQueue.adoc[RecordQueue] (in the internal <<partitionQueues, partitionQueues>> registry) to link:kafka-streams-RecordQueue.adoc#clear[clear itself].

NOTE: `clear` is used exclusively when `StreamTask` is requested to link:kafka-streams-StreamTask.adoc#closeTopology[closeTopology].

=== [[numBuffered]] `numBuffered` Method

[source, java]
----
int numBuffered(final TopicPartition partition)
----

`numBuffered`...FIXME

NOTE: `numBuffered` is used when...FIXME

=== [[timestamp]] Minimum Partition Timestamp Across All TopicPartitions -- `timestamp` Method

[source, java]
----
long timestamp()
----

`timestamp` simply iterates over the <<partitionQueues, TopicPartitions>> and requests every `RecordQueue` for the <<kafka-streams-RecordQueue.adoc#timestamp, partition timestamp>>.

In the end, `timestamp` returns the oldest partition timestamp (time-wise).

NOTE: `timestamp` is used exclusively when `StreamTask` is requested to <<kafka-streams-StreamTask.adoc#maybePunctuateStreamTime, maybePunctuateStreamTime>>
