== [[TableProcessorNode]] TableProcessorNode

`TableProcessorNode` is a concrete <<kafka-streams-internals-StreamsGraphNode.adoc#, StreamsGraphNode>> that is <<creating-instance, created>> when `KTableImpl` is requested to <<kafka-streams-internals-KTableImpl.adoc#doFilter, doFilter>>, <<kafka-streams-internals-KTableImpl.adoc#doMapValues, doMapValues>>, and <<kafka-streams-internals-KTableImpl.adoc#doTransformValues, doTransformValues>>.

In other words, `TableProcessorNode` represents <<kafka-streams-internals-KTableImpl.adoc#filter, KTableImpl.filter>>, <<kafka-streams-internals-KTableImpl.adoc#filterNot, KTableImpl.filterNot>>, <<kafka-streams-internals-KTableImpl.adoc#mapValues, KTableImpl.mapValues>>, and <<kafka-streams-internals-KTableImpl.adoc#transformValues, KTableImpl.transformValues>> operators.

=== [[creating-instance]] Creating TableProcessorNode Instance

`TableProcessorNode` takes the following to be created:

* [[nodeName]] Node name
* [[processorParameters]] `ProcessorParameters<K, V>`
* [[storeBuilder]] <<kafka-streams-StoreBuilder.adoc#, StoreBuilder>> of <<kafka-streams-TimestampedKeyValueStore.adoc#, TimestampedKeyValueStore>> (`StoreBuilder<TimestampedKeyValueStore<K, V>>`)
* [[storeNames]] Names of state stores

NOTE: <<storeNames, Names of state stores>> can only be specified when `TableProcessorNode` is created when `KTableImpl` is requested to <<kafka-streams-internals-KTableImpl.adoc#doTransformValues, doTransformValues>> (when requested to <<kafka-streams-internals-KTableImpl.adoc#transformValues, transformValues>>).

=== [[writeToTopology]] `writeToTopology` Method

[source, java]
----
void writeToTopology(
  InternalTopologyBuilder topologyBuilder)
----

NOTE: `writeToTopology` is part of the <<kafka-streams-internals-StreamsGraphNode.adoc#writeToTopology, StreamsGraphNode Contract>> to...FIXME.

`writeToTopology` requests the given <<kafka-streams-internals-InternalTopologyBuilder.adoc#, InternalTopologyBuilder>> to <<kafka-streams-internals-InternalTopologyBuilder.adoc#addProcessor, add a processor>> (with the `processorName` and `processorSupplier` of the given <<processorParameters, ProcessorParameters>>).

`writeToTopology` requests the given `InternalTopologyBuilder` to <<kafka-streams-internals-InternalTopologyBuilder.adoc#connectProcessorAndStateStores, connect the processor with the state stores>> if there are any <<storeNames, store names>> specified.

`writeToTopology` requests the given `InternalTopologyBuilder` to <<kafka-streams-internals-InternalTopologyBuilder.adoc#addStateStore, add a state store>> if a <<storeBuilder, StoreBuilder>> is specified.
