== [[KTableImpl]] KTableImpl

`KTableImpl` is...FIXME

=== [[mapValues]] `mapValues` Method

[source, java]
----
<V1> KTable<K, V1> mapValues(
  final ValueMapper<? super V, ? extends V1> mapper)
<VR> KTable<K, VR> mapValues(
  final ValueMapper<? super V, ? extends VR> mapper,
  final Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
<VR> KTable<K, VR> mapValues(
  final ValueMapperWithKey<? super K, ? super V, ? extends VR> mapper)
<VR> KTable<K, VR> mapValues(
  final ValueMapperWithKey<? super K, ? super V, ? extends VR> mapper,
  final Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

NOTE: `mapValues` is part of link:kafka-streams-KTable.adoc#mapValues[KTable Contract] to...FIXME.

`mapValues`...FIXME

NOTE: `mapValues` is used when...FIXME

=== [[join]] `join` Method

[source, java]
----
<V1, R> KTable<K, R> join(
  final KTable<K, V1> other,
  final ValueJoiner<? super V, ? super V1, ? extends R> joiner)
<VO, VR> KTable<K, VR> join(
  final KTable<K, VO> other,
  final ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  final Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

NOTE: `join` is part of link:kafka-streams-KTable.adoc#join[KTable Contract] to...FIXME.

`join`...FIXME

NOTE: `join` is used when...FIXME

=== [[leftJoin]] `leftJoin` Method

[source, java]
----
<V1, R> KTable<K, R> leftJoin(
  final KTable<K, V1> other,
  final ValueJoiner<? super V, ? super V1, ? extends R> joiner)
<VO, VR> KTable<K, VR> leftJoin(
  final KTable<K, VO> other,
  final ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  final Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

NOTE: `leftJoin` is part of link:kafka-streams-KTable.adoc#leftJoin[KTable Contract] to...FIXME.

`leftJoin`...FIXME

NOTE: `leftJoin` is used when...FIXME

=== [[outerJoin]] `outerJoin` Method

[source, java]
----
<V1, R> KTable<K, R> outerJoin(
  final KTable<K, V1> other,
  final ValueJoiner<? super V, ? super V1, ? extends R> joiner)
<VO, VR> KTable<K, VR> outerJoin(
  final KTable<K, VO> other,
  final ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  final Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

NOTE: `outerJoin` is part of link:kafka-streams-KTable.adoc#outerJoin[KTable Contract] to...FIXME.

`outerJoin`...FIXME

NOTE: `outerJoin` is used when...FIXME

=== [[doFilter]] `doFilter` Internal Method

[source, java]
----
KTable<K, V> doFilter(
  final Predicate<? super K, ? super V> predicate,
  final MaterializedInternal<K, V, KeyValueStore<Bytes, byte[]>> materialized,
  final boolean filterNot)
----

`doFilter`...FIXME

NOTE: `doFilter` is used when...FIXME

=== [[buildJoin]] `buildJoin` Internal Method

[source, java]
----
<V1, R> KTable<K, R> buildJoin(
  final AbstractStream<K> other,
  final ValueJoiner<? super V, ? super V1, ? extends R> joiner,
  final boolean leftOuter,
  final boolean rightOuter,
  final String joinMergeName,
  final String internalQueryableName)
----

`buildJoin` link:kafka-streams-AbstractStream.adoc#ensureJoinableWith[ensureJoinableWith] the `other` stream.

`buildJoin`...FIXME

NOTE: `buildJoin` is used exclusively when `KTableImpl` is requested to <<doJoin, doJoin>>.

=== [[doJoin]] `doJoin` Internal Method

[source, java]
----
<VO, VR> KTable<K, VR> doJoin(
  final KTable<K, VO> other,
  final ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  final MaterializedInternal<K, VR, KeyValueStore<Bytes, byte[]>> materialized,
  final boolean leftOuter,
  final boolean rightOuter)
----

`doJoin`...FIXME

NOTE: `doJoin` is used when `KTableImpl` is requested to <<join, join>>, <<leftJoin, leftJoin>> and <<outerJoin, outerJoin>>.

=== [[valueGetterSupplier]] `valueGetterSupplier` Method

[source, java]
----
KTableValueGetterSupplier<K, V> valueGetterSupplier()
----

`valueGetterSupplier`...FIXME

NOTE: `valueGetterSupplier` is used when...FIXME

=== [[enableSendingOldValues]] `enableSendingOldValues` Method

[source, java]
----
void enableSendingOldValues()
----

`enableSendingOldValues`...FIXME

NOTE: `enableSendingOldValues` is used when...FIXME
