== [[StreamsConfig]] StreamsConfig -- Configuration Properties for Kafka Clients

`StreamsConfig` is Apache Kafka's https://kafka.apache.org/20/javadoc/org/apache/kafka/common/config/AbstractConfig.html[AbstractConfig] for the <<properties, configuration properties>> for Kafka Streams applications.

[[properties]]
.Configuration Properties
[cols="1m,1m,1",options="header",width="100%"]
|===
| Name
| Property
| Type

| DEFAULT_TIMESTAMP_EXTRACTOR_CLASS_CONFIG
| default.timestamp.extractor
| [[default.timestamp.extractor]][[DEFAULT_TIMESTAMP_EXTRACTOR_CLASS_CONFIG]] Default timestamp extractor class that implements the <<kafka-streams-TimestampExtractor.adoc#, org.apache.kafka.streams.processor.TimestampExtractor>> interface.
|===

`StreamsConfig` is also used for the following Kafka clients (that Kafka Streams uses under the covers):

* <<getConsumerConfigs, Consumer>>

* <<getProducerConfigs, Producer>>

* <<getAdminConfigs, AdminClient>>

* <<getRestoreConsumerConfigs, getRestoreConsumerConfigs>>

[source, scala]
----
import org.apache.kafka.streams.StreamsConfig
val props = new java.util.Properties()
props.put(StreamsConfig.APPLICATION_ID_CONFIG, "appId")
import org.apache.kafka.clients.consumer.ConsumerConfig
props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:8082")
val conf = new StreamsConfig(props)

// Consumer Properties
val consumerConfigs = conf.getConsumerConfigs("groupId", "clientId")
import collection.JavaConverters._
scala> consumerConfigs.asScala.map { case (key, value) => s"$key -> $value" }.foreach(println)
replication.factor -> 1
num.standby.replicas -> 0
max.poll.records -> 1000
group.id -> groupId
partition.assignment.strategy -> org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor
bootstrap.servers -> localhost:8082
enable.auto.commit -> false
admin.retries -> 5
application.server ->
max.poll.interval.ms -> 2147483647
auto.offset.reset -> earliest
windowstore.changelog.additional.retention.ms -> 86400000
internal.leave.group.on.close -> false
application.id -> groupId
client.id -> clientId-consumer
----

`StreamsConfig` does not allow users to configure certain Kafka configurations (e.g. for <<CONSUMER_DEFAULT_OVERRIDES, consumer>>) that are simply <<checkIfUnexpectedUserSpecifiedConsumerConfig, removed>> (with a WARN message in the logs).

[[CONSUMER_DEFAULT_OVERRIDES]]
.Kafka Consumer Non-Overridable Configurations
[cols="1,1,2",options="header",width="100%"]
|===
| Name
| Value
| Description

| [[max.poll.records]] `max.poll.records`
| `1000`
|

| [[auto.offset.reset]] `auto.offset.reset`
| `earliest`
|

| [[buffered.records.per.partition]] `buffered.records.per.partition`
| `1000`
| The maximum number of records to buffer per partition

| [[enable.auto.commit]] `enable.auto.commit`
| `false`
|

| [[internal.leave.group.on.close]] `internal.leave.group.on.close`
| `false`
|

| [[max.poll.interval.ms]] `max.poll.interval.ms`
| `Integer.MAX_VALUE`
|
|===

[[CONSUMER_PREFIX]]
`StreamsConfig` uses `consumer` prefix for custom Kafka configurations of a Kafka consumer.

=== [[getConsumerConfigs]] Getting Kafka Consumer Configuration -- `getConsumerConfigs` Method

[source, java]
----
Map<String, Object> getConsumerConfigs(
  final String groupId,
  final String clientId)
----

`getConsumerConfigs` <<getCommonConsumerConfigs, gets the common consumer configuration>> first.

`getConsumerConfigs` then adds the <<getConsumerConfigs-properties, additional consumer configuration properties>>.

[[getConsumerConfigs-properties]]
.Kafka Consumer Configuration Properties
[cols="1,1,2",options="header",width="100%"]
|===
| Name
| Value
| Description

| [[application.id]] `application.id`
| `groupId`
|

| [[group.id]] `group.id`
| `groupId`
|

| [[client.id]] `client.id`
| `[clientId]-consumer`
|
|===

CAUTION: FIXME

NOTE: `getConsumerConfigs` is used exclusively when `StreamThread` is link:kafka-streams-StreamThread.adoc#create[created].

=== [[getProducerConfigs]] `getProducerConfigs` Method

[source, java]
----
Map<String, Object> getProducerConfigs(final String clientId)
----

`getProducerConfigs`...FIXME

NOTE: `getProducerConfigs` is used when...FIXME

=== [[getAdminConfigs]] `getAdminConfigs` Method

[source, java]
----
Map<String, Object> getAdminConfigs(final String clientId)
----

`getAdminConfigs`...FIXME

NOTE: `getAdminConfigs` is used when...FIXME

=== [[clientProps]] Collecting Properties per Key -- `clientProps` Internal Method

[source, java]
----
Map<String, Object> clientProps(
  final Set<String> configNames,
  final Map<String, Object> originals)
----

`clientProps` collects the configuration properties from `originals` that have their names in the input `configNames`, i.e. includes the properties that have been listed in `configNames`.

NOTE: `clientProps` is used exclusively when `StreamsConfig` is requested to <<getClientPropsWithPrefix, getClientPropsWithPrefix>>.

=== [[getClientPropsWithPrefix]] Getting Subset of User Configuration by Given Names and Prefix -- `getClientPropsWithPrefix` Internal Method

[source, java]
----
Map<String, Object> getClientPropsWithPrefix(
  final String prefix,
  final Set<String> configNames)
----

`getClientPropsWithPrefix` takes only the properties (as passed in by a user) that have their keys in `configNames` and adds all properties with the given `prefix`.

Internally, `getClientPropsWithPrefix` <<clientProps, collects the configuration properties>> from the original values of Kafka properties as passed in by a user that have their names in `configNames`.

`getClientPropsWithPrefix` then copies all original settings with the given `prefix` (stripping the prefix before adding them) to the collected properties (and possibly overwriting some).

NOTE: `getClientPropsWithPrefix` uses link:++https://kafka.apache.org/10/javadoc/org/apache/kafka/common/config/AbstractConfig.html#originals--++[AbstractConfig.originals] to get the original values of Kafka properties as passed in by the user.

NOTE: `getClientPropsWithPrefix` is used when `StreamsConfig` is requested for <<getAdminConfigs, getAdminConfigs>>, <<getCommonConsumerConfigs, getCommonConsumerConfigs>>, <<getConsumerConfigs, getConsumerConfigs>> and <<getProducerConfigs, getProducerConfigs>>.

=== [[getCommonConsumerConfigs]] Getting Common Consumer Configuration -- `getCommonConsumerConfigs` Internal Method

[source, java]
----
Map<String, Object> getCommonConsumerConfigs()
----

`getCommonConsumerConfigs` <<getClientPropsWithPrefix, gets a subset of user configuration>> for a Kafka consumer as well as the properties with <<CONSUMER_PREFIX, consumer>> prefix.

NOTE: `getCommonConsumerConfigs` uses https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/consumer/ConsumerConfig.html[ConsumerConfig.configNames] for the list of the Kafka Consumer-specific configuration keys.

CAUTION: FIXME

NOTE: `getCommonConsumerConfigs` is used when `StreamsConfig` is requested for <<getConsumerConfigs, getConsumerConfigs>> and <<getRestoreConsumerConfigs, getRestoreConsumerConfigs>>.

=== [[checkIfUnexpectedUserSpecifiedConsumerConfig]] Removing "Illegal" User-Defined Configuration Properties -- `checkIfUnexpectedUserSpecifiedConsumerConfig` Internal Method

[source, java]
----
void checkIfUnexpectedUserSpecifiedConsumerConfig(
  final Map<String, Object> clientProvidedProps,
  final String[] nonConfigurableConfigs)
----

`checkIfUnexpectedUserSpecifiedConsumerConfig` removes non-configurable configurations (`nonConfigurableConfigs`) from user-defined configurations (`clientProvidedProps`) and logging a warning.

Internally, `checkIfUnexpectedUserSpecifiedConsumerConfig` iterates over `nonConfigurableConfigs`...FIXME

NOTE: `checkIfUnexpectedUserSpecifiedConsumerConfig` is used when `StreamsConfig` is requested for <<getCommonConsumerConfigs, getCommonConsumerConfigs>> and <<getProducerConfigs, getProducerConfigs>>.

=== [[getRestoreConsumerConfigs]] `getRestoreConsumerConfigs` Method

[source, java]
----
Map<String, Object> getRestoreConsumerConfigs(final String clientId)
----

`getRestoreConsumerConfigs`...FIXME

NOTE: `getRestoreConsumerConfigs` is used when...FIXME
