== [[StreamsBuilder]] StreamsBuilder -- High-Level Stream Processing DSL

`StreamsBuilder` provides the <<operators, operators>> for *high-level stream processing DSL* to <<build, build a processor topology>> (with sources, processors, sinks and state stores).

`StreamsBuilder` is one of the very first entities that you will be working with as a Kafka Streams developer.

TIP: Use <<kafka-streams-scala.adoc#, Scala API for Kafka Streams>> to make your Kafka Streams development more pleasant if Scala is your programming language.

[[operators]]
.StreamsBuilder API / Operators
[cols="1,2",options="header",width="100%"]
|===
| Operator
| Description

| <<addGlobalStore-detailed, addGlobalStore>>
a| [[addGlobalStore]]

[source, java]
----
StreamsBuilder addGlobalStore(
  final StoreBuilder storeBuilder,
  final String topic,
  final Consumed consumed,
  final ProcessorSupplier stateUpdateSupplier)
----

Adds a global <<kafka-streams-StateStore.adoc#, StateStore>> to the topology

| <<addStateStore-detailed, addStateStore>>
a| [[addStateStore]]

[source, java]
----
StreamsBuilder addStateStore(final StoreBuilder builder)
----

Adds a <<kafka-streams-StateStore.adoc#, StateStore>> to the topology

| <<build-detailed, build>>
a| [[build]]

[source, java]
----
Topology build()
----

Returns the <<kafka-streams-Topology.adoc#, Topology>>

| <<globalTable-internals, globalTable>>
a| [[globalTable]]

[source, java]
----
GlobalKTable<K, V> globalTable(final String topic)
GlobalKTable<K, V> globalTable(
  final String topic,
  final Consumed<K, V> consumed)
GlobalKTable<K, V> globalTable(
  final String topic,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
GlobalKTable<K, V> globalTable(
  final String topic,
  final Consumed<K, V> consumed,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
----

Adds a <<kafka-streams-GlobalKTable.adoc#, GlobalKTable>> to the topology

| <<stream-detailed, stream>>
a| [[stream]]

[source, java]
----
KStream<K, V> stream(final Collection<String> topics)
KStream<K, V> stream(
  final Collection<String> topics,
  final Consumed<K, V> consumed)
KStream<K, V> stream(final Pattern topicPattern)
KStream<K, V> stream(
  final Pattern topicPattern,
  final Consumed<K, V> consumed)
KStream<K, V> stream(final String topic)
KStream<K, V> stream(
  final String topic,
  final Consumed<K, V> consumed)
----

Creates a <<kafka-streams-KStream.adoc#, KStream>>

| <<table-detailed, table>>
a| [[table]]

[source, java]
----
KTable<K, V> table(final String topic)
KTable<K, V> table(
  final String topic,
  final Consumed<K, V> consumed)
KTable<K, V> table(
  final String topic,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
KTable<K, V> table(
  final String topic,
  final Consumed<K, V> consumed,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
----

Creates a <<kafka-streams-KTable.adoc#, KTable>>

|===

[[creating-instance]]
`StreamsBuilder` takes no arguments when created.

[source, scala]
----
import org.apache.kafka.streams.StreamsBuilder
val builder = new StreamsBuilder
----

A typical Kafka Streams application looks as follows:

[source, scala]
----
import org.apache.kafka.streams.StreamsBuilder
val builder = new StreamsBuilder

// Add a GlobalKTable with a global store if needed
builder
  .addGlobalStore(...)
  .globalTable(...)

// Add a KStream if needed
builder.stream(...)

// Add a KTable if needed
builder.table(...)

// In the end, build a topology
val topology = builder.build
----

[[topology]]
[[internalStreamsBuilder]]
When <<creating-instance, created>>, `StreamsBuilder` creates an empty <<kafka-streams-Topology.adoc#, topology>> (that you enrich using the <<operators, operators>>). The topology is then requested for the <<kafka-streams-Topology.adoc#internalTopologyBuilder, InternalTopologyBuilder>> that is in turn used to create an <<kafka-streams-InternalStreamsBuilder.adoc#, InternalStreamsBuilder>>.

In other words, `StreamsBuilder` offers a more <<operators, developer-friendly API>> for developing Kafka Streams applications as compared to the <<kafka-streams-InternalStreamsBuilder.adoc#, InternalStreamsBuilder>> API (and is a façade of `InternalStreamsBuilder`).

=== [[table-detailed]] Creating KTable -- `table` Method

[source, java]
----
KTable<K, V> table(final String topic)
KTable<K, V> table(
  final String topic,
  final Consumed<K, V> consumed)
KTable<K, V> table(
  final String topic,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
KTable<K, V> table(
  final String topic,
  final Consumed<K, V> consumed,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
----

`table`...FIXME

=== [[globalTable-internals]] Adding GlobalKTable to Topology -- `globalTable` Method

[source, java]
----
GlobalKTable<K, V> globalTable(final String topic)
GlobalKTable<K, V> globalTable(
  final String topic,
  final Consumed<K, V> consumed)
GlobalKTable<K, V> globalTable(
  final String topic,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
GlobalKTable<K, V> globalTable(
  final String topic,
  final Consumed<K, V> consumed,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
----

`globalTable` creates an <<kafka-streams-internals-ConsumedInternal.adoc#, ConsumedInternal>> for the given <<kafka-streams-Consumed.adoc#, Consumed>>.

`globalTable` creates a new <<kafka-streams-MaterializedInternal.adoc#, MaterializedInternal>> (with a new <<kafka-streams-Materialized.adoc#, Materialized>> with the `keySerde` and the `valueSerde` of the `ConsumedInternal`).

NOTE: The new <<kafka-streams-MaterializedInternal.adoc#, MaterializedInternal>> uses `KeyValueStore<Bytes, byte[]>` <<kafka-streams-StateStore.adoc#, StateStore>>.

`globalTable` requests the `MaterializedInternal` to <<kafka-streams-MaterializedInternal.adoc#generateStoreNameIfNeeded, generateStoreNameIfNeeded>> (with the <<internalStreamsBuilder, InternalStreamsBuilder>> and the input `topic` name).

In the end, `globalTable` requests the <<internalStreamsBuilder, InternalStreamsBuilder>> to <<kafka-streams-InternalStreamsBuilder.adoc#globalTable, add a GlobalKTable to the topology>> (with the `topic` name, the `ConsumedInternal` and the `MaterializedInternal`).

.Demo: Non-queryable GlobalKTable
[source, scala]
----
import org.apache.kafka.streams.scala._
import ImplicitConversions._
import Serdes._

import org.apache.kafka.streams.scala.StreamsBuilder
val builder = new StreamsBuilder

val globalTable = builder.globalTable[String, String](topic = "global-table")
scala> :type globalTable
org.apache.kafka.streams.kstream.GlobalKTable[String,String]

assert(globalTable.queryableStoreName == null)

val topology = builder.build
scala> println(topology.describe)
Topologies:
   Sub-topology: 0 for global store (will not generate tasks)
    Source: KTABLE-SOURCE-0000000001 (topics: [global-table])
      --> KTABLE-SOURCE-0000000002
    Processor: KTABLE-SOURCE-0000000002 (stores: [global-table-STATE-STORE-0000000000])
      --> none
      <-- KTABLE-SOURCE-0000000001
----

.Demo: Queryable GlobalKTable
[source, scala]
----
import org.apache.kafka.streams.scala._
import ImplicitConversions._
import Serdes._

import org.apache.kafka.streams.scala.StreamsBuilder
val builder = new StreamsBuilder

import org.apache.kafka.streams.state.Stores
val supplier = Stores.inMemoryKeyValueStore("queryable-store-name")

import org.apache.kafka.streams.scala.kstream.Materialized
val materialized = Materialized.as[String, String](supplier)
val zipCodes = builder.globalTable[String, String](topic = "zip-codes", materialized)

scala> :type zipCodes
org.apache.kafka.streams.kstream.GlobalKTable[String,String]

assert(zipCodes.queryableStoreName == "queryable-store-name")

val topology = builder.build
scala> println(topology.describe)
Topologies:
   Sub-topology: 0 for global store (will not generate tasks)
    Source: KTABLE-SOURCE-0000000000 (topics: [zip-codes])
      --> KTABLE-SOURCE-0000000001
    Processor: KTABLE-SOURCE-0000000001 (stores: [queryable-store-name])
      --> none
      <-- KTABLE-SOURCE-0000000000
----

=== [[addGlobalStore-detailed]] Registering Global State Store (in Topology) -- `addGlobalStore` Method

[source, java]
----
StreamsBuilder addGlobalStore(
  final StoreBuilder storeBuilder,
  final String topic,
  final Consumed consumed,
  final ProcessorSupplier stateUpdateSupplier)
----

`addGlobalStore`...FIXME

=== [[addStateStore-detailed]] `addStateStore` Method

[source, java]
----
StreamsBuilder addStateStore(final StoreBuilder builder)
----

`addStateStore`...FIXME

=== [[stream]] Creating KStream (of Records from One or Many Topics) -- `stream` Method

[source, java]
----
KStream<K, V> stream(final Collection<String> topics)
KStream<K, V> stream(
  final Collection<String> topics,
  final Consumed<K, V> consumed)
KStream<K, V> stream(final Pattern topicPattern)
KStream<K, V> stream(
  final Pattern topicPattern,
  final Consumed<K, V> consumed)
KStream<K, V> stream(final String topic)
KStream<K, V> stream(
  final String topic,
  final Consumed<K, V> consumed)
----

`stream` creates a link:kafka-streams-KStream.adoc[KStream] (of keys of type `K` and values of type `V`) for the defined topic(s) and the parameters in the input link:kafka-streams-Consumed.adoc[Consumed].

[source, scala]
----
scala> :type builder
org.apache.kafka.streams.StreamsBuilder

// Create a KStream to read records from the input topic
// Keys and values of the records are of String type
val input = builder.stream[String, String]("input")

scala> :type input
org.apache.kafka.streams.kstream.KStream[String,String]
----

Internally, `stream` creates a link:kafka-streams-internals-ConsumedInternal.adoc#creating-instance[ConsumedInternal] (for the input link:kafka-streams-Consumed.adoc[Consumed]) and requests the <<internalStreamsBuilder, InternalStreamsBuilder>> to link:kafka-streams-InternalStreamsBuilder.adoc#stream[create a KStream] (for the input `topics` and the `ConsumedInternal`).

=== [[build-detailed]] Building Topology -- `build` Method

[source, java]
----
Topology build()
----

`build` simply returns the underlying <<topology, topology>>.
