== [[ProcessorContextImpl]] ProcessorContextImpl

`ProcessorContextImpl` is a concrete <<kafka-streams-AbstractProcessorContext.adoc#, AbstractProcessorContext>> that...FIXME

`ProcessorContextImpl` is <<creating-instance, created>> exclusively for a <<kafka-streams-StreamTask.adoc#processorContext, StreamTask>> (that is available as the <<task, StreamTask>>).

=== [[getStateStore]] Accessing State Store by Name -- `getStateStore` Method

[source, scala]
----
StateStore getStateStore(final String name)
----

NOTE: `getStateStore` is part of link:kafka-streams-ProcessorContext.adoc#getStateStore[ProcessorContext Contract] to access the <<kafka-streams-StateStore.adoc#, state store>> by name.

`getStateStore`...FIXME

=== [[schedule]] `schedule` Method

[source, java]
----
Cancellable schedule(final long interval, final PunctuationType type, final Punctuator callback)
----

NOTE: `schedule` is part of link:kafka-streams-ProcessorContext.adoc#schedule[ProcessorContext Contract] to...FIXME.

`schedule`...FIXME

=== [[creating-instance]] Creating ProcessorContextImpl Instance

`ProcessorContextImpl` takes the following when created:

* [[id]] <<kafka-streams-TaskId.adoc#, TaskId>>
* [[task]] <<kafka-streams-StreamTask.adoc#, StreamTask>>
* [[config]] <<kafka-streams-StreamsConfig.adoc#, StreamsConfig>>
* [[collector]] <<kafka-streams-internals-RecordCollector.adoc#, RecordCollector>>
* [[stateMgr]] <<kafka-streams-ProcessorStateManager.adoc#, ProcessorStateManager>>
* [[metrics]] <<kafka-streams-StreamsMetricsImpl.adoc#, StreamsMetricsImpl>>
* [[cache]] <<kafka-streams-ThreadCache.adoc#, ThreadCache>>

`ProcessorContextImpl` initializes the <<internal-registries, internal registries and counters>>.
