== [[Processor]] Processor Contract -- Stream Processing Nodes

`Processor` is the <<contract, contract>> for *record stream processors* (aka _stream processing nodes_) that <<process, process records>> (one at a time).

`Processor` is an integral part of link:kafka-streams-internals-ProcessorNode.adoc#processor[ProcessorNode].

[[contract]]
.Processor Contract
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| close
a| [[close]]

[source, java]
----
void close()
----

Closes the processor

| init
a| [[init]]

[source, java]
----
void init(ProcessorContext context)
----

Initializes the processor

| process
a| [[process]]

[source, java]
----
void process(K key, V value)
----

Processes a single record
|===

The lifecycle of a `Processor` starts at <<init, init>> when....FIXME

TIP: Use <<AbstractProcessor, AbstractProcessor>> when you want to develop a custom `Processor`.

[[implementations]]
.(Direct) Processors
[cols="1,2",options="header",width="100%"]
|===
| Processor
| Description

| link:kafka-streams-AbstractProcessor.adoc[AbstractProcessor]
| [[AbstractProcessor]] Abstract Processor that manages the `ProcessorContext` instance and provides default no-op implementations

| link:kafka-streams-KStreamTransformValuesProcessor.adoc[KStreamTransformValuesProcessor]
| [[KStreamTransformValuesProcessor]]
|===
