== [[ProcessorNode]] ProcessorNode

`ProcessorNode` is a <<process, processing node>> in a topology that is identified by a <<name, name>> and have zero or more <<children, child processor nodes>>.

NOTE: link:kafka-streams-SourceNode.adoc[SourceNode] and link:kafka-streams-SinkNode.adoc[SinkNode] are specialized `ProcessorNodes`.

`ProcessorNode` is <<creating-instance, created>> exclusively when `ProcessorNodeFactory` is requested to link:kafka-streams-ProcessorNodeFactory.adoc#build[build a processor node].

`ProcessorNode` can be <<init, initialized>> (in a given link:kafka-streams-ProcessorContext.adoc[ProcessorContext]) and <<close, closed>>.

`ProcessorNode` can be <<punctuate, punctuated>>.

`ProcessorNode` has a <<toString, human-friendly / textual representation>> that is particularly helpful for debugging.

[[internal-registries]]
.ProcessorNode's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `children`
| [[children]] Child `ProcessorNodes`

Used when...FIXME

| `nodeMetrics`
| [[nodeMetrics]] link:kafka-streams-NodeMetrics.adoc[NodeMetrics]

Used when...FIXME

| `time`
| [[time]] `Time`

Used when...FIXME
|===

=== [[init]] `init` Method

[source, java]
----
void init(ProcessorContext context)
----

`init`...FIXME

NOTE: `init` is used when...FIXME

=== [[process]] `process` Method

[source, java]
----
void process(final K key, final V value)
----

`process`...FIXME

NOTE: `process` is used when...FIXME

=== [[creating-instance]] Creating ProcessorNode Instance

`ProcessorNode` takes the following when created:

* [[name]] Name
* [[processor]] link:kafka-streams-Processor.adoc[Processor] (of `K` keys and `V` values)
* [[stateStores]] Names of the associated state stores

`ProcessorNode` initializes the <<internal-registries, internal registries and counters>>.

=== [[addChild]] `addChild` Method

[source, java]
----
void addChild(ProcessorNode<?, ?> child)
----

`addChild`...FIXME

NOTE: `addChild` is used when...FIXME

=== [[close]] `close` Method

[source, java]
----
void close()
----

`close`...FIXME

NOTE: `close` is used when...FIXME

=== [[toString]] Describing Itself (Textual Representation) -- `toString` Method

[source, java]
----
String toString() // <1>
String toString(String indent)
----
<1> Uses an empty `indent`

NOTE: `toString` is part of Java's link:++https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#toString--++[java.lang.Object Contract] to return a human-friendly / textual representation of an object.

`toString`...FIXME

=== [[punctuate]] Executing Punctuator (Scheduled Periodic Action) -- `punctuate` Method

[source, java]
----
void punctuate(final long timestamp, final Punctuator punctuator)
----

`punctuate` creates a Java https://docs.oracle.com/javase/8/docs/api/java/lang/Runnable.html[Runnable] that simply requests the input `Punctuator` to link:kafka-streams-Punctuator.adoc#punctuate[punctuate] with the input `timestamp`.

`punctuate` requests the <<nodeMetrics, NodeMetrics>> for the link:kafka-streams-NodeMetrics.adoc#metrics[StreamsMetricsImpl] that is requested to link:kafka-streams-StreamsMetricsImpl.adoc#measureLatencyNs[measureLatencyNs] (that records it with the link:kafka-streams-NodeMetrics.adoc#nodePunctuateTimeSensor[nodePunctuateTimeSensor] of the <<nodeMetrics, NodeMetrics>>).

NOTE: `punctuate` is used exclusively when `StreamTask` is requested to link:kafka-streams-StreamTask.adoc#punctuate[execute a scheduled periodic action].
