== [[KStream]] KStream

`KStream` is an abstraction of a *record stream* of key-value pairs (where each record is an independent entity or event in the real world).

`KStream` can be created directly from one or many Kafka topics (using link:kafka-streams-StreamsBuilder.adoc#stream[StreamsBuilder.stream] operator) or as a result of <<operators, transformations>> on an existing `KStream`.

[source, scala]
----
import org.apache.kafka.streams.StreamsBuilder
val builder = new StreamsBuilder

import org.apache.kafka.streams.kstream.KStream
// Use type annotation to describe the stream, i.e. KStream[String, String]
// Else...Scala type inferencer gives us a stream of "nothing", i.e. KStream[Nothing, Nothing]
val input: KStream[String, String] = builder.stream("input")
----

`KStream` comes with a rich set of <<operators, operators>> (aka _KStream API_) that allow for building topologies to consume, process and produce key-value records.

NOTE: link:kafka-streams-KStreamImpl.adoc[KStreamImpl] is the one and only implementation of `KStream`.

[[operators]]
.KStream Operators
[cols="1,2",options="header",width="100%"]
|===
| Operator
| Description

| [[transformValues]] `transformValues`
a| Stateful record-by-record value transformation

[source, java]
----
KStream<K, VR> transformValues(
  final ValueTransformerSupplier<? super V, ? extends VR> valueTransformerSupplier,
  final String... stateStoreNames)
KStream<K, VR> transformValues(
  final ValueTransformerWithKeySupplier<? super K, ? super V, ? extends VR> valueTransformerSupplier,
  final String... stateStoreNames)
----

`transformValues` uses link:kafka-streams-ValueTransformerSupplier.adoc[ValueTransformerSupplier] to create a link:kafka-streams-ValueTransformer.adoc[ValueTransformer] that is used for a stateful transformation of record values in a stream.

| [[mapValues]] `mapValues`
a|

[source, java]
----
<VR> KStream<K, VR> mapValues(ValueMapper<? super V, ? extends VR> mapper);
----

| [[print]] `print`
a|

[source, java]
----
void print(final Printed<K, V> printed);
----

| [[through]] `through`
a|

[source, java]
----
KStream<K, V> through(final String topic);
KStream<K, V> through(final String topic, final Produced<K, V> produced);
----

| [[transform]] `transform`
a| Stateful record transformation

[source, java]
----
KStream<K1, V1> transform(
  final TransformerSupplier<? super K, ? super V, KeyValue<K1, V1>> transformerSupplier,
  final String... stateStoreNames)
----

| [[to]] `to`
a|

[source, java]
----
void to(final String topic);
void to(final String topic, final Produced<K, V> produced);
----

NOTE: The specified `topic` should be manually created before the Kafka Streams application is started.

|===
