== [[TimeWindowedKStreamImpl]] TimeWindowedKStreamImpl

`TimeWindowedKStreamImpl` is a <<kafka-streams-AbstractStream.adoc#, stream>> that allows for <<kafka-streams-TimeWindowedKStream.adoc#, time-windowed streaming aggregations>>.

`TimeWindowedKStreamImpl` is <<creating-instance, created>> exclusively when `KGroupedStreamImpl` is requested to <<kafka-streams-internals-KGroupedStreamImpl.adoc#windowedBy, windowedBy>>.

`TimeWindowedKStreamImpl` uses a <<aggregateBuilder, GroupedStreamAggregateBuilder>> for...FIXME

=== [[materialize]] Creating StoreBuilder (of WindowStores) -- `materialize` Internal Method

[source, java]
----
StoreBuilder<WindowStore<K, VR>> materialize(
  final MaterializedInternal<K, VR, WindowStore<Bytes, byte[]>> materialized)
----

`materialize`...FIXME

NOTE: `materialize` is used when `TimeWindowedKStreamImpl` is requested to <<doCount, doCount>>, <<aggregate, aggregate>> and <<reduce, reduce>>.

=== [[aggregate]] `aggregate` Method

[source, java]
----
KTable<Windowed<K>, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator)
KTable<Windowed<K>, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator,
  final Materialized<K, VR, WindowStore<Bytes, byte[]>> materialized)
----

NOTE: `aggregate` is part of the <<kafka-streams-TimeWindowedKStream.adoc#aggregate, TimeWindowedKStream Contract>> to...FIXME.

`aggregate`...FIXME

=== [[reduce]] `reduce` Method

[source, java]
----
KTable<Windowed<K>, V> reduce(final Reducer<V> reducer) // <1>
KTable<Windowed<K>, V> reduce(
  final Reducer<V> reducer,
  final Materialized<K, V, WindowStore<Bytes, byte[]>> materialized)
----
<1> Uses <<kafka-streams-Materialized.adoc#, Materialized>> with the serdes for <<keySerde, keys>> and <<valSerde, values>>

NOTE: `reduce` is part of the <<kafka-streams-TimeWindowedKStream.adoc#reduce, TimeWindowedKStream Contract>> to combine record stream (by a grouped key).

`reduce` creates a <<kafka-streams-internals-MaterializedInternal.adoc#, MaterializedInternal>> for the given <<kafka-streams-Materialized.adoc#, Materialized>> and requests it to <<kafka-streams-internals-MaterializedInternal.adoc#generateStoreNameIfNeeded, generateStoreNameIfNeeded>> (with `KSTREAM-REDUCE-` store prefix).

In the end, `reduce` requests the <<aggregateBuilder, GroupedStreamAggregateBuilder>> to <<kafka-streams-internals-GroupedStreamAggregateBuilder.adoc#build, build>> (with `KSTREAM-REDUCE-` store prefix and a new `KStreamWindowReduce`).

=== [[count]] `count` Method

[source, java]
----
KTable<Windowed<K>, Long> count()
KTable<Windowed<K>, Long> count(final Materialized<K, Long, WindowStore<Bytes, byte[]>> materialized)
----

NOTE: `count` is part of the <<kafka-streams-TimeWindowedKStream.adoc#count, TimeWindowedKStream Contract>> to...FIXME.

`count`...FIXME

=== [[doCount]] `doCount` Internal Method

[source, java]
----
KTable<Windowed<K>, Long> doCount(final Materialized<K, Long, WindowStore<Bytes, byte[]>> materialized)
----

`doCount`...FIXME

NOTE: `doCount` is used exclusively when `TimeWindowedKStreamImpl` is requested to <<count, count>>.

=== [[creating-instance]] Creating TimeWindowedKStreamImpl Instance

`TimeWindowedKStreamImpl` takes the following when created:

* [[windows]] <<kafka-streams-Windows.adoc#, Windows>>
* [[builder]] <<kafka-streams-InternalStreamsBuilder.adoc#, InternalStreamsBuilder>>
* [[sourceNodes]] Names of the source topics
* [[name]] Name
* [[keySerde]] `Serde<K>` for keys
* [[valSerde]] `Serde<V>` for values
* [[aggregateBuilder]] <<kafka-streams-internals-GroupedStreamAggregateBuilder.adoc#, GroupedStreamAggregateBuilder>>
* [[streamsGraphNode]] <<kafka-streams-internals-StreamsGraphNode.adoc#, StreamsGraphNode>>

`TimeWindowedKStreamImpl` initializes the <<internal-registries, internal registries and counters>>.
