== [[StatefulProcessorNode]] StatefulProcessorNode

`StatefulProcessorNode` is a <<kafka-streams-internals-StreamsGraphNode.adoc#, graph node>> for stateful operators in <<kafka-streams-internals-KGroupedStreamImpl.adoc#, KGroupedStreamImpl>>, <<kafka-streams-internals-KGroupedTableImpl.adoc#, KGroupedTableImpl>>, <<kafka-streams-internals-KStreamImpl.adoc#, KStreamImpl>>, and <<kafka-streams-internals-KTableImpl.adoc#, KTableImpl>>.

[[storeBuilder]]
`StatefulProcessorNode` extends the parent <<kafka-streams-internals-ProcessorGraphNode.adoc#, ProcessorGraphNode>> with the two state-related parameters, i.e. <<storeNames, state store names>> and <<materializedKTableStoreBuilder, StoreBuilder>>.

When requested to <<writeToTopology, writeToTopology>>, `StatefulProcessorNode` simply requests the given <<kafka-streams-internals-InternalTopologyBuilder.adoc#, InternalTopologyBuilder>> to <<kafka-streams-internals-InternalTopologyBuilder.adoc#addProcessor, add a processor>> (as a <<kafka-streams-internals-ProcessorGraphNode.adoc#, ProcessorGraphNode>>) and to associate the state stores (by the <<storeNames, names>> or the <<materializedKTableStoreBuilder, StoreBuilder>>).

`StatefulProcessorNode` is <<creating-instance, created>> when:

* `GroupedStreamAggregateBuilder` is requested to <<kafka-streams-internals-GroupedStreamAggregateBuilder.adoc#build, build>> (for <<kafka-streams-internals-KStreamImpl.adoc#groupBy, KStream.groupBy>> and <<kafka-streams-internals-KStreamImpl.adoc#groupByKey, KStream.groupByKey>> streaming operators, incl. `windowedBy` operator with a <<kafka-streams-internals-KGroupedStreamImpl.adoc#windowedBy-Windows, Windows>> or a <<kafka-streams-internals-KGroupedStreamImpl.adoc#windowedBy-SessionWindows, SessionWindows>>)

* `KGroupedTableImpl` is requested to <<kafka-streams-internals-KGroupedTableImpl.adoc#doAggregate, doAggregate>> (for <<kafka-streams-internals-KGroupedTableImpl.adoc#reduce, reduce>>, <<kafka-streams-internals-KGroupedTableImpl.adoc#count, count>> and <<kafka-streams-internals-KGroupedTableImpl.adoc#aggregate, aggregate>> operators)

* `KStreamImpl` is requested to <<kafka-streams-internals-KStreamImpl.adoc#transform, transform>>, <<kafka-streams-internals-KStreamImpl.adoc#doTransformValues, doTransformValues>> (for <<transformValues, transformValues>> operator), and <<kafka-streams-internals-KStreamImpl.adoc#process, process>>

* `KTableImpl` is requested to <<kafka-streams-internals-KTableImpl.adoc#suppress, suppress>>

[[creating-instance]]
`StatefulProcessorNode` takes the following to be created:

* [[nodeName]] Node name
* [[processorParameters]] `ProcessorParameters<K, V>`
* [[materializedKTableStoreBuilder]][[storeNames]] Names of the state stores or a <<kafka-streams-StoreBuilder.adoc#, StoreBuilder>>
* [[repartitionRequired]] `repartitionRequired` flag

=== [[writeToTopology]] `writeToTopology` Method

[source, java]
----
void writeToTopology(final InternalTopologyBuilder topologyBuilder)
----

NOTE: `writeToTopology` is part of the <<kafka-streams-internals-StreamsGraphNode.adoc#writeToTopology, StreamsGraphNode Contract>> to...FIXME.

`writeToTopology` requests the given `InternalTopologyBuilder` to <<kafka-streams-internals-InternalTopologyBuilder.adoc#addProcessor, add a processor>> with the name and the <<kafka-streams-ProcessorSupplier.adoc#, ProcessorSupplier>> as defined by the <<processorParameters, ProcessorParameters>>.

With <<storeNames, state store name>> given, `writeToTopology` requests the given `InternalTopologyBuilder` to <<kafka-streams-internals-InternalTopologyBuilder.adoc#connectProcessorAndStateStores, connect them with the processor>>.

With a <<storeBuilder, StoreBuilder>> given, `writeToTopology` requests the given `InternalTopologyBuilder` to <<kafka-streams-internals-InternalTopologyBuilder.adoc#addStateStore, addStateStore>> with the `StoreBuilder` and the processor.
