== [[StateStoreFactory]] StateStoreFactory Internal Contract

`StateStoreFactory` is the internal <<contract, contract>> (of <<kafka-streams-InternalTopologyBuilder.adoc#, InternalTopologyBuilder>>) for <<implementations, factories>> that can <<build, build state stores>>.

[[implementations]]
NOTE: <<kafka-streams-AbstractStateStoreFactory.adoc#, AbstractStateStoreFactory>> is the one and only known direct extension contract of the <<contract, StateStoreFactory Contract>>.

[[contract]]
.StateStoreFactory Contract
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| build
a| [[build]]

[source, java]
----
StateStore build()
----

Builds a <<kafka-streams-StateStore.adoc#, state store>>

| isWindowStore
a| [[isWindowStore]]

[source, java]
----
boolean isWindowStore()
----

Indicates whether a `StateStoreFactory` was created for a link:kafka-streams-internals-WindowStoreBuilder.adoc[WindowStoreBuilder] (`true`) or not (`false`)

Used exclusively when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#createChangelogTopicConfig[create an InternalTopicConfig (for a given name and StateStoreFactory)]

`isWindowStore` is implemented by link:kafka-streams-AbstractStateStoreFactory.adoc#isWindowStore[AbstractStateStoreFactory] only and corresponds to link:kafka-streams-AbstractStateStoreFactory.adoc#windowStore[windowStore] flag that is given when link:kafka-streams-AbstractStateStoreFactory.adoc#implementations[concrete StateStoreFactories] are created.

In a nutshell, The flag is enabled only when the `StateStoreFactory` is created for a link:kafka-streams-internals-WindowStoreBuilder.adoc[WindowStoreBuilder].

| logConfig
a| [[logConfig]]

[source, java]
----
Map<String, String> logConfig()
----

Used exclusively when `InternalTopologyBuilder` is requested to <<kafka-streams-InternalTopologyBuilder.adoc#createChangelogTopicConfig, createChangelogTopicConfig>>

| loggingEnabled
a| [[loggingEnabled]]

[source, java]
----
boolean loggingEnabled()
----

Indicates whether <<kafka-streams-AbstractStateStoreFactory.adoc#loggingEnabled, change-logging>> is enabled (`true`) or not (`false`)

Used when `InternalTopologyBuilder` is requested to <<kafka-streams-InternalTopologyBuilder.adoc#buildProcessorNode, buildProcessorNode>> and for <<kafka-streams-InternalTopologyBuilder.adoc#topicGroups, topic groups>>

| name
a| [[name]]

[source, java]
----
String name()
----

| retentionPeriod
a| [[retentionPeriod]]

[source, java]
----
long retentionPeriod()
----

Window retention period (in milliseconds)

Used exclusively when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#createChangelogTopicConfig[create an InternalTopicConfig (for a given name and StateStoreFactory)]

| users
a| [[users]]

[source, java]
----
Set<String> users()
----

Names of the processors that are connected to a state store

Used when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#connectProcessorAndStateStore[connect a state store with a processor node] and link:kafka-streams-InternalTopologyBuilder.adoc#topicGroups[topic groups]

|===
