== [[InternalNameProvider]] InternalNameProvider Contract

`InternalNameProvider` is the <<contract, abstraction>> of <<implementations, internal name providers>> that give a new name for a <<newProcessorName, processor>> or a <<newStoreName, store>>.

[[contract]]
.InternalNameProvider Contract
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| newProcessorName
a| [[newProcessorName]]

[source, java]
----
String newProcessorName(String prefix)
----

Returns a name of a processor with the given prefix

Used when:

* `GroupedStreamAggregateBuilder` is requested to <<kafka-streams-internals-GroupedStreamAggregateBuilder.adoc#build, build>>

* `InternalStreamsBuilder` is requested to <<kafka-streams-internals-InternalStreamsBuilder.adoc#stream, stream>>, <<kafka-streams-internals-InternalStreamsBuilder.adoc#table, table>>, <<kafka-streams-internals-InternalStreamsBuilder.adoc#globalTable, globalTable>> and <<kafka-streams-internals-InternalStreamsBuilder.adoc#addGlobalStore, addGlobalStore>>

* `KGroupedTableImpl` is requested to <<kafka-streams-internals-KGroupedTableImpl.adoc#doAggregate, doAggregate>>

* `KStreamImpl` is requested to <<kafka-streams-internals-KStreamImpl.adoc#filter, filter>>, etc.

* `KStreamImplJoin` is requested to <<kafka-streams-internals-KStreamImplJoin.adoc#join, join>>

* `KTableImpl` is requested to <<kafka-streams-internals-KTableImpl.adoc#doFilter, doFilter>>, etc.

| newStoreName
a| [[newStoreName]]

[source, java]
----
String newStoreName(String prefix)
----

Returns a name of a state store with the given prefix

Used when:

* <<kafka-streams-internals-KGroupedStreamImpl.adoc#count, KGroupedStreamImpl>>, <<kafka-streams-internals-SessionWindowedKStreamImpl.adoc#count, SessionWindowedKStreamImpl>>, and <<kafka-streams-internals-TimeWindowedKStreamImpl.adoc#count, TimeWindowedKStreamImpl>> are requested to count

* `KTableImpl` is requested to <<kafka-streams-internals-KTableImpl.adoc#suppress, suppress>>

* `MaterializedInternal` is requested to <<kafka-streams-internals-MaterializedInternal.adoc#generateStoreNameIfNeeded, generateStoreNameIfNeeded>>

|===

[[implementations]]
NOTE: <<kafka-streams-internals-InternalStreamsBuilder.adoc#, InternalStreamsBuilder>> is the one and only known implementation of <<contract, InternalNameProvider Contract>> in Kafka Streams.
