== Configuration Properties

.Configuration Properties
[cols="1m,1,2",options="header",width="100%"]
|===
| Name
| Default Value
| Description

| application.id
| (empty)
| [[application.id]] Required *application ID*, i.e. the identifier of a Kafka Streams application.

It must be unique within the Kafka cluster as it is used as a namespace for the default client-id prefix, the group-id for membership management, and the internal topic prefix.

Use <<kafka-streams-StreamsConfig.adoc#APPLICATION_ID_CONFIG, StreamsConfig.APPLICATION_ID_CONFIG>> to reference the property.

| application.server
| (empty)
| [[application.server]] A `host:port` pair pointing to an embedded user-defined endpoint (that can be used for discovering the locations of state stores in a single KafkaStreams application).

Used when `StreamPartitionAssignor` is requested to link:kafka-streams-StreamsPartitionAssignor.adoc#configure[configure itself].

Use <<kafka-streams-StreamsConfig.adoc#APPLICATION_SERVER_CONFIG, StreamsConfig.APPLICATION_SERVER_CONFIG>> to reference the property.

| commit.interval.ms
a|
* `100L` when <<processing.guarantee, processing.guarantee>> is <<exactly_once, exactly_once>> (which is not by default)
* `30000L` otherwise
a| [[commit.interval.ms]] *Flush interval* or *commit interval* (in millis), i.e. how often `StreamThread` <<kafka-streams-StreamThread.adoc#maybeCommit, tries to commit>> the position of processors and _flush_ state stores

Use <<kafka-streams-StreamsConfig.adoc#COMMIT_INTERVAL_MS_CONFIG, StreamsConfig.COMMIT_INTERVAL_MS_CONFIG>> to reference the property.

If the commit interval is negative, `StreamThread` will never <<kafka-streams-StreamThread.adoc#maybeCommit, commit tasks>>.

| default.timestamp.extractor
| <<kafka-streams-FailOnInvalidTimestamp.adoc#, FailOnInvalidTimestamp>>
| [[default.timestamp.extractor]] Default timestamp extractor class that implements the <<kafka-streams-TimestampExtractor.adoc#, org.apache.kafka.streams.processor.TimestampExtractor>> interface.

| metrics.recording.level
| `INFO`
a| [[metrics.recording.level]] The highest recording level for <<kafka-streams-StreamsMetrics.adoc#, metrics>>

Possible values are:

* [[metrics.recording.level-INFO]] `INFO` (default)
* [[metrics.recording.level-DEBUG]] `DEBUG`

Use <<kafka-streams-StreamsConfig.adoc#METRICS_RECORDING_LEVEL_CONFIG, StreamsConfig.METRICS_RECORDING_LEVEL_CONFIG>> to reference the property.

| num.stream.threads
| `1`
| [[num.stream.threads]] The number of <<kafka-streams-StreamThread.adoc#, stream processor threads>> (that <<kafka-streams-KafkaStreams.adoc#threads, KafkaStreams>> uses for stream processing).

| poll.ms
| `100`
a| [[poll.ms]] *Polling interval* (in milliseconds), i.e. the time spent waiting in `Consumer.poll` (unless data is available in the buffer). If `0`, returns immediately with any records that are available currently in the buffer, else returns empty. Must not be negative.

* Used when `GlobalStreamThread` is requested to link:kafka-streams-GlobalStreamThread.adoc#initialize[initialize] (which is right after `KafkaStreams` has been link:kafka-streams-KafkaStreams.adoc#start[started]) and creates a link:kafka-streams-StateConsumer.adoc#pollMs[StateConsumer]

* Used when `StreamThread` is link:kafka-streams-StreamThread.adoc#pollTimeMs[created]

Use <<kafka-streams-StreamsConfig.adoc#POLL_MS_CONFIG, StreamsConfig.POLL_MS_CONFIG>> to reference the property.

| processing.guarantee
| `at_least_once`
a| [[processing.guarantee]] *Processing guarantee* (aka _Exactly-Once Support_ or _EOS support_)

Possible values are:

* [[at_least_once]] *at_least_once* (default)
* [[exactly_once]] *exactly_once*

[NOTE]
====
<<exactly_once, exactly-once>> processing guarantee requires a Kafka cluster with at least three brokers (which is the recommended setting for production).

For development you can change this by adjusting broker setting `transaction.state.log.replication.factor`.
====

Use <<kafka-streams-StreamsConfig.adoc#PROCESSING_GUARANTEE_CONFIG, StreamsConfig.PROCESSING_GUARANTEE_CONFIG>> to reference the property.

| state.cleanup.delay.ms
| `10` mins (`10 * 60 * 1000`)
| [[state.cleanup.delay.ms]] The amount of time (in milliseconds) to wait before deleting state when a partition has migrated. Only state directories that have not been modified for at least `state.cleanup.delay.ms` will be removed.

| state.dir
| `/tmp/kafka-streams`
a| [[state.dir]] Path to the base directory for a state storage

* Used when `StateDirectory` is link:kafka-streams-StateDirectory.adoc#creating-instance[created]

Use <<kafka-streams-StreamsConfig.adoc#STATE_DIR_CONFIG, StreamsConfig.STATE_DIR_CONFIG>> to reference the property.

|===
