== [[StreamsBuilder]] StreamsBuilder

`StreamsBuilder` is the *high-level stream processing DSL* in Kafka Streams to <<build, build a topology>>.

[source, scala]
----
import org.apache.kafka.streams.StreamsBuilder
val builder = new StreamsBuilder
----

[[topology]]
When created, `StreamsBuilder` creates a link:kafka-streams-Topology.adoc#creating-instance[Topology].

NOTE: Technically, `StreamsBuilder` is simply a wrapper around link:kafka-streams-Topology.adoc[Topology] and whatever topology you could build using `StreamsBuilder` so could you with `Topology` directly.

[[internalStreamsBuilder]]
`StreamsBuilder` uses link:kafka-streams-InternalStreamsBuilder.adoc[InternalStreamsBuilder] for...FIXME

=== [[table]] `table` Method

[source, java]
----
KTable<K, V> table(final String topic)
KTable<K, V> table(final String topic, final Consumed<K, V> consumed)
KTable<K, V> table(
  final String topic,
  final Consumed<K, V> consumed,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
KTable<K, V> table(
  final String topic,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
----

`table`...FIXME

=== [[addGlobalStore]] `addGlobalStore` Method

[source, java]
----
synchronized StreamsBuilder addGlobalStore(
  final StoreBuilder storeBuilder,
  final String topic,
  final Consumed consumed,
  final ProcessorSupplier stateUpdateSupplier)
----

`addGlobalStore`...FIXME

=== [[stream]] Creating KStream of Records for Topics -- `stream` Factory Method

[source, java]
----
synchronized <K, V> KStream<K, V> stream(final String topic)  // <1>
synchronized <K, V> KStream<K, V> stream(final Pattern topicPattern) // <2>
synchronized <K, V> KStream<K, V> stream(final Collection<String> topics) // <3>
// All three above have their Consumed-based variant
synchronized <K, V> KStream<K, V> stream(
  final String topic,
  final Consumed<K, V> consumed)
synchronized <K, V> KStream<K, V> stream(
  final Pattern topicPattern,
  final Consumed<K, V> consumed)
synchronized <K, V> KStream<K, V> stream(
  final Collection<String> topics,
  final Consumed<K, V> consumed)
----
<1> Calls `stream(final Collection<String> topics)`
<2> Calls `stream(final Pattern topicPattern, final Consumed<K, V> consumed)` with `Consumed` with all fields `null`
<3> Calls `stream(final Collection<String> topics, final Consumed<K, V> consumed)` with `Consumed` with all fields `null`

`stream` creates a link:kafka-streams-KStream.adoc[KStream] (of keys of type `K` and values of type `V`) for the defined topic(s) and the parameters in the input link:kafka-streams-Consumed.adoc[Consumed].

[source, scala]
----
scala> :type builder
org.apache.kafka.streams.StreamsBuilder

val input = builder.stream[String, String]("input")

scala> :type input
org.apache.kafka.streams.kstream.KStream[String,String]
----

Internally, `stream` creates a link:kafka-streams-ConsumedInternal.adoc#creating-instance[ConsumedInternal] (for the input link:kafka-streams-Consumed.adoc[Consumed]).

`stream` then requests <<internalStreamsBuilder, InternalStreamsBuilder>> to link:kafka-streams-InternalStreamsBuilder.adoc#stream[create a KStream] for the input `topics` and the `ConsumedInternal`.
