== [[AbstractTaskCreator]] AbstractTaskCreator

`AbstractTaskCreator` is the <<contract, contract>> to <<createTask, create processor tasks>>.

[[contract]]
[source, java]
----
package org.apache.kafka.streams.processor.internals;

abstract class StreamThread.AbstractTaskCreator<T extends Task> {
  // only required method that has no implementation
  T createTask(final Consumer<byte[], byte[]> consumer, final TaskId id, final Set<TopicPartition> partitions);
}
----

.AbstractTaskCreator Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| `createTask`
| [[createTask]] Creates a <<kafka-streams-Task.adoc#, Task>>

Used exclusively when `AbstractTaskCreator` is requested to <<createTasks, create tasks>> (when `TaskManager` is requested for link:kafka-streams-TaskManager.adoc#addStandbyTasks[standby] or link:kafka-streams-TaskManager.adoc#addStreamTasks[stream] tasks)
|===

NOTE: `AbstractTaskCreator` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly when the <<implementations, concrete AbstractTaskCreators>> are.

[[implementations]]
.AbstractTaskCreators
[cols="1,2",options="header",width="100%"]
|===
| AbstractTaskCreator
| Description

| link:kafka-streams-StandbyTaskCreator.adoc[StandbyTaskCreator]
| Creates link:kafka-streams-StandbyTask.adoc[standby tasks]

| link:kafka-streams-TaskCreator.adoc[TaskCreator]
| Creates link:kafka-streams-StreamTask.adoc[stream tasks]
|===

=== [[createTasks]] Creating Processor Tasks -- `createTasks` Method

[source, java]
----
Collection<T> createTasks(
  final Consumer<byte[], byte[]> consumer,
  final Map<TaskId, Set<TopicPartition>> tasksToBeCreated)
----

`createTasks`...FIXME

NOTE: `createTasks` is used when `TaskManager` is requested for <<kafka-streams-TaskManager.adoc#addStandbyTasks, standby>> or <<kafka-streams-TaskManager.adoc#addStreamTasks, stream>> tasks.

=== [[creating-instance]] Creating AbstractTaskCreator Instance

`AbstractTaskCreator` takes the following when created:

* [[builder]] link:kafka-streams-InternalTopologyBuilder.adoc[InternalTopologyBuilder]
* [[config]] link:kafka-streams-StreamsConfig.adoc[StreamsConfig]
* [[streamsMetrics]] link:kafka-streams-StreamsMetrics.adoc[StreamsMetrics]
* [[stateDirectory]] link:kafka-streams-internals-StateDirectory.adoc[StateDirectory]
* [[taskCreatedSensor]] Kafka `Sensor` (to monitor task created)
* [[storeChangelogReader]] <<kafka-streams-ChangelogReader.adoc#, ChangelogReader>>
* [[time]] `Time`
* [[log]] `Logger`
