== [[KGroupedStream]] KGroupedStream -- Basic Stream Aggregations

`KGroupedStream` is the <<contract, abstraction>> of a <<implementations, grouped record stream>> that allows Kafka Streams developers for <<aggregate, aggregate>>, <<count, count>>, <<reduce, reduce>> and <<windowedBy, windowedBy>> stream aggregations.

`KGroupedStream` is the result of the following aggregate stream operators:

* <<kafka-streams-KStream.adoc#groupBy, KStream.groupBy>>
* <<kafka-streams-KStream.adoc#groupByKey, KStream.groupByKey>>

TIP: Use <<kafka-streams-scala.adoc#, Scala API for Kafka Streams>> to make your Kafka Streams development more pleasant if Scala is your programming language.

[source, scala]
----
import org.apache.kafka.streams.scala.StreamsBuilder
import org.apache.kafka.streams.scala._
import ImplicitConversions._
import Serdes._
val builder = new StreamsBuilder
val groupedKStream = builder
  .stream[String, String]("events")
  .groupByKey
scala> :type groupedKStream
org.apache.kafka.streams.scala.kstream.KGroupedStream[String,String]
----

[[contract]]
.KGroupedStream API / Aggregation Operators
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| aggregate
a| [[aggregate]]

[source, java]
----
KTable<K, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator)
KTable<K, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator,
  final Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

Creates a <<kafka-streams-KTable.adoc#, KTable>> with a given `Initializer`, `Aggregator` and <<kafka-streams-Materialized.adoc#, Materialized>> (view of a <<kafka-streams-StateStore-KeyValueStore.adoc#, KeyValueStore>>)

| count
a| [[count]]

[source, java]
----
KTable<K, Long> count()
KTable<K, Long> count(
  final Materialized<K, Long, KeyValueStore<Bytes, byte[]>> materialized)
----

Creates a <<kafka-streams-KTable.adoc#, KTable>> with a given <<kafka-streams-Materialized.adoc#, Materialized>> (view of a <<kafka-streams-StateStore-KeyValueStore.adoc#, KeyValueStore>>)

| reduce
a| [[reduce]]

[source, java]
----
KTable<K, V> reduce(final Reducer<V> reducer)
KTable<K, V> reduce(
  final Reducer<V> reducer,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
----

Creates a <<kafka-streams-KTable.adoc#, KTable>> with a given `Reducer` and <<kafka-streams-Materialized.adoc#, Materialized>> (view of a <<kafka-streams-StateStore-KeyValueStore.adoc#, KeyValueStore>>)

| windowedBy
a| [[windowedBy]][[windowedBy-SessionWindowedKStream]]

[source, java]
----
SessionWindowedKStream<K, V> windowedBy(final SessionWindows windows)
----

Creates a <<kafka-streams-SessionWindowedKStream.adoc#, SessionWindowedKStream>> with a given `SessionWindows` window specification

| windowedBy
a| [[windowedBy-TimeWindowedKStream]]

[source, java]
----
<W extends Window> TimeWindowedKStream<K, V> windowedBy(final Windows<W> windows)
----

Creates a <<kafka-streams-TimeWindowedKStream.adoc#, TimeWindowedKStream>> with a given <<kafka-streams-Windows.adoc#, Windows>> window specification
|===

[[implementations]]
NOTE: <<kafka-streams-internals-KGroupedStreamImpl.adoc#, KGroupedStreamImpl>> is the one and only known implementation of the <<contract, KGroupedStream Contract>> in Kafka Streams {{ book.kafka_version }}.
