== [[SinkNodeFactory]] SinkNodeFactory

`SinkNodeFactory` is a custom <<kafka-streams-internals-InternalTopologyBuilder-NodeFactory.adoc#, NodeFactory>> that can <<build, build>> and <<describe, describe>> a <<kafka-streams-internals-SinkNode.adoc#, SinkNode>>.

`SinkNodeFactory` is <<creating-instance, created>> exclusively when `InternalTopologyBuilder` is requested to <<kafka-streams-internals-InternalTopologyBuilder.adoc#addSink, register a sink>>.

=== [[build]] Building SinkNode -- `build` Method

[source, java]
----
ProcessorNode build()
----

NOTE: `build` is part of link:kafka-streams-internals-InternalTopologyBuilder-NodeFactory.adoc#build[NodeFactory Contract] to build a <<kafka-streams-internals-ProcessorNode.adoc#, processor node>>.

`build` simply creates a link:kafka-streams-internals-SinkNode.adoc#creating-instance[SinkNode] (with the link:kafka-streams-internals-InternalTopologyBuilder-NodeFactory.adoc#name[name], the <<keySerializer, key serializer>>, the <<valSerializer, value serializer>> and the <<partitioner, StreamPartitioner>>).

NOTE: The link:kafka-streams-internals-SinkNode.adoc#name[name of the topic] of the `SinkNode` is the <<topic, topic>> with link:kafka-streams-internals-InternalTopologyBuilder.adoc#decorateTopic[application id] for an link:kafka-streams-internals-InternalTopologyBuilder.adoc#internalTopicNames[internal topic].

=== [[creating-instance]] Creating SinkNodeFactory Instance

`SinkNodeFactory` takes the following when created:

* [[name]] Node name
* [[predecessors]] Names of the predecessors
* [[topic]] Topic name
* [[keySerializer]] Key `Serializer`
* [[valSerializer]] Value `Serializer`
* [[partitioner]] link:kafka-streams-StreamPartitioner.adoc[StreamPartitioner]

=== [[describe]] Describing SinkNode -- `describe` Method

[source, java]
----
Sink describe()
----

NOTE: `describe` is part of link:kafka-streams-internals-InternalTopologyBuilder-NodeFactory.adoc#describe[NodeFactory Contract] to describe a <<kafka-streams-internals-ProcessorNode.adoc#, processor node>>.

`describe`...FIXME
