== [[AbstractStateManager]] AbstractStateManager

`AbstractStateManager` is an extension to the link:kafka-streams-StateManager.adoc#contract[StateManager Contract] for <<implementations, StateManagers>> that use an <<checkpoint, OffsetCheckpoint>> for...FIXME

[[creating-instance]]
[[baseDir]]
`AbstractStateManager` only takes the base directory for the <<checkpoint, checkpoint>> offset file when created.

NOTE: `AbstractStateManager` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly when the <<implementations, concrete AbstractStateManagers>> are.

[[CHECKPOINT_FILE_NAME]]
`AbstractStateManager` uses `.checkpoint` for the name of the <<checkpoint, checkpoint>> offset file.

[[internal-registries]]
.AbstractStateManager's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| checkpoint
| [[checkpoint]] <<kafka-streams-OffsetCheckpoint.adoc#, OffsetCheckpoint>> with the <<CHECKPOINT_FILE_NAME, offset checkpoint file>> in the <<baseDir, base directory>>.

Used when...FIXME

| checkpointableOffsets
| [[checkpointableOffsets]]

| stores
| [[stores]] <<kafka-streams-StateStore.adoc#, State stores>> by their names

| globalStores
| [[globalStores]]
|===

[[implementations]]
.AbstractStateManagers
[cols="1,2",options="header",width="100%"]
|===
| AbstractStateManager
| Description

| link:kafka-streams-GlobalStateManagerImpl.adoc[GlobalStateManagerImpl]
| [[GlobalStateManagerImpl]]

| link:kafka-streams-ProcessorStateManager.adoc[ProcessorStateManager]
| [[ProcessorStateManager]]
|===

=== [[reinitializeStateStoresForPartitions]] `reinitializeStateStoresForPartitions` Method

[source, java]
----
void reinitializeStateStoresForPartitions(
  final Logger log,
  final Map<String, StateStore> stateStores,
  final Map<String, String> storeToChangelogTopic,
  final Collection<TopicPartition> partitions,
  final InternalProcessorContext processorContext)
----

`reinitializeStateStoresForPartitions`...FIXME

[NOTE]
====
`reinitializeStateStoresForPartitions` is used when:

* `GlobalStateManagerImpl` is requested to <<kafka-streams-GlobalStateManagerImpl.adoc#reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>

* `ProcessorStateManager` is requested to <<kafka-streams-ProcessorStateManager.adoc#reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>
====

=== [[inverseOneToOneMap]] `inverseOneToOneMap` Internal Method

[source, java]
----
Map<String, String> inverseOneToOneMap(final Map<String, String> origin)
----

`inverseOneToOneMap`...FIXME

NOTE: `inverseOneToOneMap` is used exclusively when `AbstractStateManager` is requested to <<reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>.
