== [[Processor]] Processor -- Contract for Stream Processors

`Processor` is the <<contract, contract>> in Kafka Streams for *stream processors* that <<process, process key-value pair records>>.

`Processor` is an integral part of link:kafka-streams-ProcessorNode.adoc#processor[ProcessorNode].

[[contract]]
[source, java]
----
package org.apache.kafka.streams.processor;

interface Processor<K, V> {
  void close();
  void init(ProcessorContext context);
  void process(K key, V value);
}
----

NOTE: `Processor` is an `Evolving` contract which means that compatibility may be broken at a minor release.

.Processor Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| `close`
| [[close]]

| `init`
| [[init]] Initializing a stream processor

| `process`
| [[process]] Processing a single record

| `punctuate`
| [[punctuate]] *DEPRECATED*
|===

The lifecycle of a `Processor` starts at <<init, init>> when....FIXME

TIP: Use <<AbstractProcessor, AbstractProcessor>> when you want to develop a custom `Processor`.

[[implementations]]
.(Direct) Processors
[cols="1,2",options="header",width="100%"]
|===
| Processor
| Description

| link:kafka-streams-AbstractProcessor.adoc[AbstractProcessor]
| [[AbstractProcessor]] Abstract Processor that manages the `ProcessorContext` instance and provides default no-op implementations

| link:kafka-streams-KStreamTransformValuesProcessor.adoc[KStreamTransformValuesProcessor]
| [[KStreamTransformValuesProcessor]]
|===
