== [[KStream]] KStream

`KStream` is the <<contract, abstraction>> of a *record stream* (of key-value pairs).

`KStream` can be created directly from one or many Kafka topics (using link:kafka-streams-StreamsBuilder.adoc#stream[StreamsBuilder.stream] operator) or as a result of <<operators, transformations>> on an existing `KStream`.

TIP: Use <<kafka-streams-scala.adoc#, Scala API for Kafka Streams>> to make your Kafka Streams development more pleasant if Scala is your programming language.

[source, scala]
----
import org.apache.kafka.streams.scala.StreamsBuilder
val builder = new StreamsBuilder

import org.apache.kafka.streams.kstream.KStream
// Use type annotation to describe the stream, i.e. KStream[String, String]
// Else...Scala type inferencer gives us a stream of "nothing", i.e. KStream[Nothing, Nothing]
val input: KStream[String, String] = builder.stream("input")
----

`KStream` comes with a rich set of <<operators, operators>> (aka _KStream API_) that allow for building topologies to consume, process and produce key-value records.

[[contract]]
[[operators]]
.KStream API / Stream Operators
[cols="1m,2",options="header",width="100%"]
|===
| Operator
| Description

| branch
a| [[branch]]

[source, java]
----
KStream<K, V>[] branch(final Predicate<? super K, ? super V>... predicates)
----

| filter
a| [[filter]]

[source, java]
----
KStream<K, V> filter(Predicate<? super K, ? super V> predicate)
----

| filterNot
a| [[filterNot]]

[source, java]
----
KStream<K, V> filterNot(Predicate<? super K, ? super V> predicate)
----

| flatMap
a| [[flatMap]]

[source, java]
----
KStream<KR, VR> flatMap(
  KeyValueMapper<
    ? super K,
    ? super V,
    ? extends Iterable<? extends KeyValue<? extends KR, ? extends VR>>> mapper)
----

| flatMapValues
a| [[flatMapValues]]

[source, java]
----
KStream<K, VR> flatMapValues(
  final ValueMapper<? super V, ? extends Iterable<? extends VR>> mapper)
KStream<K, VR> flatMapValues(
  final ValueMapperWithKey<? super K, ? super V, ? extends Iterable<? extends VR>> mapper)
----

| foreach
a| [[foreach]]

[source, java]
----
void foreach(final ForeachAction<? super K, ? super V> action)
----

| groupBy
a| [[groupBy]]

[source, java]
----
KGroupedStream<KR, V> groupBy(
  final KeyValueMapper<? super K, ? super V, KR> selector)
KGroupedStream<KR, V> groupBy(
  final KeyValueMapper<? super K, ? super V, KR> selector,
  final Serialized<KR, V> serialized)
----

Creates a <<kafka-streams-KGroupedStream.adoc#, KGroupedStream>> with a given <<kafka-streams-KeyValueMapper.adoc#, KeyValueMapper>>

| groupByKey
a| [[groupByKey]]

[source, java]
----
KGroupedStream<K, V> groupByKey()
KGroupedStream<K, V> groupByKey(final Serialized<K, V> serialized)
----

Creates a <<kafka-streams-KGroupedStream.adoc#, KGroupedStream>>

| join
a| [[join]]

[source, java]
----
KStream<K, RV> join(
  final GlobalKTable<GK, GV> globalKTable,
  final KeyValueMapper<? super K, ? super V, ? extends GK> keyValueMapper,
  final ValueJoiner<? super V, ? super GV, ? extends RV> joiner)
KStream<K, VR> join(
  final KStream<K, VO> otherStream,
  final ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  final JoinWindows windows)
KStream<K, VR> join(
  final KStream<K, VO> otherStream,
  final ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  final JoinWindows windows,
  final Joined<K, V, VO> joined)
KStream<K, VR> join(
  final KTable<K, VT> table,
  final ValueJoiner<? super V, ? super VT, ? extends VR> joiner)
KStream<K, VR> join(
  final KTable<K, VT> table,
  final ValueJoiner<? super V, ? super VT, ? extends VR> joiner,
  final Joined<K, V, VT> joined)
----

| leftJoin
a| [[leftJoin]]

[source, java]
----
KStream<K, RV> leftJoin(
  final GlobalKTable<GK, GV> globalKTable,
  final KeyValueMapper<? super K, ? super V, ? extends GK> keyValueMapper,
  final ValueJoiner<? super V, ? super GV, ? extends RV> valueJoiner)
KStream<K, VR> leftJoin(
  final KStream<K, VO> otherStream,
  final ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  final JoinWindows windows)
KStream<K, VR> leftJoin(
  final KStream<K, VO> otherStream,
  final ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  final JoinWindows windows,
  final Joined<K, V, VO> joined)
KStream<K, VR> leftJoin(
  final KTable<K, VT> table,
  final ValueJoiner<? super V, ? super VT, ? extends VR> joiner)
KStream<K, VR> leftJoin(
  final KTable<K, VT> table,
  final ValueJoiner<? super V, ? super VT, ? extends VR> joiner,
  final Joined<K, V, VT> joined)
----

| map
a| [[map]]

[source, java]
----
KStream<KR, VR> map(
  KeyValueMapper<? super K, ? super V, ? extends KeyValue<? extends KR, ? extends VR>> mapper)
----

| mapValues
a| [[mapValues]]

[source, java]
----
KStream<K, VR> mapValues(
  ValueMapper<? super V, ? extends VR> mapper)
KStream<K, VR> mapValues(
  final ValueMapperWithKey<? super K, ? super V, ? extends VR> mapper)
----

| merge
a| [[merge]]

[source, java]
----
KStream<K, V> merge(final KStream<K, V> stream)
----

| outerJoin
a| [[outerJoin]]

[source, java]
----
KStream<K, VR> outerJoin(
  final KStream<K, VO> otherStream,
  final ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  final JoinWindows windows)
KStream<K, VR> outerJoin(
  final KStream<K, VO> otherStream,
  final ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  final JoinWindows windows,
  final Joined<K, V, VO> joined)
----

| peek
a| [[peek]]

[source, java]
----
KStream<K, V> peek(
  final ForeachAction<? super K, ? super V> action)
----

| print
a| [[print]]

[source, java]
----
void print(final Printed<K, V> printed)
----

| process
a| [[process]]

[source, java]
----
void process(
  final ProcessorSupplier<? super K, ? super V> processorSupplier,
  final String... stateStoreNames)
----

| selectKey
a| [[selectKey]]

[source, java]
----
KStream<KR, V> selectKey(
  KeyValueMapper<? super K, ? super V, ? extends KR> mapper)
----

| through
a| [[through]]

[source, java]
----
KStream<K, V> through(final String topic)
KStream<K, V> through(
  final String topic,
  final Produced<K, V> produced)
----

| to
a| [[to]]

[source, java]
----
void to(final String topic)
void to(final String topic, final Produced<K, V> produced)
void to(final TopicNameExtractor<K, V> topicExtractor)
void to(
  final TopicNameExtractor<K, V> topicExtractor,
  final Produced<K, V> produced)
----

The specified `topic` should be manually created before the Kafka Streams application is started.

| transform
a| [[transform]]

[source, java]
----
KStream<K1, V1> transform(
  final TransformerSupplier<? super K, ? super V, KeyValue<K1, V1>> transformerSupplier,
  final String... stateStoreNames)
----

Stateful record transformation

| transformValues
a| [[transformValues]]

[source, java]
----
KStream<K, VR> transformValues(
  final ValueTransformerSupplier<? super V, ? extends VR> valueTransformerSupplier,
  final String... stateStoreNames)
KStream<K, VR> transformValues(
  final ValueTransformerWithKeySupplier<? super K, ? super V, ? extends VR> valueTransformerSupplier,
  final String... stateStoreNames)
----

Stateful record-by-record value transformation

`transformValues` uses link:kafka-streams-ValueTransformerSupplier.adoc[ValueTransformerSupplier] to create a link:kafka-streams-ValueTransformer.adoc[ValueTransformer] that is used for a stateful transformation of record values in a stream.

|===

[[implementations]]
NOTE: link:kafka-streams-KStreamImpl.adoc[KStreamImpl] is the one and only known implementation of the <<contract, KStream Contract>> in Kafka Streams {{ book.kafka_version }}.
