== [[ProcessorStateManager]] ProcessorStateManager

`ProcessorStateManager` is a concrete link:kafka-streams-AbstractStateManager.adoc[AbstractStateManager] that...FIXME

`ProcessorStateManager` is <<creating-instance, created>> exclusively when `AbstractTask` is link:kafka-streams-AbstractTask.adoc#creating-instance[created].

[[STATE_CHANGELOG_TOPIC_SUFFIX]]
`ProcessorStateManager` uses `-changelog` for the suffix of state changelog topic names.

=== [[storeChangelogTopic]] `storeChangelogTopic` Method

[source, java]
----
static String storeChangelogTopic(final String applicationId, final String storeName)
----

`storeChangelogTopic`...FIXME

NOTE: `storeChangelogTopic` is used when...FIXME

=== [[checkpoint]] `checkpoint` Method

[source, java]
----
void checkpoint(final Map<TopicPartition, Long> ackedOffsets)
----

NOTE: `checkpoint` is part of link:kafka-streams-Checkpointable.adoc#checkpoint[Checkpointable Contract] to...FIXME.

`checkpoint`...FIXME

=== [[creating-instance]] Creating ProcessorStateManager Instance

`ProcessorStateManager` takes the following when created:

* [[taskId]] Task ID
* [[sources]] Sources (as Kafka https://kafka.apache.org/11/javadoc/org/apache/kafka/common/TopicPartition.html[TopicPartitions])
* [[isStandby]] `isStandby` Flag
* [[stateDirectory]] link:kafka-streams-StateDirectory.adoc[StateDirectory]
* [[storeToChangelogTopic]] `Map<String, String>`
* [[changelogReader]] link:kafka-streams-ChangelogReader.adoc[ChangelogReader]
* [[eosEnabled]] `eosEnabled` Flag (that corresponds to link:kafka-streams-properties.adoc#processing.guarantee[processing.guarantee] configuration property)
* [[logContext]] `LogContext`

`ProcessorStateManager` initializes the <<internal-registries, internal registries and counters>>.

=== [[register]] Registering StateStore (and StateRestoreCallback) -- `register` Method

[source, java]
----
void register(
  final StateStore store,
  final StateRestoreCallback stateRestoreCallback)
----

NOTE: `register` is part of link:kafka-streams-StateManager.adoc#register[StateManager Contract] to...FIXME.

`register`...FIXME
