== [[Task]] Task Contract -- Stream Processor Tasks

`Task` is the <<contract, abstraction>> of <<implementations, stream processor tasks>>.

[[contract]]
.Task Contract
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| applicationId
a| [[applicationId]]

[source, java]
----
String applicationId()
----

*Application ID* of the Kafka Streams application the task belongs to

| changelogPartitions
a| [[changelogPartitions]]

[source, java]
----
Collection<TopicPartition> changelogPartitions()
----

Changelog partitions associated with the task

Used when:

* `AssignedStreamsTasks` is requested to <<kafka-streams-internals-AssignedStreamsTasks.adoc#updateRestored, updateRestored>> and <<kafka-streams-internals-AssignedStreamsTasks.adoc#addToRestoring, addToRestoring>>

* `AssignedTasks` is requested to <<kafka-streams-internals-AssignedTasks.adoc#transitionToRunning, mark a task as ready for execution and processing records>>

* `StreamTask` is requested to <<kafka-streams-internals-StreamTask.adoc#initializeStateStores, initialize state stores>>

| close
a| [[close]]

[source, java]
----
void close(
  boolean clean,
  boolean isZombie)
----

Closes the task

Used when:

* `AssignedTasks` is requested to <<kafka-streams-internals-AssignedTasks.adoc#closeNonRunningTasks, closeNonRunningTasks>>, <<kafka-streams-internals-AssignedTasks.adoc#suspendTasks, suspendTasks>>, <<kafka-streams-internals-AssignedTasks.adoc#closeZombieTask, closeZombieTask>>, <<kafka-streams-internals-AssignedTasks.adoc#close, close>>, and <<kafka-streams-internals-AssignedTasks.adoc#closeUnclean, closeUnclean>>

* `StandbyTask` is requested to <<kafka-streams-internals-StandbyTask.adoc#closeSuspended, closeSuspended>>

| closeSuspended
a| [[closeSuspended]]

[source, java]
----
void closeSuspended(
  boolean clean,
  boolean isZombie,
  RuntimeException e)
----

Used when:

* `AssignedTasks` is requested to <<kafka-streams-internals-AssignedTasks.adoc#closeNonAssignedSuspendedTasks, closeNonAssignedSuspendedTasks>>

* `StreamTask` is requested to <<kafka-streams-internals-StreamTask.adoc#close, close>>

| commit
a| [[commit]]

[source, java]
----
void commit()
----

Commits the task

Used when:

* `AssignedStreamsTasks` is requested to <<kafka-streams-internals-AssignedStreamsTasks.adoc#maybeCommitPerUserRequested, maybeCommitPerUserRequested>>

* `AssignedTasks` is requested to <<kafka-streams-internals-AssignedTasks.adoc#commit, commit>>

* `StandbyTask` is requested to <<kafka-streams-internals-StandbyTask.adoc#close, close>>

| commitNeeded
a| [[commitNeeded]]

[source, java]
----
boolean commitNeeded()
----

Used when:

* `AssignedStreamsTasks` is requested to <<kafka-streams-internals-AssignedStreamsTasks.adoc#maybeCommitPerUserRequested, maybeCommitPerUserRequested>>

* `AssignedTasks` is requested to <<kafka-streams-internals-AssignedTasks.adoc#commit, commit>>

| context
a| [[context]]

[source, java]
----
ProcessorContext context()
----

<<kafka-streams-ProcessorContext.adoc#, ProcessorContext>> of the task

| getStore
a| [[getStore]]

[source, java]
----
StateStore getStore(String name)
----

Looks up the <<kafka-streams-StateStore.adoc#, state store>> by name

Used exclusively when `StreamThreadStateStoreProvider` is requested for the <<kafka-streams-internals-StreamThreadStateStoreProvider.adoc#stores, stores>>

| hasStateStores
a| [[hasStateStores]]

[source, java]
----
boolean hasStateStores()
----

| id
a| [[id]]

[source, java]
----
TaskId id()
----

<<kafka-streams-TaskId.adoc#, TaskId>> of the task

| initializeStateStores
a| [[initializeStateStores]]

[source, java]
----
boolean initializeStateStores()
----

Initializes <<kafka-streams-StateStore.adoc#, state stores>> (of the <<topology, ProcessorTopology>>)

Enabled (`true`) if the task has no state stores that need restoring.

* `StandbyTask` always returns <<kafka-streams-internals-StandbyTask.adoc#initializeStateStores, true>>

Used exclusively when `AssignedTasks` is requested to <<kafka-streams-internals-AssignedTasks.adoc#initializeNewTasks, initialize new tasks>>

| initializeTopology
a| [[initializeTopology]]

[source, java]
----
void initializeTopology()
----

Initializes the <<topology, topology of processor nodes>>

Used exclusively when `AssignedTasks` is requested to <<kafka-streams-internals-AssignedTasks.adoc#transitionToRunning, mark the specified task as ready for execution and processing records>>

| partitions
a| [[partitions]]

[source, java]
----
Set<TopicPartition> partitions()
----

Used when:

* `AssignedStreamsTasks` is requested to <<kafka-streams-internals-AssignedStreamsTasks.adoc#addToRestoring, addToRestoring>>

* `AssignedTasks` is requested to <<kafka-streams-internals-AssignedTasks.adoc#maybeResumeSuspendedTask, maybeResumeSuspendedTask>>, <<kafka-streams-internals-AssignedTasks.adoc#transitionToRunning, transitionToRunning>>, and <<kafka-streams-internals-AssignedTasks.adoc#closeNonAssignedSuspendedTasks, closeNonAssignedSuspendedTasks>>

* `StreamThread` is requested to <<kafka-streams-internals-StreamThread.adoc#updateThreadMetadata, updateThreadMetadata>>

| resume
a| [[resume]]

[source, java]
----
void resume()
----

Resumes the task

Used exclusively when `AssignedTasks` is requested to <<kafka-streams-internals-AssignedTasks.adoc#maybeResumeSuspendedTask, attempt to resume suspended task>> (when the task has actually been <<kafka-streams-internals-AssignedTasks.adoc#suspended, suspended>>)

| suspend
a| [[suspend]]

[source, java]
----
void suspend()
----

Suspends the task

Used exclusively when `AssignedTasks` is requested to <<kafka-streams-internals-AssignedTasks.adoc#suspendTasks, suspend tasks>>.

| topology
a| [[topology]]

[source, java]
----
ProcessorTopology topology()
----

<<kafka-streams-internals-ProcessorTopology.adoc#, ProcessorTopology>> of the task

| toString
a| [[toString]]

[source, java]
----
String toString(String indent)
----

Describes the task (*textual representation*)

|===

[[implementations]]
NOTE: <<kafka-streams-internals-AbstractTask.adoc#, AbstractTask>> is the base implementation of the <<contract, Task Contract>> in Kafka Streams (with <<kafka-streams-internals-StandbyTask.adoc#, StandbyTask>> and <<kafka-streams-internals-StreamTask.adoc#, StreamTask>> as the only concrete implementations).
