== [[AssignedStandbyTasks]] AssignedStandbyTasks -- AssignedTasks For StandbyTasks

`AssignedStandbyTasks` is a link:kafka-streams-internals-AssignedTasks.adoc[AssignedTasks] for link:kafka-streams-internals-StandbyTask.adoc[StandbyTasks] that...FIXME

`AssignedStandbyTasks` is <<creating-instance, created>> along with a link:kafka-streams-internals-StreamThread.adoc#create[StreamThread] (when `KafkaStreams` is link:kafka-streams-KafkaStreams.adoc#creating-instance[created]).

[[logContext]]
[[creating-instance]]
`AssignedStandbyTasks` takes a `LogContext` when created.

`AssignedStandbyTasks` uses *standby task* for link:kafka-streams-internals-AssignedTasks.adoc#taskTypeName[taskTypeName].

[[logging]]
[TIP]
====
Enable any of `ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE` logging levels for `org.apache.kafka.streams.processor.internals.AssignedStandbyTasks` logger to see what happens inside.

Add the following line to `log4j.properties`:

```
log4j.logger.org.apache.kafka.streams.processor.internals.AssignedStandbyTasks=TRACE
```

Refer to link:kafka-logging.adoc#log4j.properties[Application Logging Using log4j].
====
