== [[StateConsumer]] StateConsumer

`StateConsumer` is...FIXME

`StateConsumer` is <<creating-instance, created>> exclusively when `GlobalStreamThread` is requested to link:kafka-streams-GlobalStreamThread.adoc#initialize[initialize].

`StateConsumer` uses link:kafka-streams-properties.adoc#poll.ms[poll.ms] configuration property as the <<pollMs, polling interval>> while <<pollAndUpdate, polling the topics for records>>.

=== [[pollAndUpdate]] `pollAndUpdate` Method

[source, java]
----
void pollAndUpdate()
----

`pollAndUpdate`...FIXME

NOTE: `pollAndUpdate` is used exclusively when `GlobalStreamThread` is link:kafka-streams-GlobalStreamThread.adoc#run[running].

=== [[creating-instance]] Creating StateConsumer Instance

`StateConsumer` takes the following when created:

* [[logContext]] `LogContext`
* [[globalConsumer]] Kafka `Consumer<byte[], byte[]>`
* [[stateMaintainer]] link:kafka-streams-GlobalStateMaintainer.adoc[GlobalStateMaintainer]
* [[time]] `Time`
* [[pollMs]] Polling interval (in milliseconds)
* [[flushInterval]] `flushInterval`

`StateConsumer` initializes the <<internal-registries, internal registries and counters>>.
