== Configuration Properties

.Configuration Properties
[cols="1,1,2",options="header",width="100%"]
|===
| Name
| Default Value
| Description

| [[application.id]] `application.id`
|
| *Application ID*, i.e. the identifier of a stream processing application.

It must be unique within the Kafka cluster as it is used as the default client-id prefix, the group-id for membership management, and the changelog topic prefix.

Use `StreamsConfig.APPLICATION_ID_CONFIG` to reference the property.

| [[commit.interval.ms]] `commit.interval.ms`
a|

* `100L` when <<processing.guarantee, processing.guarantee>> is <<exactly_once, exactly_once>> (which is not by default)
* `30000L` otherwise

a| *Flush interval* (in milliseconds), i.e. the time between persisting the position of a processor.

Use `StreamsConfig.COMMIT_INTERVAL_MS_CONFIG` to reference the property.

| [[num.stream.threads]] `num.stream.threads`
| 1
| The number of link:kafka-streams-KafkaStreams.adoc#threads[threads to execute stream processing].

| [[poll.ms]] `poll.ms`
| `100`
a| *Polling interval* (in milliseconds), i.e. the time spent waiting in `Consumer.poll` (unless data is available in the buffer). If `0`, returns immediately with any records that are available currently in the buffer, else returns empty. Must not be negative.

* Used when `GlobalStreamThread` is requested to link:kafka-streams-GlobalStreamThread.adoc#initialize[initialize] (which is right after `KafkaStreams` has been link:kafka-streams-KafkaStreams.adoc#start[started]) and creates a link:kafka-streams-StateConsumer.adoc#pollMs[StateConsumer]

* Used when `StreamThread` is link:kafka-streams-StreamThread.adoc#pollTimeMs[created]

Use `StreamsConfig.POLL_MS_CONFIG` to reference the property.

| [[processing.guarantee]] `processing.guarantee`
| `at_least_once`
a| *Processing guarantee* (aka _Exactly-Once Support_ or _EOS support_)

Possible values are:

* [[at_least_once]] *at_least_once* (default)
* [[exactly_once]] *exactly_once*

[NOTE]
====
<<exactly_once, exactly-once>> processing guarantee requires a Kafka cluster with at least three brokers (which is the recommended setting for production).

For development you can change this by adjusting broker setting `transaction.state.log.replication.factor`.
====

Use `StreamsConfig.PROCESSING_GUARANTEE_CONFIG` to reference the property.

| [[state.cleanup.delay.ms]] `state.cleanup.delay.ms`
| 10 * 60 * 1000
| The amount of time (in milliseconds) to wait before deleting state when a partition has migrated. Only state directories that have not been modified for at least `state.cleanup.delay.ms` will be removed.

| [[state.dir]] `state.dir`
| `/tmp/kafka-streams`
a| Path to the base directory for a state storage

* Used when `StateDirectory` is link:kafka-streams-StateDirectory.adoc#creating-instance[created]

Use `StreamsConfig.STATE_DIR_CONFIG` to reference the property.

|===
