== [[GlobalStateUpdateTask]] GlobalStateUpdateTask -- The Default GlobalStateMaintainer

`GlobalStateUpdateTask` is the one and only link:kafka-streams-GlobalStateMaintainer.adoc[GlobalStateMaintainer] that...FIXME

`GlobalStateUpdateTask` is <<creating-instance, created>> exclusively when `GlobalStreamThread` is requested to link:kafka-streams-GlobalStreamThread.adoc#initialize[initialize] (and creates a link:kafka-streams-StateConsumer.adoc#stateMaintainer[StateConsumer]).

=== [[initialize]] `initialize` Method

[source, java]
----
Map<TopicPartition, Long> initialize()
----

NOTE: `initialize` is part of link:kafka-streams-GlobalStateMaintainer.adoc#initialize[GlobalStateMaintainer Contract] to...FIXME.

`initialize`...FIXME

=== [[update]] `update` Method

[source, java]
----
void update(final ConsumerRecord<byte[], byte[]> record)
----

NOTE: `update` is part of link:kafka-streams-GlobalStateMaintainer.adoc#update[GlobalStateMaintainer Contract] to...FIXME.

`update`...FIXME

=== [[flushState]] `flushState` Method

[source, java]
----
void flushState()
----

NOTE: `flushState` is part of link:kafka-streams-GlobalStateMaintainer.adoc#flushState[GlobalStateMaintainer Contract] to...FIXME.

`flushState`...FIXME

=== [[close]] `close` Method

[source, java]
----
void close() throws IOException
----

NOTE: `close` is part of link:kafka-streams-GlobalStateMaintainer.adoc#close[GlobalStateMaintainer Contract] to...FIXME.

`close`...FIXME

=== [[creating-instance]] Creating GlobalStateUpdateTask Instance

`GlobalStateUpdateTask` takes the following when created:

* [[topology]] `ProcessorTopology`
* [[processorContext]] `InternalProcessorContext`
* [[stateMgr]] `GlobalStateManager`
* [[deserializationExceptionHandler]] `DeserializationExceptionHandler`
* [[logContext]] `LogContext`

`GlobalStateUpdateTask` initializes the <<internal-registries, internal registries and counters>>.
