== KafkaStreams, StreamThreads, StreamTasks and StandbyTasks

=== KafkaStreams, StreamThreads and StreamsConfig.NUM_STREAM_THREADS_CONFIG

A <<kafka-streams-KafkaStreams.adoc#, KafkaStreams>> instance uses <<kafka-streams-internals-StreamThread.adoc#, StreamThreads>> for stream processing.

The number of `StreamThreads` is controlled by <<kafka-streams-StreamsConfig.adoc#NUM_STREAM_THREADS_CONFIG, StreamsConfig.NUM_STREAM_THREADS_CONFIG>> (`num.stream.threads`) configuration property.

=== StreamThread, Kafka Consumer and Consumer Group

`StreamThread` is given a <<kafka-streams-internals-StreamThread.adoc#consumer, Kafka Consumer>> (`Consumer<byte[], byte[]>`) using <<kafka-streams-KafkaClientSupplier.adoc#, KafkaClientSupplier>> when <<kafka-streams-internals-StreamThread.adoc#create, created>>.

`StreamThread` <<kafka-streams-internals-StreamThread.adoc#StreamThread-Consumer, uses the Kafka consumer>> to act as a regular Kafka consumer (e.g. subscribes to the source topics of a topology or poll records) and simply becomes a Kafka client.

When `KafkaClientSupplier` is requested for a <<kafka-streams-KafkaClientSupplier.adoc#getConsumer, Kafka Consumer>>, `StreamThread` passes on the <<kafka-streams-StreamsConfig.adoc#getMainConsumerConfigs, consumer configuration>> with `ConsumerConfig.GROUP_ID_CONFIG` for consumer group ID and `CommonClientConfigs.CLIENT_ID_CONFIG` for client ID.

`ConsumerConfig.GROUP_ID_CONFIG` is exactly <<kafka-streams-StreamsConfig.adoc#APPLICATION_ID_CONFIG, StreamsConfig.APPLICATION_ID_CONFIG>>.

In summary, using the required <<kafka-streams-StreamsConfig.adoc#APPLICATION_ID_CONFIG, StreamsConfig.APPLICATION_ID_CONFIG>> for group ID among all `StreamThreads` of a Kafka Streams application creates a consumer group. Dynamic partition assignment is controlled using Kafka protocol via <<kafka-streams-internals-StreamsPartitionAssignor.adoc#, StreamsPartitionAssignor>> among all `StreamThreads`.

=== StreamThread, TaskManager and StreamTask

Every `StreamThread` manages its own <<kafka-streams-internals-TaskManager.adoc#, TaskManager>> (with the factories to create <<kafka-streams-internals-TaskCreator.adoc#, stream>> and <<kafka-streams-internals-StandbyTaskCreator.adoc#, standby>> tasks).

When requested to <<kafka-streams-internals-StreamThread.adoc#runOnce, poll records once and process them using active stream tasks>>, `StreamThread` requests the `TaskManager` for <<kafka-streams-internals-TaskManager.adoc#activeTask, active stream tasks>> for every partition with records (see <<kafka-streams-internals-StreamThread.adoc#addRecordsToTasks, StreamThread.addRecordsToTasks>>).

A single `StreamTask` is responsible for processing records from <<kafka-streams-internals-StreamTask.adoc#partitions, one or more assigned partitions>> (using <<kafka-streams-internals-StreamTask.adoc#partitionGroup, partition queues of RecordQueues per TopicPartition>>).

When requested for a <<kafka-streams-internals-TaskCreator.adoc#createTask, StreamTask>>, `TaskCreator` is given partitions.

NOTE: Explore the relationship between topic groups, partitions and tasks (`builder.build(taskId.topicGroupId)` while creating a `StreamTask`) which is <<kafka-streams-internals-TaskManager.adoc#addStreamTask, TaskManager.addStreamTask>>.

The number of `StreamTask` is exactly the number of partitions assigned (as `StreamTasks` simply create a consumer group and so every partition can only be consumed by one and exactly one consumer group member).

* Number of StreamTasks = # TaskCreator.createTask = # AbstractTaskCreator.createTasks = TaskManager.addStreamTasks

<<kafka-streams-StreamsConfig.adoc#NUM_STANDBY_REPLICAS_CONFIG, StreamsConfig.NUM_STANDBY_REPLICAS_CONFIG>> (`num.standby.replicas`) is the number of <<kafka-streams-internals-StandbyTask.adoc#, standby replicas>> for each task.

* StickyTaskAssignor.assignActive = number of tasks per StreamThread

* StickyTaskAssignor.assign

StreamsPartitionAssignor.assign —> TaskManager.builder().topicGroups() —> PartitionGrouper.partitionGroups(sourceTopicsByGroup, fullMetadata)

At this step = Map<TaskId, Set<TopicPartition>> partitionsForTask

Enable DEBUG logging level for org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor

DEBUG Assigning tasks {} to clients {} with number of replicas {}

Step 1. StreamsPartitionAssignor.onAssignment(final Assignment assignment) —> TaskManager.setAssignmentMetadata(Map<TaskId, Set<TopicPartition>> activeTasks, Map<TaskId, Set<TopicPartition>> standbyTasks)

Step 2. RebalanceListener.onPartitionsAssigned(Collection<TopicPartition> assignment) —> TaskManager.createTasks(assignment)

`StreamsPartitionAssignor` makes sure that the <<kafka-streams-internals-StreamsPartitionAssignor.adoc#processVersionOneAssignment, number of assigned partitions to a Kafka Streams application instance is exactly the same as number of active tasks>>.
