== [[AbstractTask]] AbstractTask -- Base Processor Task

`AbstractTask` is the base of <<implementations, stream processor tasks>> that <<FIXME, FIXME>>.

NOTE: `AbstractTask` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly when the <<implementations, concrete AbstractTasks>> are.

[[eosEnabled]]
`AbstractTask` uses link:kafka-streams-properties.adoc#processing.guarantee[processing.guarantee] configuration property to enable link:kafka-streams-exactly-once-support-eos.adoc[Exactly-Once Support] for...FIXME

[[taskInitialized]]
`AbstractTask` has `taskInitialized` flag that is on (i.e. `true`) to mark when:

* `StandbyTask` has finished link:kafka-streams-StandbyTask.adoc#initializeStateStores[initializeStateStores] successfully

* `StreamTask` has finished link:kafka-streams-StreamTask.adoc#initializeTopology[initializeTopology]

The `taskInitialized` flag is used by the <<implementations, concrete AbstractTasks>> as an optimization when:

* `StandbyTask` is requested to link:kafka-streams-StandbyTask.adoc#close[close]

* `StreamTask` is requested to link:kafka-streams-StreamTask.adoc#closeTopology[closeTopology]

[[taskClosed]]
`AbstractTask` has `taskClosed` flag that is on (i.e. `true`) to mark when:

* `StandbyTask` was requested to link:kafka-streams-StandbyTask.adoc#close[close]

* `StreamTask` was requested to link:kafka-streams-StreamTask.adoc#close[close]

[[internal-registries]]
.AbstractTask's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| processorContext
a| [[processorContext]] link:kafka-streams-InternalProcessorContext.adoc[InternalProcessorContext]:

* `StandbyContextImpl` for `StandbyTask`

* link:kafka-streams-ProcessorContextImpl.adoc[ProcessorContextImpl] for `StreamTask`

| stateMgr
a| [[stateMgr]] <<kafka-streams-ProcessorStateManager.adoc#, ProcessorStateManager>>

<<kafka-streams-ProcessorStateManager.adoc#creating-instance, Created>> when `AbstractTask` is <<creating-instance, created>>
|===

[[implementations]]
.AbstractTasks
[cols="1,2",options="header",width="100%"]
|===
| AbstractTask
| Description

| link:kafka-streams-StreamTask.adoc[StreamTask]
| [[StreamTask]]

| link:kafka-streams-StandbyTask.adoc[StandbyTask]
| [[StandbyTask]]
|===

=== [[closeStateManager]] `closeStateManager` Method

[source, java]
----
void closeStateManager(final boolean writeCheckpoint) throws ProcessorStateException
----

`closeStateManager`...FIXME

NOTE: `closeStateManager` is used when...FIXME

=== [[creating-instance]] Creating AbstractTask Instance

`AbstractTask` takes the following when created:

* [[id]] `TaskId`
* [[partitions]] Kafka https://kafka.apache.org/11/javadoc/org/apache/kafka/common/TopicPartition.html[TopicPartitions]
* [[topology]] link:kafka-streams-ProcessorTopology.adoc[ProcessorTopology]
* [[consumer]] Kafka https://kafka.apache.org/11/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html[Consumer] (of keys and values as array of bytes, i.e. `byte[]`)
* [[changelogReader]] link:kafka-streams-ChangelogReader.adoc[ChangelogReader]
* [[isStandby]] `isStandby` Flag
* [[stateDirectory]] link:kafka-streams-StateDirectory.adoc[StateDirectory]
* [[config]] link:kafka-streams-StreamsConfig.adoc[StreamsConfig]

`AbstractTask` initializes the <<internal-registries, internal registries and counters>>.

=== [[hasStateStores]] Checking If Topology Uses State Stores -- `hasStateStores` Method

[source, java]
----
boolean hasStateStores()
----

NOTE: `hasStateStores` is part of link:kafka-streams-Task.adoc#hasStateStores[Task Contract] to...FIXME.

`hasStateStores` is positive (and returns `true`) when <<topology, ProcessorTopology>> has at least one link:kafka-streams-ProcessorTopology.adoc#stateStores[local state store].

=== [[flushState]] `flushState` Method

[source, java]
----
void flushState()
----

`flushState` simply requests the <<stateMgr, ProcessorStateManager>> to link:kafka-streams-ProcessorStateManager.adoc#flush[flush].

NOTE: `flushState` is used when...FIXME

=== [[recordCollectorOffsets]] `recordCollectorOffsets` Method

[source, java]
----
Map<TopicPartition, Long> recordCollectorOffsets()
----

`recordCollectorOffsets`...FIXME

NOTE: `recordCollectorOffsets` is used when...FIXME

=== [[registerStateStores]] `registerStateStores` Method

[source, java]
----
void registerStateStores()
----

`registerStateStores`...FIXME

NOTE: `registerStateStores` is used when <<kafka-streams-StandbyTask.adoc#initializeStateStores, StandbyTask>> and <<kafka-streams-StreamTask.adoc#initializeStateStores, StreamTask>> are requested to `initializeStateStores`.

=== [[changelogPartitions]] `changelogPartitions` Method

[source, java]
----
Collection<TopicPartition> changelogPartitions()
----

NOTE: `changelogPartitions` is part of <<kafka-streams-Task.adoc#changelogPartitions, Task Contract>> to return changelog partitions associated with the task.

`changelogPartitions` simply requests the <<stateMgr, ProcessorStateManager>> to give the <<kafka-streams-ProcessorStateManager.adoc#changelogPartitions, changelogPartitions>> and returns them.
