== KafkaStreams, StreamThreads, StreamTasks and StandbyTasks

<<kafka-streams-StreamsConfig.adoc#NUM_STREAM_THREADS_CONFIG, StreamsConfig.NUM_STREAM_THREADS_CONFIG>> (`num.stream.threads`) is the number of <<kafka-streams-internals-StreamThread.adoc#, StreamThreads>> that a single <<kafka-streams-KafkaStreams.adoc#, KafkaStreams>> instance creates for stream processing. That means that there will always be at least two threads running for a Kafka Streams application - the main thread of the application and one or many `StreamThreads`.

Every `StreamThread` manages its own <<kafka-streams-internals-TaskManager.adoc#, TaskManager>> (with the factories of <<kafka-streams-internals-TaskCreator.adoc#, stream>> and <<kafka-streams-internals-StandbyTaskCreator.adoc#, standby>> tasks).

When requested to <<kafka-streams-internals-StreamThread.adoc#runOnce, poll records once and process them using active stream tasks>>, `StreamThread` requests the `TaskManager` for <<kafka-streams-internals-TaskManager.adoc#activeTask, active stream tasks>> for every partition with records (see <<kafka-streams-internals-StreamThread.adoc#addRecordsToTasks, StreamThread.addRecordsToTasks>>).

A single `StreamTask` is responsible for processing records from <<kafka-streams-internals-StreamTask.adoc#partitions, one or more assigned partitions>> (using <<kafka-streams-internals-StreamTask.adoc#partitionGroup, partition queues of RecordQueues per TopicPartition>>).

When requested for a <<kafka-streams-internals-TaskCreator.adoc#createTask, StreamTask>>, `TaskCreator` is given partitions.

NOTE: Explore the relationship between topic groups, partitions and tasks (`builder.build(taskId.topicGroupId)` while creating a `StreamTask`) which is <<kafka-streams-internals-TaskManager.adoc#addStreamTask, TaskManager.addStreamTask>>.

* Number of StreamTasks = # TaskCreator.createTask = # AbstractTaskCreator.createTasks = TaskManager.addStreamTasks

<<kafka-streams-StreamsConfig.adoc#NUM_STANDBY_REPLICAS_CONFIG, StreamsConfig.NUM_STANDBY_REPLICAS_CONFIG>> (`num.standby.replicas`) is the number of <<kafka-streams-internals-StandbyTask.adoc#, standby replicas>> for each task.

* StickyTaskAssignor.assignActive = number of tasks per StreamThread

* StickyTaskAssignor.assign

StreamsPartitionAssignor.assign —> TaskManager.builder().topicGroups() —> PartitionGrouper.partitionGroups(sourceTopicsByGroup, fullMetadata)

At this step = Map<TaskId, Set<TopicPartition>> partitionsForTask

Enable DEBUG logging level for org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor

DEBUG Assigning tasks {} to clients {} with number of replicas {}

Step 1. StreamsPartitionAssignor.onAssignment(final Assignment assignment) —> TaskManager.setAssignmentMetadata(Map<TaskId, Set<TopicPartition>> activeTasks, Map<TaskId, Set<TopicPartition>> standbyTasks)

Step 2. RebalanceListener.onPartitionsAssigned(Collection<TopicPartition> assignment) —> TaskManager.createTasks(assignment)

`StreamsPartitionAssignor` makes sure that the <<kafka-streams-internals-StreamsPartitionAssignor.adoc#processVersionOneAssignment, number of assigned partitions to a Kafka Streams application instance is exactly the same as number of active tasks>>.
