== [[Task]] Task -- Contract for Stream Processor Tasks

`Task` is the <<contract, contract>> in Kafka Streams for *stream processor tasks* that are identified by <<id, id>> and...FIXME

NOTE: link:kafka-streams-AbstractTask.adoc[AbstractTask] is the direct implementation of `Task` available with the concrete link:kafka-streams-StandbyTask.adoc[StandbyTask] and link:kafka-streams-StreamTask.adoc[StreamTask] implementations.

The lifecycle of a task is...FIXME

There are two types of partitions that a task operates on:

1. <<partitions, partitions>>

1. <<changelogPartitions, changelogPartitions>>

[[contract]]
[source, java]
----
package org.apache.kafka.streams.processor.internals;

public interface Task {
  String applicationId();
  Collection<TopicPartition> changelogPartitions();
  void close(final boolean clean,
             final boolean isZombie);
  void closeSuspended(final boolean clean,
                      final boolean isZombie,
                      final RuntimeException e);
  void commit();
  ProcessorContext context();
  StateStore getStore(final String name);
  boolean hasStateStores();
  TaskId id();
  boolean initializeStateStores();
  void initializeTopology();
  Set<TopicPartition> partitions();
  void resume();
  void suspend();
  ProcessorTopology topology();
  String toString(final String indent);
}
----

.Task Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[changelogPartitions]] `changelogPartitions`
| Used when...

| [[close]] `close`
a|

Used when:

* `AssignedTasks` is requested to do the following:

** link:kafka-streams-AssignedTasks.adoc#close[close]

** link:kafka-streams-AssignedTasks.adoc#closeNonRunningTasks[closeNonRunningTasks]

** link:kafka-streams-AssignedTasks.adoc#closeUnclean[closeUnclean]

** link:kafka-streams-AssignedTasks.adoc#closeZombieTask[closeZombieTask]

** link:kafka-streams-AssignedTasks.adoc#suspendTasks[suspendTasks] (and suspending a task has failed)

* `StandbyTask` is requested to link:kafka-streams-StandbyTask.adoc#closeSuspended[closeSuspended]

| [[closeSuspended]] `closeSuspended`
| Used when...

| [[hasStateStores]] `hasStateStores`
a|

Used when `AssignedTasks` is requested to:

* link:kafka-streams-AssignedTasks.adoc#transitionToRunning[Schedule a task for execution]

* link:kafka-streams-AssignedTasks.adoc#uninitializedPartitions[Get the partitions of the new tasks with a state store]

---

Implemented exclusively in link:kafka-streams-AbstractTask.adoc#hasStateStores[AbstractTask].

| [[initializeStateStores]] `initializeStateStores`
| Used when...

| [[initializeTopology]] `initializeTopology`
| Used when...

| [[partitions]] `partitions`
| Used when...

| [[resume]] `resume`
| Used when...

| [[toString]] `toString`
| Used when...
|===
