== [[GlobalStateUpdateTask]] GlobalStateUpdateTask -- The Default GlobalStateMaintainer

`GlobalStateUpdateTask` is the one and only link:kafka-streams-GlobalStateMaintainer.adoc[GlobalStateMaintainer] that...FIXME

`GlobalStateUpdateTask` is <<creating-instance, created>> exclusively when `GlobalStreamThread` is requested to link:kafka-streams-GlobalStreamThread.adoc#initialize[initialize] (and creates a link:kafka-streams-StateConsumer.adoc#stateMaintainer[StateConsumer]).

[[offsets]]
`GlobalStateUpdateTask` keeps track of the *offsets* of the records (by the topics and the partitions) that have already been <<update, processed>>. The offsets are then <<flushState, flushed to the global store>> when requested.

[[deserializers]]
`GlobalStateUpdateTask` keeps track of the *deserializers* for...FIXME

=== [[initialize]] Initializing -- `initialize` Method

[source, java]
----
Map<TopicPartition, Long> initialize()
----

NOTE: `initialize` is part of link:kafka-streams-GlobalStateMaintainer.adoc#initialize[GlobalStateMaintainer Contract] to...FIXME.

`initialize`...FIXME

=== [[update]] `update` Method

[source, java]
----
void update(final ConsumerRecord<byte[], byte[]> record)
----

NOTE: `update` is part of link:kafka-streams-GlobalStateMaintainer.adoc#update[GlobalStateMaintainer Contract] to...FIXME.

`update` looks up the link:kafka-streams-RecordDeserializer.adoc[RecordDeserializer] for the topic (of the record) in the <<deserializers, deserializers>> internal registry.

NOTE: `RecordDeserializer` is the metadata of a link:kafka-streams-RecordDeserializer.adoc#sourceNode[SourceNode] that link:kafka-streams-RecordDeserializer.adoc#deserialize[knows how to deserialize a raw record] in a given `ProcessorContext`.

`update` then uses the `RecordDeserializer` to deserialize the record (to the proper types of the key and the value).

When the record has been successfully deserialized, `update` does the following:

1. Creates a link:kafka-streams-ProcessorRecordContext.adoc#creating-instance[ProcessorRecordContext] for the deserialized record

1. Requests <<processorContext, InternalProcessorContext>> to link:kafka-streams-InternalProcessorContext.adoc#setRecordContext[use the record context]

1. Requests <<processorContext, InternalProcessorContext>> to link:kafka-streams-InternalProcessorContext.adoc#setCurrentNode[use the source node] of the link:kafka-streams-RecordDeserializer.adoc#sourceNode[RecordDeserializer]

1. Requests the link:kafka-streams-RecordDeserializer.adoc#sourceNode[SourceNode] (of the deserialized record) to link:kafka-streams-internals-SourceNode.adoc#process[process] the deserialized record

In the end, `update` saves the topic and the partition of the record with the offset in the <<offsets, offsets>> internal registry.

=== [[flushState]] Flushing State Stores -- `flushState` Method

[source, java]
----
void flushState()
----

NOTE: `flushState` is part of link:kafka-streams-GlobalStateMaintainer.adoc#flushState[GlobalStateMaintainer Contract] to...FIXME.

`flushState` requests <<stateMgr, GlobalStateManager>> to link:kafka-streams-StateManager.adoc#flush[flush] followed by link:kafka-streams-Checkpointable.adoc#checkpoint[checkpointing] the <<offsets, offsets>>.

=== [[close]] Closing State Manager -- `close` Method

[source, java]
----
void close() throws IOException
----

NOTE: `close` is part of link:kafka-streams-StateManager.adoc#close[StateManager Contract] to...FIXME.

`close` simply requests <<stateMgr, GlobalStateManager>> to link:kafka-streams-StateManager.adoc#close[close] (passing on the <<offsets, offsets>>).

=== [[creating-instance]] Creating GlobalStateUpdateTask Instance

`GlobalStateUpdateTask` takes the following when created:

* [[topology]] `ProcessorTopology`
* [[processorContext]] link:kafka-streams-InternalProcessorContext.adoc[InternalProcessorContext]
* [[stateMgr]] link:kafka-streams-GlobalStateManager.adoc[GlobalStateManager]
* [[deserializationExceptionHandler]] `DeserializationExceptionHandler`
* [[logContext]] `LogContext`

`GlobalStateUpdateTask` initializes the <<offsets, offsets>> and <<deserializers, deserializers>> internal registries.
