== [[StateManager]] StateManager Contract -- State Store Managers

`StateManager` is the <<contract, contract>> of <<implementations, state store managers>> that manage one or more <<kafka-streams-StateStore.adoc#, state stores>>.

`StateManager` is a <<kafka-streams-Checkpointable.adoc#, Checkpointable>> that...FIXME

[[contract]]
.StateManager Contract
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| baseDir
a| [[baseDir]]

[source, java]
----
File baseDir()
----

Used exclusively when `AbstractProcessorContext` is requested for <<kafka-streams-AbstractProcessorContext.adoc#stateDir, stateDir>>

| close
a| [[close]]

[source, java]
----
void close(final Map<TopicPartition, Long> offsets) throws IOException
----

Closes a state manager

Used when:

* `AbstractTask` is requested to <<kafka-streams-AbstractTask.adoc#closeStateManager, close the state manager>>

* `GlobalStateUpdateTask` is requested to <<kafka-streams-GlobalStateUpdateTask.adoc#close, close the state manager>>

| flush
a| [[flush]]

[source, java]
----
void flush()
----

Flushes all <<kafka-streams-StateStore.adoc#, state stores>> registered with the state manager

Used when:

* <<kafka-streams-AbstractTask.adoc#flushState, AbstractTask>> and <<kafka-streams-GlobalStateUpdateTask.adoc#flushState, GlobalStateUpdateTask>> are requested to flush state stores

* `StandbyTask` is requested to <<kafka-streams-StandbyTask.adoc#flushAndCheckpointState, flush and checkpoint state stores>>

| getGlobalStore
a| [[getGlobalStore]]

[source, java]
----
StateStore getGlobalStore(final String name)
----

Accessing the global <<kafka-streams-StateStore.adoc#, state store>> by name

Used when:

* <<kafka-streams-GlobalProcessorContextImpl.adoc#getStateStore, GlobalProcessorContextImpl>> and <<kafka-streams-ProcessorContextImpl.adoc#getStateStore, ProcessorContextImpl>> are requested to get the global <<kafka-streams-StateStore.adoc#, state store>> by name

* `GlobalStateManagerImpl` is requested to <<kafka-streams-GlobalStateManagerImpl.adoc#getStore, get state store by name>>

| getStore
a| [[getStore]]

[source, java]
----
StateStore getStore(final String name)
----

Accessing the <<kafka-streams-StateStore.adoc#, state store>> by name

Used when <<kafka-streams-AbstractTask.adoc#getStore, AbstractTask>> and <<kafka-streams-ProcessorContextImpl.adoc#getStateStore, ProcessorContextImpl>> are requested to get the state store by name

| register
a| [[register]]

[source, java]
----
void register(
  final StateStore store,
  final StateRestoreCallback stateRestoreCallback)
----

Registering a <<kafka-streams-StateStore.adoc#, state store>> with a `StateRestoreCallback`

Used exclusively when `AbstractProcessorContext` is requested to <<kafka-streams-AbstractProcessorContext.adoc#register, register a state store>>

| reinitializeStateStoresForPartitions
a| [[reinitializeStateStoresForPartitions]]

[source, java]
----
void reinitializeStateStoresForPartitions(
  final Collection<TopicPartition> partitions,
  final InternalProcessorContext processorContext)
----

Used when:

* `AbstractTask` is requested to <<kafka-streams-AbstractTask.adoc#reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>

* `GlobalStateManagerImpl` is requested to <<kafka-streams-GlobalStateManagerImpl.adoc#restoreState, restoreState>>

|===

[[implementations]]
.StateManagers (Direct Extensions)
[cols="1,2",options="header",width="100%"]
|===
| StateManager
| Description

| <<kafka-streams-AbstractStateManager.adoc#, AbstractStateManager>>
| [[AbstractStateManager]]

| <<kafka-streams-GlobalStateManager.adoc#, GlobalStateManager>>
| [[GlobalStateManager]]
|===
