== [[KafkaClientSupplier]] KafkaClientSupplier Contract -- Suppliers of Kafka AdminClient, Consumers and Producers

`KafkaClientSupplier` is the <<contract, contract>> of <<implementations, Kafka client suppliers>> that provide (_supply_) Kafka clients, i.e. <<getAdminClient, AdminClient>>, Kafka Consumers (<<getConsumer, getConsumer>>, <<getGlobalConsumer, getGlobalConsumer>> and <<getRestoreConsumer, getRestoreConsumer>>) and a Kafka <<getProducer, Producer>>.

[[contract]]
.KafkaClientSupplier Contract
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| getAdminClient
a| [[getAdminClient]]

[source, java]
----
AdminClient getAdminClient(final Map<String, Object> config);
----

A Kafka https://kafka.apache.org/20/javadoc/org/apache/kafka/clients/admin/AdminClient.html[AdminClient] (for <<kafka-streams-KafkaStreams.adoc#adminClient, KafkaStreams>>)

Used exclusively when `KafkaStreams` is <<kafka-streams-KafkaStreams.adoc#creating-instance-adminClient, created>>

| getConsumer
a| [[getConsumer]]

[source, java]
----
Consumer<byte[], byte[]> getConsumer(final Map<String, Object> config);
----

A Kafka https://kafka.apache.org/20/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html[Consumer] (for <<kafka-streams-internals-TaskManager.adoc#consumer, TaskManager>> and <<kafka-streams-StreamThread.adoc#consumer, StreamThread>>)

Used exclusively when `StreamThread` is <<kafka-streams-StreamThread.adoc#create, created>> (that also <<kafka-streams-internals-TaskManager.adoc#setConsumer, sets the Kafka Consumer>> for the <<kafka-streams-internals-TaskManager.adoc#taskManager, TaskManager>>)

| getGlobalConsumer
a| [[getGlobalConsumer]]

[source, java]
----
Consumer<byte[], byte[]> getGlobalConsumer(final Map<String, Object> config);
----

A Kafka https://kafka.apache.org/20/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html[Consumer] (for <<kafka-streams-internals-GlobalStreamThread.adoc#globalConsumer, GlobalStreamThread>>)

Used exclusively when `KafkaStreams` is <<kafka-streams-KafkaStreams.adoc#creating-instance, created>> (for the only purpose of creating a <<kafka-streams-KafkaStreams.adoc#globalStreamThread, GlobalStreamThread>>)

| getProducer
a| [[getProducer]]

[source, java]
----
Producer<byte[], byte[]> getProducer(final Map<String, Object> config);
----

A Kafka http://kafka.apache.org/20/javadoc/org/apache/kafka/clients/producer/KafkaProducer.html[Producer] (for <<kafka-streams-StreamThread.adoc#producer, StreamThreads>> and <<kafka-streams-internals-TaskCreator.adoc#threadProducer, TaskCreator>>)

Used when:

* `StreamThread` is <<kafka-streams-StreamThread.adoc#create, created>> (with <<kafka-streams-properties.adoc#processing.guarantee, processing.guarantee>> as <<kafka-streams-properties.adoc#at_least_once, at_least_once>>)

* `TaskCreator` is requested to <<kafka-streams-internals-TaskCreator.adoc#createProducer, createProducer>> (with <<kafka-streams-properties.adoc#processing.guarantee, processing.guarantee>> as <<kafka-streams-properties.adoc#exactly-once, exactly-once>>)

| getRestoreConsumer
a| [[getRestoreConsumer]]

[source, java]
----
Consumer<byte[], byte[]> getRestoreConsumer(final Map<String, Object> config);
----

A Kafka https://kafka.apache.org/20/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html[Consumer] (for <<kafka-streams-StoreChangelogReader.adoc#restoreConsumer, StoreChangelogReader>>, <<kafka-streams-internals-TaskManager.adoc#restoreConsumer, TaskManager>> and <<kafka-streams-StreamThread.adoc#restoreConsumer, StreamThread>>)

Used exclusively when `StreamThread` is <<kafka-streams-StreamThread.adoc#create, created>>

|===

[[implementations]]
NOTE: <<kafka-streams-internals-DefaultKafkaClientSupplier.adoc#, DefaultKafkaClientSupplier>> is the one and only known implementation of the <<contract, KafkaClientSupplier Contract>>.
