== [[KTable]] KTable API -- Changelog Stream

`KTable` is the <<contract, abstraction>> of a *changelog stream* from a primary-keyed table. Each record in the changelog stream is an update on the primary-keyed table with the record key as the primary key.

`KTable` assumes that records from the source topic that have `null` keys are simply dropped.

`KTable` can be created directly from a Kafka topic (using <<kafka-streams-StreamsBuilder.adoc#table, StreamsBuilder.table>> operator), as a result of <<operators, transformations>> on an existing `KTable`, or aggregations (`aggregate`, `count`, and `reduce`) of the following abstractions:

* <<kafka-streams-KGroupedStream.adoc#, KGroupedStream>> (<<kafka-streams-KStream.adoc#groupBy, KStream.groupBy>> and <<kafka-streams-KStream.adoc#groupByKey, KStream.groupByKey>> aggregate stream operators)

* <<kafka-streams-KGroupedTable.adoc#, KGroupedTable>>

* <<kafka-streams-SessionWindowedKStream.adoc#, SessionWindowedKStream>> (<<kafka-streams-KGroupedStream.adoc#windowedBy, KGroupedStream.windowedBy>> stream operator)

* <<kafka-streams-TimeWindowedKStream.adoc#, TimeWindowedKStream>> (<<kafka-streams-KGroupedStream.adoc#windowedBy-TimeWindowedKStream, KGroupedStream.windowedBy>> stream operator with a <<kafka-streams-TimeWindows.adoc#, TimeWindows>> window specification)

TIP: Use <<kafka-streams-scala.adoc#, Scala API for Kafka Streams>> to make your Kafka Streams development more pleasant if Scala is your programming language.

[[contract]]
.KTable API / Operators
[cols="30m,70",options="header",width="100%"]
|===
| Operator
| Description

| filter
a| [[filter]]

[source, java]
----
KTable<K, V> filter(
  Predicate<? super K, ? super V> predicate)
KTable<K, V> filter(
  Predicate<? super K, ? super V> predicate,
  Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
----

| filterNot
a| [[filterNot]]

[source, java]
----
KTable<K, V> filterNot(
  Predicate<? super K, ? super V> predicate)
KTable<K, V> filterNot(
  Predicate<? super K, ? super V> predicate,
  Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
----

| groupBy
a| [[groupBy]]

[source, java]
----
KGroupedTable<KR, VR> groupBy(
  KeyValueMapper<? super K, ? super V, KeyValue<KR, VR>> selector)
KGroupedTable<KR, VR> groupBy(
  KeyValueMapper<? super K, ? super V, KeyValue<KR, VR>> selector,
  Grouped<KR, VR> grouped)
----

| join
a| [[join]]

[source, java]
----
KTable<K, VR> join(
  KTable<K, VO> other,
  ValueJoiner<? super V, ? super VO, ? extends VR> joiner)
KTable<K, VR> join(
  KTable<K, VO> other,
  ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

| leftJoin
a| [[leftJoin]]

[source, java]
----
KTable<K, VR> leftJoin(
  KTable<K, VO> other,
  ValueJoiner<? super V, ? super VO, ? extends VR> joiner)
KTable<K, VR> leftJoin(
  KTable<K, VO> other,
  ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

| mapValues
a| [[mapValues]]

[source, java]
----
KTable<K, VR> mapValues(
  ValueMapper<? super V, ? extends VR> mapper)
KTable<K, VR> mapValues(
  ValueMapper<? super V, ? extends VR> mapper,
  Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
KTable<K, VR> mapValues(
  ValueMapperWithKey<? super K, ? super V, ? extends VR> mapper)
KTable<K, VR> mapValues(
  ValueMapperWithKey<? super K, ? super V, ? extends VR> mapper,
  Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

| outerJoin
a| [[outerJoin]]

[source, java]
----
KTable<K, VR> outerJoin(
  KTable<K, VO> other,
  ValueJoiner<? super V, ? super VO, ? extends VR> joiner)
KTable<K, VR> outerJoin(
  KTable<K, VO> other,
  ValueJoiner<? super V, ? super VO, ? extends VR> joiner,
  Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

| queryableStoreName
a| [[queryableStoreName]]

[source, java]
----
String queryableStoreName()
----

| suppress
a| [[suppress]]

[source, java]
----
KTable<K, V> suppress(
  Suppressed<? super K> suppressed)
----

| toStream
a| [[toStream]]

[source, java]
----
KStream<K, V> toStream()
KStream<KR, V> toStream(
  KeyValueMapper<? super K, ? super V, ? extends KR> mapper)
----

| transformValues
a| [[transformValues]]

[source, java]
----
KTable<K, VR> transformValues(
  ValueTransformerWithKeySupplier<? super K, ? super V, ? extends VR> transformerSupplier,
  Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized,
  String... stateStoreNames)
KTable<K, VR> transformValues(
  ValueTransformerWithKeySupplier<? super K, ? super V, ? extends VR> transformerSupplier,
  String... stateStoreNames)
----

|===
