== [[Task]] Task Contract -- Stream Processor Tasks

`Task` is the <<contract, contract>> in Kafka Streams for *stream processor tasks* that are identified by <<id, id>> and...FIXME

NOTE: link:kafka-streams-AbstractTask.adoc[AbstractTask] is the direct implementation of `Task` available with the concrete link:kafka-streams-StandbyTask.adoc[StandbyTask] and link:kafka-streams-StreamTask.adoc[StreamTask] implementations.

The lifecycle of a task is...FIXME

There are two types of partitions that a task operates on:

1. <<partitions, partitions>>

1. <<changelogPartitions, changelogPartitions>>

[[contract]]
[source, java]
----
package org.apache.kafka.streams.processor.internals;

public interface Task {
  String applicationId();
  Collection<TopicPartition> changelogPartitions();
  void close(final boolean clean,
             final boolean isZombie);
  void closeSuspended(final boolean clean,
                      final boolean isZombie,
                      final RuntimeException e);
  void commit();
  ProcessorContext context();
  StateStore getStore(final String name);
  boolean hasStateStores();
  TaskId id();
  boolean initializeStateStores();
  void initializeTopology();
  Set<TopicPartition> partitions();
  void resume();
  void suspend();
  ProcessorTopology topology();
  String toString(final String indent);
}
----

.Task Contract
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| applicationId
a| [[applicationId]]

[source, java]
----
String applicationId()
----

| changelogPartitions
a| [[changelogPartitions]]

[source, java]
----
Collection<TopicPartition> changelogPartitions()
----

Changelog partitions associated with the task

Used when:

* `AssignedTasks` is requested to <<kafka-streams-AssignedTasks.adoc#updateRestored, updateRestored>>, <<kafka-streams-AssignedTasks.adoc#addToRestoring, addToRestoring>> and <<kafka-streams-AssignedTasks.adoc#transitionToRunning, transitionToRunning>>

* `StreamTask` is requested to <<kafka-streams-StreamTask.adoc#initializeStateStores, initialize state stores>>.

| close
a| [[close]]

[source, java]
----
void close(
  final boolean clean,
  final boolean isZombie)
----

Used when:

* `AssignedTasks` is requested to do the following:

** link:kafka-streams-AssignedTasks.adoc#close[close]

** link:kafka-streams-AssignedTasks.adoc#closeNonRunningTasks[closeNonRunningTasks]

** link:kafka-streams-AssignedTasks.adoc#closeUnclean[closeUnclean]

** link:kafka-streams-AssignedTasks.adoc#closeZombieTask[closeZombieTask]

** link:kafka-streams-AssignedTasks.adoc#suspendTasks[suspendTasks] (and suspending a task has failed)

* `StandbyTask` is requested to link:kafka-streams-StandbyTask.adoc#closeSuspended[closeSuspended]

| closeSuspended
a| [[closeSuspended]]

[source, java]
----
void closeSuspended(
  final boolean clean,
  final boolean isZombie,
  final RuntimeException e)
----

| commit
a| [[commit]]

[source, java]
----
void commit()
----

Used when:

* `AssignedStreamsTasks` is requested to execute the <<kafka-streams-AssignedStreamsTasks.adoc#maybeCommitAction, maybeCommitAction>> action

* `AssignedTasks` is requested to execute the <<kafka-streams-AssignedTasks.adoc#commitAction, commitAction>> action

* `StandbyTask` is requested to <<kafka-streams-StandbyTask.adoc#close, close>>

| context
a| [[context]]

[source, java]
----
ProcessorContext context()
----

| getStore
a| [[getStore]]

[source, java]
----
StateStore getStore(final String name)
----

Gets the <<kafka-streams-StateStore.adoc#, state store>> by name

| hasStateStores
a| [[hasStateStores]]

[source, java]
----
boolean hasStateStores()
----

Used when `AssignedTasks` is requested to:

* link:kafka-streams-AssignedTasks.adoc#transitionToRunning[Schedule a task for execution]

* link:kafka-streams-AssignedTasks.adoc#uninitializedPartitions[Get the partitions of the new tasks with a state store]

---

Implemented exclusively in link:kafka-streams-AbstractTask.adoc#hasStateStores[AbstractTask].

| id
a| [[id]]

[source, java]
----
TaskId id()
----

| initializeStateStores
a| [[initializeStateStores]]

[source, java]
----
boolean initializeStateStores()
----

Initializing <<kafka-streams-StateStore.adoc#, state stores>>

Enabled (`true`) if the task has no state stores that need restoring.

* `StandbyTask` always returns <<kafka-streams-StandbyTask.adoc#initializeStateStores, true>>

Used exclusively when `AssignedTasks` is requested to <<kafka-streams-AssignedTasks.adoc#initializeNewTasks, initializeNewTasks>>.

| initializeTopology
a| [[initializeTopology]]

[source, java]
----
void initializeTopology()
----

Used exclusively when `AssignedTasks` is requested to link:kafka-streams-AssignedTasks.adoc#transitionToRunning[schedule a task for execution]

| partitions
a| [[partitions]]

[source, java]
----
Set<TopicPartition> partitions()
----

| resume
a| [[resume]]

[source, java]
----
void resume()
----

| suspend
a| [[suspend]]

[source, java]
----
void suspend()
----

| topology
a| [[topology]]

[source, java]
----
ProcessorTopology topology()
----

| toString
a| [[toString]]

[source, java]
----
String toString(final String indent)
----
|===
