== [[AbstractStateManager]] AbstractStateManager -- Base State Manager

`AbstractStateManager` is the base implementation of the <<kafka-streams-internals-StateManager.adoc#, StateManager contract>> for <<implementations, state managers>> that use <<checkpoint, offset checkpointing>>.

NOTE: `AbstractStateManager` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete AbstractStateManagers>>.

[[CHECKPOINT_FILE_NAME]]
`AbstractStateManager` uses *.checkpoint* for the name of the <<checkpoint, checkpoint>> offset file.

[[implementations]]
.AbstractStateManagers
[cols="30,70",options="header",width="100%"]
|===
| AbstractStateManager
| Description

| <<kafka-streams-internals-GlobalStateManagerImpl.adoc#, GlobalStateManagerImpl>>
| [[GlobalStateManagerImpl]]

| <<kafka-streams-internals-ProcessorStateManager.adoc#, ProcessorStateManager>>
| [[ProcessorStateManager]]
|===

=== [[creating-instance]] Creating AbstractStateManager Instance

`AbstractStateManager` takes the following to be created:

* [[baseDir]] Base directory
* [[eosEnabled]] `eosEnabled` flag

`AbstractStateManager` initializes the <<internal-properties, internal properties>>.

NOTE: `AbstractStateManager` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete AbstractStateManagers>>.

=== [[reinitializeStateStoresForPartitions]] `reinitializeStateStoresForPartitions` Method

[source, java]
----
void reinitializeStateStoresForPartitions(
  Logger log,
  Map<String, StateStore> stateStores,
  Map<String, String> storeToChangelogTopic,
  Collection<TopicPartition> partitions,
  InternalProcessorContext processorContext)
----

`reinitializeStateStoresForPartitions`...FIXME

[NOTE]
====
`reinitializeStateStoresForPartitions` is used when:

* `GlobalStateManagerImpl` is requested to <<kafka-streams-internals-GlobalStateManagerImpl.adoc#reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>

* `ProcessorStateManager` is requested to <<kafka-streams-internals-ProcessorStateManager.adoc#reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>
====

==== [[inverseOneToOneMap]] `inverseOneToOneMap` Internal Method

[source, java]
----
Map<String, String> inverseOneToOneMap(Map<String, String> origin)
----

`inverseOneToOneMap`...FIXME

NOTE: `inverseOneToOneMap` is used exclusively when `AbstractStateManager` is requested to <<reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>.

=== [[converterForStore]] `converterForStore` Static Method

[source, java]
----
RecordConverter converterForStore(StateStore store)
----

`converterForStore`...FIXME

NOTE: `converterForStore` is used when...FIXME

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| checkpoint
a| [[checkpoint]] <<kafka-streams-internals-OffsetCheckpoint.adoc#, OffsetCheckpoint>> with the <<CHECKPOINT_FILE_NAME, .checkpoint>> file in the <<baseDir, base directory>>.

Initialized to a new <<kafka-streams-internals-OffsetCheckpoint.adoc#, OffsetCheckpoint>> when `AbstractStateManager` is <<creating-instance, created>>

Used when:

* `AbstractStateManager` is requested to <<reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>> (to write the <<checkpointableOffsets, checkpointableOffsets>> with <<eosEnabled, exactly-once support>> off)

* `GlobalStateManagerImpl` is requested to <<kafka-streams-internals-GlobalStateManagerImpl.adoc#initialize, initialize>> and <<kafka-streams-internals-GlobalStateManagerImpl.adoc#checkpoint, checkpoint>>

* `ProcessorStateManager` is <<kafka-streams-internals-ProcessorStateManager.adoc#, created>> and requested to <<kafka-streams-internals-ProcessorStateManager.adoc#checkpoint, checkpoint>>

| checkpointableOffsets
a| [[checkpointableOffsets]] Collection of Kafka https://kafka.apache.org/22/javadoc/index.html?org/apache/kafka/common/TopicPartition.html[TopicPartitions] with offsets (`Map<TopicPartition, Long>`)

Entries (partitions with offsets) added when:

* `GlobalStateManagerImpl` is requested to <<kafka-streams-internals-GlobalStateManagerImpl.adoc#initialize, initialize>>, <<kafka-streams-internals-GlobalStateManagerImpl.adoc#restoreState, restoreState>> and <<kafka-streams-internals-GlobalStateManagerImpl.adoc#checkpoint, checkpoint>>

* `ProcessorStateManager` is <<kafka-streams-internals-ProcessorStateManager.adoc#, created>> and requested to <<kafka-streams-internals-ProcessorStateManager.adoc#checkpoint, checkpoint>>

| globalStores
a| [[globalStores]] Global <<kafka-streams-StateStore.adoc#, state stores>> by name (managed by <<kafka-streams-internals-GlobalStateManagerImpl.adoc#, GlobalStateManagerImpl>> _mostly_)

New state stores added when:

* `GlobalStateManagerImpl` is requested to <<kafka-streams-internals-GlobalStateManagerImpl.adoc#register, register a state store>>

* `ProcessorStateManager` is requested to <<kafka-streams-internals-ProcessorStateManager.adoc#registerGlobalStateStores, registerGlobalStateStores>>

State stores removed when:

* `GlobalStateManagerImpl` is requested to <<kafka-streams-internals-GlobalStateManagerImpl.adoc#close, close>>

| stores
a| [[stores]] <<kafka-streams-StateStore.adoc#, State stores>> by name (managed by <<kafka-streams-internals-ProcessorStateManager.adoc#, ProcessorStateManager>>)

New state stores added when:

* `ProcessorStateManager` is requested to <<kafka-streams-internals-ProcessorStateManager.adoc#register, register a state store>>

State stores removed when:

* `ProcessorStateManager` is requested to <<kafka-streams-internals-ProcessorStateManager.adoc#close, close>>
|===
