== [[ProcessorContextImpl]] ProcessorContextImpl

`ProcessorContextImpl` is a concrete <<kafka-streams-internals-AbstractProcessorContext.adoc#, AbstractProcessorContext>> that is <<creating-instance, created>> exclusively for a <<kafka-streams-internals-StreamTask.adoc#processorContext, StreamTask>>.

[[recordCollector]]
`ProcessorContextImpl` is a concrete <<kafka-streams-internals-RecordCollector.adoc#Supplier, RecordCollector.Supplier>> that supplies the given <<collector, RecordCollector>> when <<kafka-streams-internals-RecordCollector.adoc#recordCollector, requested>>.

=== [[getStateStore]] Accessing State Store by Name -- `getStateStore` Method

[source, scala]
----
StateStore getStateStore(final String name)
----

NOTE: `getStateStore` is part of link:kafka-streams-ProcessorContext.adoc#getStateStore[ProcessorContext Contract] to access the <<kafka-streams-StateStore.adoc#, state store>> by name.

`getStateStore`...FIXME

=== [[schedule]] `schedule` Method

[source, java]
----
Cancellable schedule(final long interval, final PunctuationType type, final Punctuator callback)
----

NOTE: `schedule` is part of link:kafka-streams-ProcessorContext.adoc#schedule[ProcessorContext Contract] to...FIXME.

`schedule`...FIXME

=== [[creating-instance]] Creating ProcessorContextImpl Instance

`ProcessorContextImpl` takes the following when created:

* [[id]] <<kafka-streams-TaskId.adoc#, TaskId>>
* [[task]] <<kafka-streams-internals-StreamTask.adoc#, StreamTask>>
* [[config]] <<kafka-streams-StreamsConfig.adoc#, StreamsConfig>>
* [[collector]] <<kafka-streams-internals-RecordCollector.adoc#, RecordCollector>>
* [[stateMgr]] <<kafka-streams-ProcessorStateManager.adoc#, ProcessorStateManager>>
* [[metrics]] <<kafka-streams-internals-StreamsMetricsImpl.adoc#, StreamsMetricsImpl>>
* [[cache]] <<kafka-streams-internals-ThreadCache.adoc#, ThreadCache>>

`ProcessorContextImpl` initializes the <<internal-registries, internal registries and counters>>.

=== [[forward]] `forward` Method

[source, scala]
----
void forward(final K key, final V value)
void forward(final K key, final V value, final int childIndex)
void forward(final K key, final V value, final String childName)
void forward(final K key, final V value, final To to)
void forward(
  final ProcessorNode child,
  final K key,
  final V value) // <1>
----
<1> Private API

NOTE: `forward` is part of the <<kafka-streams-ProcessorContext.adoc#forward, ProcessorContext Contract>> to...FIXME.

`forward`...FIXME
