== [[RecordCollector]] RecordCollector Contract

`RecordCollector` is the <<contract, contract>> of <<implementations, record collectors>> that <<FIXME, FIXME>>.

[[contract]]
.RecordCollector Contract
[cols="1m,3",options="header",width="100%"]
|===
| Method
| Description

| close
a| [[close]]

[source, java]
----
void close()
----

Closes the `RecordCollector`

Used when...FIXME

| flush
a| [[flush]]

[source, java]
----
void flush()
----

Flushing the internal Kafka producer

Used exclusively when `StreamTask` is requested to <<kafka-streams-internals-StreamTask.adoc#flushState, flush state stores and the internal Kafka producer>>

| init
a| [[init]]

[source, java]
----
void init(final Producer<byte[], byte[]> producer)
----

Initializes the `RecordCollector` (with a specified Kafka `Producer`)

Used when `StreamTask` is <<kafka-streams-internals-StreamTask.adoc#, created>> and <<kafka-streams-internals-StreamTask.adoc#resume, resumed>>

| offsets
a| [[offsets]]

[source, java]
----
Map<TopicPartition, Long> offsets()
----

Used exclusively when `StreamTask` is requested to <<kafka-streams-internals-StreamTask.adoc#activeTaskCheckpointableOffsets, activeTaskCheckpointableOffsets>>

| send
a| [[send]]

[source, java]
----
<K, V> void send(
  final String topic,
  final K key,
  final V value,
  final Headers headers,
  final Integer partition,
  final Long timestamp,
  final Serializer<K> keySerializer,
  final Serializer<V> valueSerializer)
<K, V> void send(
  final String topic,
  final K key,
  final V value,
  final Headers headers,
  final Long timestamp,
  final Serializer<K> keySerializer,
  final Serializer<V> valueSerializer,
  final StreamPartitioner<? super K, ? super V> partitioner)
----

Used when:

* `RecordCollectorImpl` is requested to <<kafka-streams-internals-RecordCollectorImpl.adoc#send, send a record>>

* `InMemoryTimeOrderedKeyValueBuffer` is requested to `flush`

* `StoreChangeLogger` is requested to <<kafka-streams-StoreChangeLogger.adoc#logChange, logChange>>

* `SinkNode` is requested to <<kafka-streams-internals-SinkNode.adoc#process, process a record>>

|===

[[implementations]]
.RecordCollectors
[cols="30m,70",options="header",width="100%"]
|===
| RecordCollector
| Description

| <<kafka-streams-internals-StandbyContextImpl.adoc#NO_OP_COLLECTOR, NO_OP_COLLECTOR>>
| [[NO_OP_COLLECTOR]]

| <<kafka-streams-internals-RecordCollectorImpl.adoc#, RecordCollectorImpl>>
| [[RecordCollectorImpl]]

|===
