== [[AssignedStreamsTasks]] AssignedStreamsTasks

`AssignedStreamsTasks` is...FIXME

It _appears_ that `AssignedStreamsTasks` simply operates on the running tasks (i.e. the tasks that are in link:kafka-streams-AssignedTasks.adoc#running[running] internal registry). When requested to <<process, process>> or <<punctuate, punctuate>> `AssignedStreamsTasks` simply walks over the `running` internal registry and triggers execution of every task.

[[logging]]
[TIP]
====
Enable any of `ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE` logging levels for `org.apache.kafka.streams.processor.internals.AssignedStreamsTasks` logger to see what happens inside.

Add the following line to `log4j.properties`:

```
log4j.logger.org.apache.kafka.streams.processor.internals.AssignedStreamsTasks=TRACE
```

Refer to link:kafka-logging.adoc#log4j.properties[Application Logging Using log4j].
====

=== [[punctuate]] `punctuate` Method

[source, java]
----
int punctuate()
----

`punctuate`...FIXME

NOTE: `punctuate` is used when...FIXME

=== [[process]] Requesting Stream Tasks to Process Single Record -- `process` Method

[source, java]
----
int process()
----

`process` requests every stream task (from link:kafka-streams-AssignedTasks.adoc#running[running]) to link:kafka-streams-StreamTask.adoc#process[process a single record].

In the end, `process` gives the number of stream tasks that processed a single record successfully.

NOTE: `process` is used exclusively when `TaskManager` is requested to link:kafka-streams-TaskManager.adoc#process[process records].

==== [[process-TaskMigratedException]] process and TaskMigratedException

In case of a `TaskMigratedException`, `process` prints out the following INFO message to the logs:

```
Failed to process stream task [id] since it got migrated to another thread already. Closing it as zombie before triggering a new rebalance.
```

`process` then link:kafka-streams-AssignedTasks.adoc#closeZombieTask[closes the task] (considering the task a zombie). If this reports a `RuntimeException`, `process` re-throws it.

`process` removes the task from link:kafka-streams-AssignedTasks.adoc#running[running] and throws the `TaskMigratedException`.

==== [[process-RuntimeException]] process and RuntimeException

In case of a `RuntimeException`, `process` prints out the following ERROR message to the logs followed by the exception.

```
Failed to process stream task [id] due to the following error:
```

`process` re-throws the `RuntimeException`.
