== [[KStreamImpl]] KStreamImpl

`KStreamImpl` is the concrete link:kafka-streams-KStream.adoc[KStream].

`KStreamImpl` is <<creating-instance, created>> when...FIXME

[[internal-registries]]
.KStreamImpl's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[defaultKeyValueMapper]] `defaultKeyValueMapper`
| link:kafka-streams-KeyValueMapper.adoc[KeyValueMapper]
|===

=== [[mapValues]] Creating New Processor with KStreamMapValues Processor Supplier (with KSTREAM-MAPVALUES Prefix) -- `mapValues` Operator

[source, java]
----
<V1> KStream<K, V1> mapValues(final ValueMapper<? super V, ? extends V1> mapper)
----

NOTE: `mapValues` is a part of link:kafka-streams-KStream.adoc#mapValues[KStream Contract] to...FIXME.

`mapValues` creates a new `KStreamImpl` for a new processor (with the current <<builder, InternalStreamsBuilder>>, <<sourceNodes, source nodes>> and <<repartitionRequired, repartitionRequired>> flag).

Internally, `mapValues` requests <<builder, InternalStreamsBuilder>> for a new processor name with *KSTREAM-MAPVALUES-* prefix and link:kafka-streams-InternalTopologyBuilder.adoc#addProcessor[registers] a `KStreamMapValues` processor supplier under the name.

NOTE: `mapValues` uses <<builder, InternalStreamsBuilder>> to access the current link:kafka-streams-InternalStreamsBuilder.adoc#internalTopologyBuilder[InternalTopologyBuilder].

=== [[createReparitionedSource]] `createReparitionedSource` Method

[source, java]
----
String createReparitionedSource(
  final InternalStreamsBuilder builder,
  final Serde<K1> keySerde,
  final Serde<V1> valSerde,
  final String topicNamePrefix,
  final String name)
----

`createReparitionedSource`...FIXME

NOTE: `createReparitionedSource` is used when...FIXME

=== [[creating-instance]] Creating KStreamImpl Instance

`KStreamImpl` takes the following when created:

* [[builder]] link:kafka-streams-InternalStreamsBuilder.adoc[InternalStreamsBuilder] that created the `KStreamImpl`
* [[name]] Name of the stream processor node
* [[sourceNodes]] Source nodes
* [[repartitionRequired]] Flag whether repartitioning is required or not

`KStreamImpl` initializes the <<internal-registries, internal registries and counters>>.
