== [[KGroupedStreamImpl]] KGroupedStreamImpl

`KGroupedStreamImpl` is a concrete link:kafka-streams-AbstractStream.adoc[AbstractStream] and a link:kafka-streams-KGroupedStream.adoc[KGroupedStream].

=== [[aggregate]] `aggregate` Method

[source, java]
----
KTable<K, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator)
KTable<K, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator,
  final Materialized<K, VR, KeyValueStore<Bytes, byte[]>> materialized)
----

NOTE: `aggregate` is part of link:kafka-streams-KGroupedStream.adoc#aggregate[KGroupedStream Contract] to...FIXME.

`aggregate`...FIXME

=== [[reduce]] `reduce` Method

[source, java]
----
KTable<K, V> reduce(final Reducer<V> reducer)
KTable<K, V> reduce(
  final Reducer<V> reducer,
  final Materialized<K, V, KeyValueStore<Bytes, byte[]>> materialized)
----

NOTE: `reduce` is part of link:kafka-streams-KGroupedStream.adoc#reduce[KGroupedStream Contract] to...FIXME.

`reduce`...FIXME

=== [[windowedBy]] `windowedBy` Method

[source, java]
----
SessionWindowedKStream<K, V> windowedBy(final SessionWindows windows)
TimeWindowedKStream<K, V> windowedBy(final Windows<W> windows)
----

NOTE: `windowedBy` is part of link:kafka-streams-KGroupedStream.adoc#windowedBy[KGroupedStream Contract] to...FIXME.

`windowedBy`...FIXME

=== [[doAggregate]] Building KTable -- `doAggregate` Internal Method

[source, java]
----
KTable<K, T> doAggregate(
  final KStreamAggProcessorSupplier<K, ?, V, T> aggregateSupplier,
  final String functionName,
  final MaterializedInternal<K, T, KeyValueStore<Bytes, byte[]>> materializedInternal)
----

`doAggregate`...FIXME

NOTE: `doAggregate` is used when `KGroupedStreamImpl` is requested to <<reduce, reduce>>, <<aggregate, aggregate>> and <<doCount, doCount>>.

=== [[doCount]] `doCount` Internal Method

[source, java]
----
KTable<K, Long> doCount(final Materialized<K, Long, KeyValueStore<Bytes, byte[]>> materialized)
----

`doCount`...FIXME

NOTE: `doCount` is used exclusively when `KGroupedStreamImpl` is requested to <<count, count>>.

=== [[count]] `count` Method

[source, java]
----
KTable<K, Long> count()
KTable<K, Long> count(final Materialized<K, Long, KeyValueStore<Bytes, byte[]>> materialized)
----

NOTE: `count` is part of the <<kafka-streams-KGroupedStream.adoc#count, KGroupedStream Contract>> to...FIXME.

`count`...FIXME
