== [[StreamsGraphNode]] StreamsGraphNode

`StreamsGraphNode` is the <<contract, abstraction>> of <<implementations, graph nodes>> that can <<writeToTopology, writeToTopology>>.

[[contract]]
[[writeToTopology]]
[source, java]
----
void writeToTopology(final InternalTopologyBuilder topologyBuilder)
----

`StreamsGraphNode` is used exclusively in <<kafka-streams-internals-InternalStreamsBuilder.adoc#root, InternalStreamsBuilder>> (to <<kafka-streams-internals-InternalStreamsBuilder.adoc#buildAndOptimizeTopology, build a topology>>).

[[creating-instance]]
`StreamsGraphNode` takes the following when created:

* [[nodeName]] *Name* of the node
* [[repartitionRequired]] *repartitionRequired* flag

NOTE: `StreamsGraphNode` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete StreamsGraphNodes>> and as the <<kafka-streams-internals-InternalStreamsBuilder.adoc#root, root node of an InternalStreamsBuilder>>.

[[implementations]]
.StreamsGraphNodes (Direct Implementations)
[cols="1,2",options="header",width="100%"]
|===
| StreamsGraphNode
| Description

| BaseJoinProcessorNode
| [[BaseJoinProcessorNode]]

| BaseRepartitionNode
| [[BaseRepartitionNode]]

| ProcessorGraphNode
| [[ProcessorGraphNode]]

| StateStoreNode
| [[StateStoreNode]]

| StreamSinkNode
| [[StreamSinkNode]]

| <<kafka-streams-internals-StreamSourceNode.adoc#, StreamSourceNode>>
| [[StreamSourceNode]]

| StreamTableJoinNode
| [[StreamTableJoinNode]]

| TableProcessorNode
| [[TableProcessorNode]]

|===
