== [[Stores]] Stores

`Stores` is...FIXME

=== [[create]] Creating StoreFactory -- `create` Method

[source, java]
----
static StoreFactory create(final String name)
----

NOTE: `create` is a deprecated method and may disappear at any major release of Kafka Streams. You should use...FIXME...instead.

`create`...FIXME

NOTE: `create` is used when...FIXME

=== [[sessionStoreBuilder]] `sessionStoreBuilder` Static Method

[source, java]
----
StoreBuilder<SessionStore<K, V>> sessionStoreBuilder(
  final SessionBytesStoreSupplier supplier,
  final Serde<K> keySerde,
  final Serde<V> valueSerde)
----

`sessionStoreBuilder` simply returns a new link:kafka-streams-SessionStoreBuilder.adoc#creating-instance[SessionStoreBuilder] (for the input arguments and `Time.SYSTEM`).

In case the input link:kafka-streams-SessionBytesStoreSupplier.adoc[SessionBytesStoreSupplier] is undefined (`null`), `sessionStoreBuilder` throws a `NullPointerException`.

NOTE: `sessionStoreBuilder` is used when `SessionWindowedKStreamImpl` is requested to link:kafka-streams-SessionWindowedKStreamImpl.adoc#materialize[materialize] and link:kafka-streams-SessionWindowedKStreamImpl.adoc#storeBuilder[storeBuilder].

=== [[windowStoreBuilder]] `windowStoreBuilder` Static Method

[source, java]
----
StoreBuilder<WindowStore<K, V>> windowStoreBuilder(
  final WindowBytesStoreSupplier supplier,
  final Serde<K> keySerde,
  final Serde<V> valueSerde)
----

`windowStoreBuilder`...FIXME

[NOTE]
====
`windowStoreBuilder` is used when:

* `KStreamImpl` is requested to <<kafka-streams-KStreamImpl.adoc#createWindowedStateStore, createWindowedStateStore>>

* `TimeWindowedKStreamImpl` is requested to <<kafka-streams-TimeWindowedKStreamImpl.adoc#materialize, create a StoreBuilder (of WindowStores)>>
====
