== [[Consumed]] Consumed -- Metadata for Consuming Streams

[[creating-instance]]
`Consumed` provides the optional parameters that describe how to consume streams in the <<kafka-streams-StreamsBuilder.adoc#, High-Level Stream Processing DSL>>:

* [[keySerde]] *Key Serde* (Apache Kafka's https://kafka.apache.org/22/javadoc/org/apache/kafka/common/serialization/Serde.html[Serde] for record keys)
* [[valueSerde]] *Value Serde* (Apache Kafka's https://kafka.apache.org/22/javadoc/org/apache/kafka/common/serialization/Serde.html[Serde] for record values)
* [[timestampExtractor]] <<kafka-streams-TimestampExtractor.adoc#, TimestampExtractor>>
* [[resetPolicy]] *Offset reset policy* (<<kafka-streams-Topology.adoc#, Topology.AutoOffsetReset>>)

`Consumed` is used as an optional parameter in the following `StreamsBuilder` operators:

* <<kafka-streams-StreamsBuilder.adoc#stream, StreamsBuilder.stream>>

* <<kafka-streams-StreamsBuilder.adoc#table, StreamsBuilder.table>>

* <<kafka-streams-StreamsBuilder.adoc#globalTable, StreamsBuilder.globalTable>>

* <<kafka-streams-StreamsBuilder.adoc#addGlobalStore, StreamsBuilder.addGlobalStore>>

A `Consumed` instance is <<creating-instance, created>> using one of the available <<with, with>> factory methods.

[[with]]
[source, java]
----
Consumed<K, V> with(
  final Serde<K> keySerde,
  final Serde<V> valueSerde)
Consumed<K, V> with(final TimestampExtractor timestampExtractor)
Consumed<K, V> with(final Topology.AutoOffsetReset resetPolicy)
Consumed<K, V> with(
  final Serde<K> keySerde,
  final Serde<V> valueSerde,
  final TimestampExtractor timestampExtractor,
  final Topology.AutoOffsetReset resetPolicy)
----

A `Consumed` instance can futher be configured using the <<methods, "with" methods>>.

[[methods]]
.Consumed's "with" Methods
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| withKeySerde
a| [[withKeySerde]]

[source, java]
----
Consumed<K, V> withKeySerde(final Serde<K> keySerde)
----

| withOffsetResetPolicy
a| [[withOffsetResetPolicy]]

[source, java]
----
Consumed<K, V> withOffsetResetPolicy(
  final Topology.AutoOffsetReset resetPolicy)
----

| withTimestampExtractor
a| [[withTimestampExtractor]]

[source, java]
----
Consumed<K, V> withTimestampExtractor(
  final TimestampExtractor timestampExtractor)
----

| withValueSerde
a| [[withValueSerde]]

[source, java]
----
Consumed<K, V> withValueSerde(final Serde<V> valueSerde)
----
|===

=== Scala API for Kafka Streams

<<kafka-streams-scala.adoc#, Scala API for Kafka Streams>> makes the optional `Consumed` metadata an implicit parameter in the `StreamsBuilder` API.

Moreover, <<kafka-streams-scala-ImplicitConversions.adoc#, ImplicitConversions>> object defines <<kafka-streams-scala-ImplicitConversions.adoc#consumedFromSerde, consumedFromSerde>> implicit method that creates a `Consumed` instance with the key and value `Serde` objects available in implicit scope.

And the last but not least, Scala API for Kafka Streams defines <<kafka-streams-scala-Consumed.adoc#, Consumed>> object with `++`with`++` factory methods that use implicit key and value `Serde` objects.
