== [[NodeFactory]] NodeFactory

`NodeFactory` is the internal <<contract, contract>> for...FIXME

[[name]]
[[predecessors]]
`NodeFactory` has a *name* and zero, one or more *predecessors*.

[[contract]]
[source, java]
----
package org.apache.kafka.streams.processor.internals;

abstract class NodeFactory {
  ProcessorNode build();
  AbstractNode describe();
}
----

NOTE: `NodeFactory` is a `private` and `static` contract in link:kafka-streams-InternalTopologyBuilder.adoc[InternalTopologyBuilder].

.NodeFactory Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[build]] `build`
| Building a link:kafka-streams-internals-ProcessorNode.adoc[processor node]

Used exclusively when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#build[build a topology of processor tasks] (aka *processor topology*) for specified node groups.

| [[describe]] `describe`
| Used exclusively when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#describeSubtopology[describeSubtopology] (which is when requested to link:kafka-streams-InternalTopologyBuilder.adoc#describe[describe]).
|===

[[implementations]]
.NodeFactories
[cols="1,2",options="header",width="100%"]
|===
| NodeFactory
| Description

| link:kafka-streams-ProcessorNodeFactory.adoc[ProcessorNodeFactory]
|

| `SinkNodeFactory`
|

| link:kafka-streams-SourceNodeFactory.adoc[SourceNodeFactory]
|
|===
