== [[Stores]] Stores -- Factory of State Stores

`Stores` is a <<methods, factory for creating state stores>> (using <<kafka-streams-StoreSupplier.adoc#, StoreSuppliers>> for <<kafka-streams-StreamsBuilder.adoc#, StreamsBuilder>> or <<kafka-streams-StoreBuilder.adoc#, StoreBuilders>> for <<kafka-streams-Topology.adoc#, Topology>>).

[source, scala]
----
import org.apache.kafka.streams.state.Stores
val kvStore = Stores.inMemoryKeyValueStore("store-name")

scala> :type kvStore
org.apache.kafka.streams.state.KeyValueBytesStoreSupplier
----

[[methods]]
.Stores API (Static Methods)
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| inMemoryKeyValueStore
a| [[inMemoryKeyValueStore]]

[source, java]
----
KeyValueBytesStoreSupplier inMemoryKeyValueStore(final String name)
----

Creates a <<kafka-streams-KeyValueBytesStoreSupplier.adoc#, KeyValueBytesStoreSupplier>> (that creates <<kafka-streams-StateStore-KeyValueStore.adoc#, KeyValueStores>>)

| keyValueStoreBuilder
a| [[keyValueStoreBuilder]]

[source, java]
----
StoreBuilder<KeyValueStore<K, V>> keyValueStoreBuilder(
  final KeyValueBytesStoreSupplier supplier,
  final Serde<K> keySerde,
  final Serde<V> valueSerde)
----

Creates a <<kafka-streams-internals-KeyValueStoreBuilder.adoc#, KeyValueStoreBuilder>> (that creates <<kafka-streams-StateStore-KeyValueStore.adoc#, KeyValueStores>>)

| lruMap
a| [[lruMap]]

[source, java]
----
KeyValueBytesStoreSupplier lruMap(
  final String name,
  final int maxCacheSize)
----

Creates a <<kafka-streams-KeyValueBytesStoreSupplier.adoc#, KeyValueBytesStoreSupplier>> (that creates `MemoryNavigableLRUCaches` with `maxCacheSize`)

| persistentKeyValueStore
a| [[persistentKeyValueStore]]

[source, java]
----
KeyValueBytesStoreSupplier persistentKeyValueStore(final String name)
----

Creates a `RocksDbKeyValueBytesStoreSupplier`

| persistentSessionStore
a| [[persistentSessionStore]]

[source, java]
----
SessionBytesStoreSupplier persistentSessionStore(
  final String name,
  final Duration retentionPeriod)
----

Creates a `RocksDbSessionBytesStoreSupplier` (with `retentionPeriod`)

| persistentWindowStore
a| [[persistentWindowStore]]

[source, java]
----
WindowBytesStoreSupplier persistentWindowStore(
  final String name,
  final Duration retentionPeriod,
  final Duration windowSize,
  final boolean retainDuplicates)
----

Creates a <<kafka-streams-WindowBytesStoreSupplier.adoc#, WindowBytesStoreSupplier>> (i.e. <<kafka-streams-internals-RocksDbWindowBytesStoreSupplier.adoc#, RocksDbWindowBytesStoreSupplier>>)

| sessionStoreBuilder
a| [[sessionStoreBuilder]]

[source, java]
----
StoreBuilder<SessionStore<K, V>> sessionStoreBuilder(
  final SessionBytesStoreSupplier supplier,
  final Serde<K> keySerde,
  final Serde<V> valueSerde)
----

Creates a <<kafka-streams-StoreBuilder.adoc#, StoreBuilder>> of <<kafka-streams-StateStore-SessionStore.adoc#, SessionStores>> (i.e. a <<kafka-streams-internals-SessionStoreBuilder.adoc#, SessionStoreBuilder>>)

| windowStoreBuilder
a| [[windowStoreBuilder]]

[source, java]
----
StoreBuilder<WindowStore<K, V>> windowStoreBuilder(
  final WindowBytesStoreSupplier supplier,
  final Serde<K> keySerde,
  final Serde<V> valueSerde)
----

Creates a <<kafka-streams-StoreBuilder.adoc#, StoreBuilder>> of <<kafka-streams-StateStore-WindowStore.adoc#, WindowStores>> (i.e. a <<kafka-streams-internals-WindowStoreBuilder.adoc#, WindowStoreBuilder>>)

|===
