== [[SinkNode]] SinkNode

`SinkNode` is a link:kafka-streams-ProcessorNode.adoc[ProcessorNode] with no <<addChild, child processor nodes>>.

`SinkNode` is <<creating-instance, created>> exclusively when `SinkNodeFactory` is requested to link:kafka-streams-SinkNodeFactory.adoc#build[build a processor node] (when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#build[build a processor task topology] for specified node groups).

=== [[process]] `process` Method

[source, java]
----
void process(final K key, final V value)
----

NOTE: `process` is part of link:kafka-streams-ProcessorNode.adoc#process[ProcessorNode Contract] to...FIXME.

`process`...FIXME

=== [[creating-instance]] Creating SinkNode Instance

`SinkNode` takes the following when created:

* [[name]] Name of the sink (topic)
* [[topic]] Name of the topic
* [[keySerializer]] Key `Serializer`
* [[valSerializer]] Value `Serializer`
* [[partitioner]] link:kafka-streams-StreamPartitioner.adoc[StreamPartitioner]

=== [[addChild]] Adding Child Processor Node -- `addChild` Method

[source, java]
----
void addChild(final ProcessorNode<?, ?> child)
----

NOTE: `addChild` is part of link:kafka-streams-ProcessorNode.adoc#addChild[ProcessorNode Contract] to...FIXME.

`addChild` simply throws an `UnsupportedOperationException` with the following message:

```
sink node does not allow addChild
```

=== [[init]] Initializing Processor Node -- `init` Method

[source, java]
----
void init(final ProcessorContext context)
----

NOTE: `init` is part of link:kafka-streams-ProcessorNode.adoc#init[ProcessorNode Contract] to...FIXME.

`init`...FIXME

=== [[toString]] Describing Itself (Textual Representation) -- `toString` Method

[source, java]
----
void toString(final ProcessorContext context)
----

NOTE: `toString` is part of link:kafka-streams-ProcessorNode.adoc#toString[ProcessorNode Contract] for the human-friendly / textual representation of a `ProcessorNode`.

`toString`...FIXME
