== [[StateManager]] StateManager

`StateManager` is the <<contract, contract>> for...FIXME

`StateManager` is a <<kafka-streams-Checkpointable.adoc#, Checkpointable>> that...FIXME

[[contract]]
.StateManager Contract
[cols="1a,2",options="header",width="100%"]
|===
| Method
| Description

| baseDir
a| [[baseDir]]

[source, java]
----
File baseDir()
----

Used when...FIXME

| close
a| [[close]]

[source, java]
----
void close(final Map<TopicPartition, Long> offsets) throws IOException
----

Closes a state manager

Used when:

* `AbstractTask` is requested to link:kafka-streams-AbstractTask.adoc#closeStateManager[closeStateManager]
* `GlobalStateUpdateTask` is requested to link:kafka-streams-GlobalStateUpdateTask.adoc#close[close]

| flush
a| [[flush]]

[source, java]
----
void flush()
----

Flushes all <<kafka-streams-StateStore.adoc#, state stores>> registered with the state manager

Used when...FIXME

| getGlobalStore
a| [[getGlobalStore]]

[source, java]
----
StateStore getGlobalStore(final String name)
----

Used when...FIXME

| getStore
a| [[getStore]]

[source, java]
----
StateStore getStore(final String name)
----

Used when...FIXME

| register
a| [[register]]

[source, java]
----
void register(final StateStore store, final StateRestoreCallback stateRestoreCallback)
----

Registering a <<kafka-streams-StateStore.adoc#, StateStore>> and the associated `StateRestoreCallback`

Used when...FIXME

| reinitializeStateStoresForPartitions
a| [[reinitializeStateStoresForPartitions]]

[source, java]
----
void reinitializeStateStoresForPartitions(
  final Collection<TopicPartition> partitions,
  final InternalProcessorContext processorContext)
----

Used when...FIXME
|===

[[implementations]]
.StateManagers
[cols="1,2",options="header",width="100%"]
|===
| StateManager
| Description

| link:kafka-streams-AbstractStateManager.adoc[AbstractStateManager]
| [[AbstractStateManager]]

| link:kafka-streams-GlobalStateManager.adoc[GlobalStateManager]
| [[GlobalStateManager]]
|===
