== [[StandbyTaskCreator]] StandbyTaskCreator -- Factory of Standby Tasks

`StandbyTaskCreator` is a concrete <<kafka-streams-AbstractTaskCreator.adoc, AbstractTaskCreator>> of <<createTask, standby tasks>>.

`StandbyTaskCreator` is <<creating-instance, created>> exclusively when `StreamThread` is link:kafka-streams-StreamThread.adoc#create[created] (just to create a link:kafka-streams-TaskManager.adoc#standbyTaskCreator[TaskManager]).

=== [[createTask]] Creating Standby Task -- `createTask` Factory Method

[source, java]
----
StandbyTask createTask(
  final Consumer<byte[], byte[]> consumer,
  final TaskId taskId,
  final Set<TopicPartition> partitions)
----

NOTE: `createTask` is part of link:kafka-streams-AbstractTaskCreator.adoc#createTask[AbstractTaskCreator Contract] to create concrete link:kafka-streams-internals-AbstractTask.adoc[stream processor tasks].

`createTask`...FIXME

NOTE: `createTask` is used when...FIXME

=== [[creating-instance]] Creating StandbyTaskCreator Instance

`StandbyTaskCreator` takes the following when created:

* [[builder]] link:kafka-streams-internals-InternalTopologyBuilder.adoc[InternalTopologyBuilder]
* [[config]] link:kafka-streams-StreamsConfig.adoc[StreamsConfig]
* [[streamsMetrics]] link:kafka-streams-StreamsMetrics.adoc[StreamsMetrics]
* [[stateDirectory]] link:kafka-streams-internals-StateDirectory.adoc[StateDirectory]
* [[taskCreatedSensor]] `Sensor`
* [[storeChangelogReader]] <<kafka-streams-ChangelogReader.adoc#, ChangelogReader>>
* [[time]] `Time`
* [[log]] `Logger`
