== [[AbstractTask]] AbstractTask -- Base Processor Task

`AbstractTask` is the base implementation of the <<kafka-streams-Task.adoc#, Task contract>> for <<implementations, tasks>> that <<FIXME, FIXME>>.

NOTE: `AbstractTask` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete AbstractTasks>>.

[[eosEnabled]]
`AbstractTask` uses link:kafka-streams-properties.adoc#processing.guarantee[processing.guarantee] configuration property to enable link:kafka-streams-exactly-once-support-eos.adoc[Exactly-Once Support] for...FIXME

[[taskInitialized]]
`AbstractTask` has `taskInitialized` flag that is on (i.e. `true`) to mark when:

* `StandbyTask` has finished link:kafka-streams-StandbyTask.adoc#initializeStateStores[initializeStateStores] successfully

* `StreamTask` has finished link:kafka-streams-StreamTask.adoc#initializeTopology[initializeTopology]

The `taskInitialized` flag is used by the <<implementations, concrete AbstractTasks>> as an optimization when:

* `StandbyTask` is requested to link:kafka-streams-StandbyTask.adoc#close[close]

* `StreamTask` is requested to link:kafka-streams-StreamTask.adoc#closeTopology[closeTopology]

[[taskClosed]]
`AbstractTask` has `taskClosed` flag that is on (i.e. `true`) to mark when <<kafka-streams-StandbyTask.adoc#close, StandbyTask>> and <<kafka-streams-StreamTask.adoc#close, StreamTask>> have already been requested to close.

[[implementations]]
.AbstractTasks
[cols="1,2",options="header",width="100%"]
|===
| AbstractTask
| Description

| <<kafka-streams-StandbyTask.adoc#, StandbyTask>>
| [[StandbyTask]]

| <<kafka-streams-StreamTask.adoc#, StreamTask>>
| [[StreamTask]]
|===

[[internal-registries]]
.AbstractTask's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| processorContext
a| [[processorContext]] <<kafka-streams-internals-InternalProcessorContext.adoc#, InternalProcessorContext>>, i.e.

* <<kafka-streams-ProcessorContextImpl.adoc#, ProcessorContextImpl>> for <<kafka-streams-StreamTask.adoc#, StreamTask>>

* <<kafka-streams-StandbyContextImpl.adoc#, StandbyContextImpl>> for <<kafka-streams-StandbyTask.adoc#, StandbyTask>>

| stateMgr
a| [[stateMgr]] <<kafka-streams-ProcessorStateManager.adoc#, ProcessorStateManager>>

<<kafka-streams-ProcessorStateManager.adoc#creating-instance, Created>> when `AbstractTask` is <<creating-instance, created>>

Used when:

* `AbstractTask` is requested to <<getStore, getStore>>, <<updateOffsetLimits, updateOffsetLimits>>, <<flushState, flushState>>, <<reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>, <<closeStateManager, closeStateManager>> and <<changelogPartitions, changelogPartitions>>

* `StandbyTask` is <<kafka-streams-StandbyTask.adoc#creating-instance, created>> (and creates the <<processorContext, InternalProcessorContext>>), and is requested to <<kafka-streams-StandbyTask.adoc#initializeStateStores, initializeStateStores>>, <<kafka-streams-StandbyTask.adoc#flushAndCheckpointState, flushAndCheckpointState>> and <<kafka-streams-StandbyTask.adoc#update, update>>

* `StreamTask` is <<kafka-streams-StreamTask.adoc#creating-instance, created>> (and creates the <<processorContext, InternalProcessorContext>>), and is requested to <<kafka-streams-StreamTask.adoc#commit, commit>> and <<kafka-streams-StreamTask.adoc#commitOffsets, commitOffsets>>
|===

=== [[closeStateManager]] Closing State Manager -- `closeStateManager` Method

[source, java]
----
void closeStateManager(final boolean writeCheckpoint) throws ProcessorStateException
----

`closeStateManager`...FIXME

NOTE: `closeStateManager` is used when...FIXME

=== [[creating-instance]] Creating AbstractTask Instance

`AbstractTask` takes the following when created:

* [[id]] `TaskId`
* [[partitions]] Assigned Kafka https://kafka.apache.org/20/javadoc/org/apache/kafka/common/TopicPartition.html[TopicPartitions]
* [[topology]] <<kafka-streams-ProcessorTopology.adoc#, ProcessorTopology>>
* [[consumer]] Kafka https://kafka.apache.org/20/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html[Consumer] (`Consumer<byte[], byte[]>`)
* [[changelogReader]] <<kafka-streams-ChangelogReader.adoc#, ChangelogReader>>
* [[isStandby]] `isStandby` flag
* [[stateDirectory]] <<kafka-streams-internals-StateDirectory.adoc#, StateDirectory>>
* [[config]] <<kafka-streams-StreamsConfig.adoc#, StreamsConfig>>

`AbstractTask` initializes the <<internal-registries, internal registries and counters>>.

NOTE: `AbstractTask` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete AbstractTasks>>.

=== [[hasStateStores]] Checking If Topology Uses State Stores -- `hasStateStores` Method

[source, java]
----
boolean hasStateStores()
----

NOTE: `hasStateStores` is part of link:kafka-streams-Task.adoc#hasStateStores[Task Contract] to...FIXME.

`hasStateStores` is positive (and returns `true`) when <<topology, ProcessorTopology>> has at least one link:kafka-streams-ProcessorTopology.adoc#stateStores[local state store].

=== [[flushState]] Flushing All State Stores -- `flushState` Method

[source, java]
----
void flushState()
----

`flushState` simply requests the <<stateMgr, ProcessorStateManager>> to <<kafka-streams-ProcessorStateManager.adoc#flush, flush>>.

NOTE: `flushState` is used exclusively when `StreamTask` is requested to <<kafka-streams-StreamTask.adoc#commit, commit>> (using the custom <<kafka-streams-StreamTask.adoc#flushState, flushState>>).

=== [[recordCollectorOffsets]] `recordCollectorOffsets` Method

[source, java]
----
Map<TopicPartition, Long> recordCollectorOffsets()
----

`recordCollectorOffsets`...FIXME

NOTE: `recordCollectorOffsets` is used when...FIXME

=== [[registerStateStores]] `registerStateStores` Method

[source, java]
----
void registerStateStores()
----

`registerStateStores`...FIXME

NOTE: `registerStateStores` is used when <<kafka-streams-StandbyTask.adoc#initializeStateStores, StandbyTask>> and <<kafka-streams-StreamTask.adoc#initializeStateStores, StreamTask>> are requested to `initializeStateStores`.

=== [[changelogPartitions]] `changelogPartitions` Method

[source, java]
----
Collection<TopicPartition> changelogPartitions()
----

NOTE: `changelogPartitions` is part of <<kafka-streams-Task.adoc#changelogPartitions, Task Contract>> to return changelog partitions associated with the task.

`changelogPartitions` simply requests the <<stateMgr, ProcessorStateManager>> to give the <<kafka-streams-ProcessorStateManager.adoc#changelogPartitions, changelogPartitions>> and returns them.

=== [[getStore]] Accessing State Store by Name -- `getStore` Method

[source, java]
----
StateStore getStore(final String name)
----

NOTE: `getStore` is part of the <<kafka-streams-Task.adoc#getStore, Task Contract>> to access the <<kafka-streams-StateStore.adoc#, state store>> by name.

`getStore` simply requests the <<stateMgr, ProcessorStateManager>> for the <<kafka-streams-ProcessorStateManager.adoc#getStore, StateStore by name>>.

=== [[updateOffsetLimits]] `updateOffsetLimits` Method

[source, java]
----
void updateOffsetLimits()
----

`updateOffsetLimits`...FIXME

[NOTE]
====
`updateOffsetLimits` is used when:

* `AbstractTask` is requested to <<registerStateStores, registerStateStores>>

* `StandbyTask` is requested to <<kafka-streams-StandbyTask.adoc#resume, resume>>

* `StandbyTask` is requested to <<kafka-streams-StandbyTask.adoc#commit, commit>>
====

=== [[reinitializeStateStoresForPartitions]] `reinitializeStateStoresForPartitions` Method

[source, java]
----
void reinitializeStateStoresForPartitions(final Collection<TopicPartition> partitions)
----

`reinitializeStateStoresForPartitions` simply requests the <<stateMgr, ProcessorStateManager>> to <<kafka-streams-ProcessorStateManager.adoc#reinitializeStateStoresForPartitions, reinitializeStateStores>> for the input `partitions` and the <<processorContext, InternalProcessorContext>>.

[NOTE]
====
`reinitializeStateStoresForPartitions` is used when:

* `StoreChangelogReader` is requested to <<kafka-streams-StoreChangelogReader.adoc#restore, restore>>

* `StreamThread` is requested to <<kafka-streams-StreamThread.adoc#maybeUpdateStandbyTasks, maybeUpdateStandbyTasks>>
====

=== [[activeTaskCheckpointableOffsets]] Checkpointable Offsets -- `activeTaskCheckpointableOffsets` Method

[source, java]
----
Map<TopicPartition, Long> activeTaskCheckpointableOffsets()
----

`activeTaskCheckpointableOffsets` simply returns an empty collection (of checkpointable offsets).
