== [[SessionWindowedKStreamImpl]] SessionWindowedKStreamImpl

`SessionWindowedKStreamImpl` is...FIXME

=== [[aggregate]] `aggregate` Method

[source, java]
----
KTable<Windowed<K>, T> aggregate(
  final Initializer<T> initializer,
  final Aggregator<? super K, ? super V, T> aggregator,
  final Merger<? super K, T> sessionMerger)
KTable<Windowed<K>, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator,
  final Merger<? super K, VR> sessionMerger,
  final Materialized<K, VR, SessionStore<Bytes, byte[]>> materialized)
----

NOTE: `aggregate` is part of link:kafka-streams-SessionWindowedKStream.adoc#aggregate[SessionWindowedKStream Contract] to...FIXME.

`aggregate`...FIXME

=== [[count]] `count` Method

[source, java]
----
KTable<Windowed<K>, Long> count()
KTable<Windowed<K>, Long> count(final Materialized<K, Long, SessionStore<Bytes, byte[]>> materialized)
----

NOTE: `count` is part of link:kafka-streams-SessionWindowedKStream.adoc#count[SessionWindowedKStream Contract] to...FIXME.

`count`...FIXME

=== [[reduce]] `reduce` Method

[source, java]
----
KTable<Windowed<K>, V> reduce(final Reducer<V> reducer)
KTable<Windowed<K>, V> reduce(
  final Reducer<V> reducer,
  final Materialized<K, V, SessionStore<Bytes, byte[]>> materialized)
----

NOTE: `reduce` is part of link:kafka-streams-SessionWindowedKStream.adoc#reduce[SessionWindowedKStream Contract] to...FIXME.

`reduce`...FIXME

=== [[doAggregate]] `doAggregate` Internal Method

[source, java]
----
KTable<Windowed<K>, VR> doAggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator,
  final Merger<? super K, VR> merger,
  final Serde<VR> serde)
----

`doAggregate`...FIXME

NOTE: `doAggregate` is used when `SessionWindowedKStreamImpl` is requested to <<count, count>>, <<aggregate, aggregate>> and <<reduce, reduce>>.

=== [[materialize]] `materialize` Internal Method

[source, java]
----
StoreBuilder<SessionStore<K, VR>> materialize(
  final MaterializedInternal<K, VR, SessionStore<Bytes, byte[]>> materialized)
----

`materialize`...FIXME

NOTE: `materialize` is used exclusively when `SessionWindowedKStreamImpl` is requested to <<aggregate, aggregate>>.

=== [[storeBuilder]] `storeBuilder` Internal Method

[source, java]
----
StoreBuilder<SessionStore<K, VR>> storeBuilder(
  final String storeName,
  final Serde<VR> aggValueSerde)
----

`storeBuilder`...FIXME

NOTE: `storeBuilder` is used exclusively when `SessionWindowedKStreamImpl` is requested to <<doAggregate, doAggregate>> (when requested to <<count, count>>, <<aggregate, aggregate>> and <<reduce, reduce>>).
