== [[StateStoreFactory]] StateStoreFactory

`StateStoreFactory` is the <<contract, contract>> for...FIXME

NOTE: `StateStoreFactory` is an internal interface of link:kafka-streams-InternalTopologyBuilder.adoc[InternalTopologyBuilder].

[[contract]]
[source, java]
----
package org.apache.kafka.streams.processor.internals;

interface StateStoreFactory {
  StateStore build();
  boolean isWindowStore();
  Map<String, String> logConfig();
  boolean loggingEnabled();
  String name();
  long retentionPeriod();
  Set<String> users();
}
----

.StateStoreFactory Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| `build`
| [[build]]

| `isWindowStore`
a| [[isWindowStore]] Flag to control whether a `StateStoreFactory` is created for a link:kafka-streams-WindowStoreBuilder.adoc[WindowStoreBuilder] (`true`) or not (`false`)

Used exclusively when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#createChangelogTopicConfig[create an InternalTopicConfig (for a given name and StateStoreFactory)]

[NOTE]
====
`isWindowStore` is implemented by link:kafka-streams-AbstractStateStoreFactory.adoc#isWindowStore[AbstractStateStoreFactory] only and corresponds to link:kafka-streams-AbstractStateStoreFactory.adoc#windowStore[windowStore] flag that is given when link:kafka-streams-AbstractStateStoreFactory.adoc#implementations[concrete StateStoreFactories] are created.

In a nutshell, The flag is enabled only when the `StateStoreFactory` is created for a link:kafka-streams-WindowStoreBuilder.adoc[WindowStoreBuilder].
====

| `logConfig`
| [[logConfig]]

| `loggingEnabled`
| [[loggingEnabled]]

| `name`
| [[name]]

| `retentionPeriod`
| [[retentionPeriod]] Window retention period (in milliseconds)

Used exclusively when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#createChangelogTopicConfig[create an InternalTopicConfig (for a given name and StateStoreFactory)]

| `users`
| [[users]] Names of the processors that are connected to a state store

Used when `InternalTopologyBuilder` is requested to link:kafka-streams-InternalTopologyBuilder.adoc#connectProcessorAndStateStore[connect a state store with a processor node] and link:kafka-streams-InternalTopologyBuilder.adoc#topicGroups[topic groups]
|===

[[implementations]]
.StateStoreFactories
[cols="1,2",options="header",width="100%"]
|===
| StateStoreFactory
| Description

| [[AbstractStateStoreFactory]] link:kafka-streams-AbstractStateStoreFactory.adoc[AbstractStateStoreFactory]
|

| [[StoreBuilderFactory]] link:kafka-streams-StoreBuilderFactory.adoc[StoreBuilderFactory]
|

| [[StateStoreSupplierFactory]] link:kafka-streams-StateStoreSupplierFactory.adoc[StateStoreSupplierFactory]
|
|===
