== [[TableSourceNode]] TableSourceNode

`TableSourceNode` is a concrete <<kafka-streams-internals-StreamsGraphNode.adoc#, StreamsGraphNode>> (as a <<kafka-streams-internals-StreamSourceNode.adoc#, StreamSourceNode>>) that is <<creating-instance, created>> (using <<build, StreamStreamJoinNode.build>> method) when `InternalStreamsBuilder` is requested to add a <<kafka-streams-internals-InternalStreamsBuilder.adoc#table, KTable>> and a <<kafka-streams-internals-InternalStreamsBuilder.adoc#globalTable, GlobalKTable>> to a topology.

In other words, `TableSourceNode` represents <<kafka-streams-StreamsBuilder.adoc#table, StreamsBuilder.table>> and <<kafka-streams-StreamsBuilder.adoc#globalTable, StreamsBuilder.globalTable>> operators.

=== [[creating-instance]] Creating TableSourceNode Instance

`TableSourceNode` takes the following to be created:

* [[nodeName]] Name of the node
* [[sourceName]] Name of the source
* [[topic]] Name of the topic
* [[consumedInternal]] <<kafka-streams-internals-ConsumedInternal.adoc#, ConsumedInternal>>
* [[materializedInternal]] <<kafka-streams-internals-MaterializedInternal.adoc#, MaterializedInternal>>
* [[processorParameters]] `ProcessorParameters<K, V>`
* [[isGlobalKTable]] `isGlobalKTable` flag

=== [[writeToTopology]] `writeToTopology` Method

[source, java]
----
void writeToTopology(
  InternalTopologyBuilder topologyBuilder)
----

NOTE: `writeToTopology` is part of the <<kafka-streams-internals-StreamsGraphNode.adoc#writeToTopology, StreamsGraphNode Contract>> to...FIXME.

`writeToTopology` creates a <<kafka-streams-internals-KeyValueStoreMaterializer.adoc#, KeyValueStoreMaterializer>> and requests it to <<kafka-streams-internals-KeyValueStoreMaterializer.adoc#materialize, materialize>> (to a <<kafka-streams-StoreBuilder.adoc#, StoreBuilder>> of <<kafka-streams-KeyValueStore.adoc#, KeyValueStore>>).

`writeToTopology` branches off per <<isGlobalKTable, isGlobalKTable>> flag.

When the <<isGlobalKTable, isGlobalKTable>> flag is enabled (`true`), `writeToTopology` requests the given <<kafka-streams-internals-InternalTopologyBuilder.adoc#, InternalTopologyBuilder>> to <<kafka-streams-internals-InternalTopologyBuilder.adoc#addGlobalStore, add a global key-value state store (to a topology)>>.

When the <<isGlobalKTable, isGlobalKTable>> flag is disabled (`false`), `writeToTopology`...FIXME

=== [[build]] Creating TableSourceNode -- `build` Method

[source, java]
----
TableSourceNode<K, V> build()
----

`build` simply <<creating-instance, creates a new TableSourceNode>>.

NOTE: `build` is used exclusively when `InternalStreamsBuilder` is requested to <<kafka-streams-internals-InternalStreamsBuilder.adoc#table, table>> and <<kafka-streams-internals-InternalStreamsBuilder.adoc#globalTable, globalTable>>.
