== [[MaterializedInternal]] MaterializedInternal

`MaterializedInternal` is a <<kafka-streams-Materialized.adoc#, Materialized>> that...FIXME

[[queriable]]
[[isQueryable]]
`MaterializedInternal` can be *queriable* which is...FIXME

[[loggingEnabled]]
`MaterializedInternal` uses the `loggingEnabled` flag for...FIXME

[[cachingEnabled]]
`MaterializedInternal` uses the `cachingEnabled` flag for...FIXME

[[logConfig]]
[[topicConfig]]
`MaterializedInternal` uses the `topicConfig` registry with mappings for...FIXME

`MaterializedInternal` allows accessing the optional <<storeSupplier, StoreSupplier>>.

[[storeName]]
`MaterializedInternal` uses the <<kafka-streams-Materialized.adoc#storeName, store name>> for...FIXME

=== [[generateStoreNameIfNeeded]] `generateStoreNameIfNeeded` Method

[source, java]
----
void generateStoreNameIfNeeded(
  final InternalNameProvider nameProvider,
  final String generatedStorePrefix)
----

`generateStoreNameIfNeeded`...FIXME

NOTE: `generateStoreNameIfNeeded` is used when...FIXME

=== [[withLoggingDisabled]] `withLoggingDisabled` Method

[source, java]
----
Materialized<K, V, S> withLoggingDisabled()
----

`withLoggingDisabled` turns the <<loggingEnabled, loggingEnabled>> flag off and removes all of the mappings from the <<topicConfig, topicConfig>>.

In the end, `withLoggingDisabled` returns the current `Materialized` instance.

NOTE: `withLoggingDisabled` is used exclusively when `InternalStreamsBuilder` is requested to <<kafka-streams-internals-InternalStreamsBuilder.adoc#globalTable, add a GlobalKTable to the topology>>.

=== [[storeSupplier]] Accessing Optional StoreSupplier -- `storeSupplier` Method

[source, java]
----
StoreSupplier<S> storeSupplier()
----

`storeSupplier` simply returns the <<kafka-streams-Materialized.adoc#storeSupplier, StoreSupplier>>.

NOTE: `storeSupplier` is used when <<kafka-streams-internals-KeyValueStoreMaterializer.adoc#materialize, KeyValueStoreMaterializer>>, <<kafka-streams-internals-SessionWindowedKStreamImpl.adoc#materialize, SessionWindowedKStreamImpl>>, and <<kafka-streams-internals-TimeWindowedKStreamImpl.adoc#materialize, TimeWindowedKStreamImpl>> are requested to materialize a StoreBuilder.
