== [[StreamsGraphNode]] StreamsGraphNode Contract -- Graph Nodes that Write to Topology

`StreamsGraphNode` is the <<contract, abstraction>> of <<implementations, graph nodes>> that can <<writeToTopology, writeToTopology>>.

[[contract]]
[[writeToTopology]]
[source, java]
----
void writeToTopology(
  InternalTopologyBuilder topologyBuilder)
----

`StreamsGraphNode` is used exclusively in <<kafka-streams-internals-InternalStreamsBuilder.adoc#root, InternalStreamsBuilder>> (to <<kafka-streams-internals-InternalStreamsBuilder.adoc#buildAndOptimizeTopology, build a topology>>).

[source, scala]
----
import org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder
import org.apache.kafka.streams.processor.internals.InternalTopologyBuilder
val builder = new InternalStreamsBuilder(new InternalTopologyBuilder)

import org.apache.kafka.streams.state.Stores
val lruMapSupplier = Stores.lruMap("input-stream", 5)
import org.apache.kafka.common.serialization.Serdes
import org.apache.kafka.streams.state.{KeyValueStore, StoreBuilder}
val storeBuilder = Stores.keyValueStoreBuilder(
  lruMapSupplier,
  Serdes.Long(),
  Serdes.Long())

builder.addStateStore(storeBuilder)

val root = builder.root
scala> :type root
org.apache.kafka.streams.kstream.internals.graph.StreamsGraphNode

val children = root.children
scala> :type children
java.util.Collection[org.apache.kafka.streams.kstream.internals.graph.StreamsGraphNode]
----

[[creating-instance]]
`StreamsGraphNode` takes the following when created:

* [[nodeName]] *Name* of the node
* [[repartitionRequired]] *repartitionRequired* flag (that does not seem to be used)

NOTE: `StreamsGraphNode` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete StreamsGraphNodes>> and as the <<kafka-streams-internals-InternalStreamsBuilder.adoc#root, root node of an InternalStreamsBuilder>>.

[[valueChangingOperation]]
[[setValueChangingOperation]]
`StreamsGraphNode` uses the `valueChangingOperation` flag for...FIXME

[[implementations]]
.StreamsGraphNodes (Direct Implementations)
[cols="1,2",options="header",width="100%"]
|===
| StreamsGraphNode
| Description

| <<kafka-streams-internals-BaseJoinProcessorNode.adoc#, BaseJoinProcessorNode>>
| [[BaseJoinProcessorNode]]

| <<kafka-streams-internals-BaseRepartitionNode.adoc#, BaseRepartitionNode>>
| [[BaseRepartitionNode]]

| <<kafka-streams-internals-ProcessorGraphNode.adoc#, ProcessorGraphNode>>
| [[ProcessorGraphNode]]

| <<kafka-streams-internals-StateStoreNode.adoc#, StateStoreNode>>
| [[StateStoreNode]]

| <<kafka-streams-internals-StreamSinkNode.adoc#, StreamSinkNode>>
| [[StreamSinkNode]]

| <<kafka-streams-internals-StreamSourceNode.adoc#, StreamSourceNode>>
| [[StreamSourceNode]]

| <<kafka-streams-internals-StreamTableJoinNode.adoc#, StreamTableJoinNode>>
| [[StreamTableJoinNode]]

| <<kafka-streams-internals-TableProcessorNode.adoc#, TableProcessorNode>>
| [[TableProcessorNode]]

|===
