== [[StandbyTaskCreator]] StandbyTaskCreator -- Factory of Standby Tasks

`StandbyTaskCreator` is a concrete link:kafka-streams-AbstractTaskCreator.adoc[AbstractTaskCreator] that can <<createTask, create standby tasks>>.

`StandbyTaskCreator` is <<creating-instance, created>> exclusively when `StreamThread` is link:kafka-streams-StreamThread.adoc#create[created] (and only to create a link:kafka-streams-TaskManager.adoc#taskCreator[TaskManager]).

=== [[createTask]] Creating Standby Tasks -- `createTask` Factory Method

[source, java]
----
StandbyTask createTask(
  final Consumer<byte[], byte[]> consumer,
  final TaskId taskId,
  final Set<TopicPartition> partitions)
----

NOTE: `createTask` is part of link:kafka-streams-AbstractTaskCreator.adoc#createTask[AbstractTaskCreator Contract] to create concrete link:kafka-streams-AbstractTask.adoc[stream processor tasks].

`createTask`...FIXME

NOTE: `createTask` is used when...FIXME

=== [[creating-instance]] Creating StandbyTaskCreator Instance

`StandbyTaskCreator` takes the following when created:

* [[builder]] link:kafka-streams-InternalTopologyBuilder.adoc[InternalTopologyBuilder]
* [[config]] link:kafka-streams-StreamsConfig.adoc[StreamsConfig]
* [[streamsMetrics]] `StreamsMetrics`
* [[stateDirectory]] link:kafka-streams-StateDirectory.adoc[StateDirectory]
* [[taskCreatedSensor]] `Sensor`
* [[storeChangelogReader]] link:kafka-streams-ChangelogReader.adoc[ChangelogReader]
* [[time]] `Time`
* [[log]] `Logger`
