== [[ChangelogReader]] ChangelogReader Internal Contract

`ChangelogReader` is the internal <<contract, contract>> for <<implementations, changelog readers>> that...FIXME

[[implementations]]
NOTE: link:kafka-streams-StoreChangelogReader.adoc[StoreChangelogReader] is the one and only known direct implementation of <<contract, ChangelogReader Contract>> in Kafka Streams {{ book.kafka_version }}.

[[contract]]
.ChangelogReader Contract
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| register
a| [[register]]

[source, java]
----
void register(final StateRestorer restorer)
----

Used exclusively when `ProcessorStateManager` is requested to <<kafka-streams-ProcessorStateManager.adoc#register, register a persistent state store>> (with an underlying changelog topic)

| reset
a| [[reset]]

[source, java]
----
void reset()
----

Used exclusively when `TaskManager` is requested to <<kafka-streams-internals-TaskManager.adoc#createTasks, create processor tasks for assigned topic partitions>> (when `RebalanceListener` handles <<kafka-streams-StreamThread-RebalanceListener.adoc#onPartitionsAssigned, onPartitionsAssigned>>)

| restore
a| [[restore]]

[source, java]
----
Collection<TopicPartition> restore(final RestoringTasks active)
----

Used exclusively when `TaskManager` is requested to <<kafka-streams-internals-TaskManager.adoc#updateNewAndRestoringTasks, updateNewAndRestoringTasks>> (when the owning `StreamThread` is requested to <<kafka-streams-StreamThread.adoc#runOnce, poll records once>> while <<kafka-streams-StreamThread.adoc#runLoop, running the main record processing loop>>)

| restoredOffsets
a| [[restoredOffsets]]

[source, java]
----
Map<TopicPartition, Long> restoredOffsets()
----

Used exclusively when `ProcessorStateManager` is requested to <<kafka-streams-ProcessorStateManager.adoc#checkpoint, checkpoint offsets>>
|===
