== [[Topology]] Topology

`Topology` is...FIXME

[[internalTopologyBuilder]]
`Topology` owns a link:kafka-streams-InternalTopologyBuilder.adoc[InternalTopologyBuilder]. When created, `Topology` creates a link:kafka-streams-InternalTopologyBuilder.adoc#creating-instance[InternalTopologyBuilder] and...FIXME

=== [[addSource]] `addSource` Method

[source, scala]
----
synchronized Topology addSource(
  final String name,
  final String... topics)
synchronized Topology addSource(
  final AutoOffsetReset offsetReset,
  final String name,
  final String... topics)
synchronized Topology addSource(
  final TimestampExtractor timestampExtractor,
  final String name,
  final String... topics)
synchronized Topology addSource(
  final AutoOffsetReset offsetReset,
  final TimestampExtractor timestampExtractor,
  final String name,
  final String... topics)
synchronized Topology addSource(
  final String name,
  final Deserializer keyDeserializer,
  final Deserializer valueDeserializer,
  final String... topics)
synchronized Topology addSource(
  final AutoOffsetReset offsetReset,
  final String name,
  final Deserializer keyDeserializer,
  final Deserializer valueDeserializer,
  final String... topics)
synchronized Topology addSource(
  final AutoOffsetReset offsetReset,
  final String name,
  final TimestampExtractor timestampExtractor,
  final Deserializer keyDeserializer,
  final Deserializer valueDeserializer,
  final String... topics)
----

`addSource`...FIXME

NOTE: `addSource` is used when...FIXME

=== [[addGlobalStore]] `addGlobalStore` Method

[source, java]
----
synchronized Topology addGlobalStore(
  final StoreBuilder storeBuilder,
  final String sourceName,
  final Deserializer keyDeserializer,
  final Deserializer valueDeserializer,
  final String topic,
  final String processorName,
  final ProcessorSupplier stateUpdateSupplier)
synchronized Topology addGlobalStore(
  final StoreBuilder storeBuilder,
  final String sourceName,
  final TimestampExtractor timestampExtractor,
  final Deserializer keyDeserializer,
  final Deserializer valueDeserializer,
  final String topic,
  final String processorName,
  final ProcessorSupplier stateUpdateSupplier)
----

`addGlobalStore`...FIXME

NOTE: `addGlobalStore` is used when...FIXME

=== [[connectProcessorAndStateStores]] `connectProcessorAndStateStores` Method

[source, java]
----
synchronized Topology connectProcessorAndStateStores(
  final String processorName,
  final String... stateStoreNames)
----

`connectProcessorAndStateStores` simply requests <<internalTopologyBuilder, InternalTopologyBuilder>> to link:kafka-streams-InternalTopologyBuilder.adoc#connectProcessorAndStateStores[connectProcessorAndStateStores] and returns itself (the `Topology` being built).
