== [[AbstractStateManager]] AbstractStateManager

`AbstractStateManager` is the base implementation of the <<kafka-streams-StateManager.adoc#, StateManager contract>> for <<implementations, state managers>> that use <<checkpoint, offset checkpointing>>.

NOTE: `AbstractStateManager` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete AbstractStateManagers>>.

[[CHECKPOINT_FILE_NAME]]
`AbstractStateManager` uses `.checkpoint` for the name of the <<checkpoint, checkpoint>> offset file.

[[implementations]]
.AbstractStateManagers
[cols="1,2",options="header",width="100%"]
|===
| AbstractStateManager
| Description

| <<kafka-streams-GlobalStateManagerImpl.adoc#, GlobalStateManagerImpl>>
| [[GlobalStateManagerImpl]]

| <<kafka-streams-ProcessorStateManager.adoc#, ProcessorStateManager>>
| [[ProcessorStateManager]]
|===

[[internal-registries]]
.AbstractStateManager's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| checkpoint
a| [[checkpoint]] <<kafka-streams-OffsetCheckpoint.adoc#, OffsetCheckpoint>> with the <<CHECKPOINT_FILE_NAME, .checkpoint>> file in the <<baseDir, base directory>>.

Initialized to a new <<kafka-streams-OffsetCheckpoint.adoc#, OffsetCheckpoint>> when `AbstractStateManager` is <<creating-instance, created>>

Used when:

* `AbstractStateManager` is requested to <<reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>> (to write the <<checkpointableOffsets, checkpointableOffsets>> with <<eosEnabled, exactly-once support>> off)

* `GlobalStateManagerImpl` is requested to <<kafka-streams-GlobalStateManagerImpl.adoc#initialize, initialize>> and <<kafka-streams-GlobalStateManagerImpl.adoc#checkpoint, checkpoint>>

* `ProcessorStateManager` is <<kafka-streams-ProcessorStateManager.adoc#, created>> and requested to <<kafka-streams-ProcessorStateManager.adoc#checkpoint, checkpoint>>

| checkpointableOffsets
a| [[checkpointableOffsets]] Collection of Kafka https://kafka.apache.org/20/javadoc/index.html?org/apache/kafka/common/TopicPartition.html[TopicPartitions] with offsets (`Map<TopicPartition, Long>`)

Entries (partitions with offsets) added when:

* `GlobalStateManagerImpl` is requested to <<kafka-streams-GlobalStateManagerImpl.adoc#initialize, initialize>>, <<kafka-streams-GlobalStateManagerImpl.adoc#restoreState, restoreState>> and <<kafka-streams-GlobalStateManagerImpl.adoc#checkpoint, checkpoint>>

* `ProcessorStateManager` is <<kafka-streams-ProcessorStateManager.adoc#, created>> and requested to <<kafka-streams-ProcessorStateManager.adoc#checkpoint, checkpoint>>

| globalStores
a| [[globalStores]] Global <<kafka-streams-StateStore.adoc#, state stores>> by name (managed by <<kafka-streams-GlobalStateManagerImpl.adoc#, GlobalStateManagerImpl>> _mostly_)

New state stores added when:

* `GlobalStateManagerImpl` is requested to <<kafka-streams-GlobalStateManagerImpl.adoc#register, register a state store>>

* `ProcessorStateManager` is requested to <<kafka-streams-ProcessorStateManager.adoc#registerGlobalStateStores, registerGlobalStateStores>>

State stores removed when:

* `GlobalStateManagerImpl` is requested to <<kafka-streams-GlobalStateManagerImpl.adoc#close, close>>

| stores
a| [[stores]] <<kafka-streams-StateStore.adoc#, State stores>> by name (managed by <<kafka-streams-ProcessorStateManager.adoc#, ProcessorStateManager>>)

New state stores added when:

* `ProcessorStateManager` is requested to <<kafka-streams-ProcessorStateManager.adoc#register, register a state store>>

State stores removed when:

* `ProcessorStateManager` is requested to <<kafka-streams-ProcessorStateManager.adoc#close, close>>
|===

=== [[reinitializeStateStoresForPartitions]] `reinitializeStateStoresForPartitions` Method

[source, java]
----
void reinitializeStateStoresForPartitions(
  final Logger log,
  final Map<String, StateStore> stateStores,
  final Map<String, String> storeToChangelogTopic,
  final Collection<TopicPartition> partitions,
  final InternalProcessorContext processorContext)
----

`reinitializeStateStoresForPartitions`...FIXME

[NOTE]
====
`reinitializeStateStoresForPartitions` is used when:

* `GlobalStateManagerImpl` is requested to <<kafka-streams-GlobalStateManagerImpl.adoc#reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>

* `ProcessorStateManager` is requested to <<kafka-streams-ProcessorStateManager.adoc#reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>
====

=== [[inverseOneToOneMap]] `inverseOneToOneMap` Internal Method

[source, java]
----
Map<String, String> inverseOneToOneMap(final Map<String, String> origin)
----

`inverseOneToOneMap`...FIXME

NOTE: `inverseOneToOneMap` is used exclusively when `AbstractStateManager` is requested to <<reinitializeStateStoresForPartitions, reinitializeStateStoresForPartitions>>.

=== [[creating-instance]] Creating AbstractStateManager Instance

`AbstractStateManager` takes the following when created:

* [[baseDir]] Base directory
* [[eosEnabled]] `eosEnabled` flag

`AbstractStateManager` initializes the <<internal-registries, internal registries and counters>>.

NOTE: `AbstractStateManager` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete AbstractStateManagers>>.
