== [[StateRestorer]] StateRestorer

`StateRestorer` is a concrete `BatchingStateRestoreCallback` and a <<kafka-streams-StateRestoreListener.adoc#, StateRestoreListener>>.

`StateRestorer` uses a <<compositeRestoreListener, CompositeRestoreListener>> to propagate the events: <<restoreStarted, restoreStarted>>, <<restoreDone, restoreDone>>, <<restoreBatchCompleted, restoreBatchCompleted>>, <<restore, restore>>.

`StateRestorer` is <<creating-instance, created>> exclusively when `ProcessorStateManager` is requested to <<kafka-streams-ProcessorStateManager.adoc#register, register a state store>>.

=== [[restoreBatchCompleted]] `restoreBatchCompleted` Method

[source, java]
----
void restoreBatchCompleted(long currentRestoredOffset, int numRestored)
----

`restoreBatchCompleted`...FIXME

NOTE: `restoreBatchCompleted` is used exclusively when `StoreChangelogReader` is requested to <<kafka-streams-StoreChangelogReader.adoc#processNext, processNext>> (when requested to <<kafka-streams-StoreChangelogReader.adoc#restore, restore>>).

=== [[restoreStarted]] `restoreStarted` Method

[source, java]
----
void restoreStarted()
----

`restoreStarted`...FIXME

NOTE: `restoreStarted` is used exclusively when `StoreChangelogReader` is requested to <<kafka-streams-StoreChangelogReader.adoc#startRestoration, startRestoration>> (when requested to <<kafka-streams-StoreChangelogReader.adoc#initialize, initialize>> as part of <<kafka-streams-StoreChangelogReader.adoc#restore, restore>>).

=== [[restoreDone]] `restoreDone` Method

[source, java]
----
void restoreDone()
----

`restoreDone`...FIXME

NOTE: `restoreDone` is used exclusively when `StoreChangelogReader` is requested to <<kafka-streams-StoreChangelogReader.adoc#processNext, processNext>> (when requested to <<kafka-streams-StoreChangelogReader.adoc#restore, restore>>).

=== [[restore]] `restore` Method

[source, java]
----
void restore(final Collection<KeyValue<byte[], byte[]>> records)
----

`restore`...FIXME

NOTE: `restore` is used exclusively when `StoreChangelogReader` is requested to <<kafka-streams-StoreChangelogReader.adoc#restore, restore>>.

=== [[creating-instance]] Creating StateRestorer Instance

`StateRestorer` takes the following when created:

* [[partition]] Kafka https://kafka.apache.org/20/javadoc/index.html?org/apache/kafka/common/TopicPartition.html[TopicPartition]
* [[compositeRestoreListener]] <<kafka-streams-CompositeRestoreListener.adoc#, CompositeRestoreListener>>
* [[checkpoint]] `checkpoint`
* [[offsetLimit]] `offsetLimit`
* [[persistent]] `persistent` flag
* [[storeName]] Name of the state store

`StateRestorer` initializes the <<internal-registries, internal registries and counters>>.

=== [[setUserRestoreListener]] Setting StateRestoreListener -- `setUserRestoreListener` Method

[source, java]
----
void setUserRestoreListener(StateRestoreListener userRestoreListener)
----

`setUserRestoreListener` simply requests the <<compositeRestoreListener, CompositeRestoreListener>> to <<kafka-streams-CompositeRestoreListener.adoc#setUserRestoreListener, use>> the input <<kafka-streams-StateRestoreListener.adoc#, StateRestoreListener>>.

NOTE: `setUserRestoreListener` is used exclusively when `StoreChangelogReader` is requested to <<kafka-streams-StoreChangelogReader.adoc#register, register a StateRestorer>>.
