== [[TimeWindowedKStream]] TimeWindowedKStream -- Time-Windowed Streaming Aggregations

`TimeWindowedKStream` is the <<contract, abstraction>> of a <<implementations, windowed record stream>> that allows Kafka Streams developers for <<aggregate, aggregate>>, <<count, count>>, <<reduce, reduce>> aggregations.

`TimeWindowedKStream` is the result of <<kafka-streams-KGroupedStream.adoc#windowedBy-TimeWindowedKStream, KGroupedStream.windowedBy>> stream operator with a <<kafka-streams-TimeWindows.adoc#, TimeWindows>> window specification.

TIP: Use <<kafka-streams-scala.adoc#, Scala API for Kafka Streams>> to make your Kafka Streams development more pleasant if Scala is your programming language.

[source, scala]
----
import org.apache.kafka.streams.kstream.TimeWindows
import scala.concurrent.duration._
val everyMinute = TimeWindows.of(1.minute.toMillis)

import org.apache.kafka.streams.scala.StreamsBuilder
import org.apache.kafka.streams.scala._
import ImplicitConversions._
import Serdes._
val builder = new StreamsBuilder
val windowedKStream = builder
  .stream[String, String]("events")
  .groupByKey
  .windowedBy(everyMinute)
scala> :type windowedKStream
org.apache.kafka.streams.scala.kstream.TimeWindowedKStream[String,String]

// Print out counts over 1-minute time windows to stdout
import org.apache.kafka.streams.kstream.Printed
import org.apache.kafka.streams.kstream.Windowed
val stdout = Printed
  .toSysOut[Windowed[String], Long]
  .withLabel("[time-windows]")
windowedKStream
  .count
  .toStream
  .print(stdout)

// Use println(builder.build.describe) to see the whole topology
----

[[contract]]
.TimeWindowedKStream API / Windowed Operators
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| aggregate
a| [[aggregate]]

[source, java]
----
KTable<Windowed<K>, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator)
KTable<Windowed<K>, VR> aggregate(
  final Initializer<VR> initializer,
  final Aggregator<? super K, ? super V, VR> aggregator,
  final Materialized<K, VR, WindowStore<Bytes, byte[]>> materialized)
----

Creates a <<kafka-streams-KTable.adoc#, KTable>> with a given `Initializer`, `Aggregator` and <<kafka-streams-Materialized.adoc#, Materialized>> (view of a <<kafka-streams-WindowStore.adoc#, WindowStore>>)

| count
a| [[count]]

[source, java]
----
KTable<Windowed<K>, Long> count()
KTable<Windowed<K>, Long> count(
  final Materialized<K, Long, WindowStore<Bytes, byte[]>> materialized)
----

Creates a <<kafka-streams-KTable.adoc#, KTable>> with a given <<kafka-streams-Materialized.adoc#, Materialized>> (view of a <<kafka-streams-WindowStore.adoc#, WindowStore>>)

| reduce
a| [[reduce]]

[source, java]
----
KTable<Windowed<K>, V> reduce(final Reducer<V> reducer)
KTable<Windowed<K>, V> reduce(
  final Reducer<V> reducer,
  final Materialized<K, V, WindowStore<Bytes, byte[]>> materialized)
----

Combining record stream (by a grouped key)

Creates a <<kafka-streams-KTable.adoc#, KTable>> with a given `Reducer` and <<kafka-streams-Materialized.adoc#, Materialized>> (view of a <<kafka-streams-WindowStore.adoc#, WindowStore>>)
|===

[[implementations]]
NOTE: <<kafka-streams-internals-TimeWindowedKStreamImpl.adoc#, TimeWindowedKStreamImpl>> is the one and only known implementation of the <<contract, TimeWindowedKStream Contract>> in Kafka Streams {{ book.kafka_version }}.
