== [[SourceNodeFactory]] SourceNodeFactory -- NodeFactory With No Predecessors

`SourceNodeFactory` is a link:kafka-streams-NodeFactory.adoc[NodeFactory] that has no link:kafka-streams-NodeFactory.adoc#predecessors[predecessors].

`SourceNodeFactory` is <<creating-instance, created>> when `InternalTopologyBuilder` is requested to register a link:kafka-streams-InternalTopologyBuilder.adoc#addGlobalStore[global state store] or link:kafka-streams-InternalTopologyBuilder.adoc#addSource[source topic].

NOTE: `SourceNodeFactory` is an internal `private` class of link:kafka-streams-InternalTopologyBuilder.adoc[InternalTopologyBuilder].

=== [[build]] Building SourceNode -- `build` Method

[source, java]
----
ProcessorNode build()
----

NOTE: `build` is part of link:kafka-streams-NodeFactory.adoc#build[NodeFactory Contract] to build a processor node.

`build`...FIXME

=== [[creating-instance]] Creating SourceNodeFactory Instance

`SourceNodeFactory` takes the following when created:

* [[name]] Name
* [[topics]] Topic names
* [[pattern]] Topic pattern
* [[timestampExtractor]] `TimestampExtractor`
* [[keyDeserializer]] Key deserializer
* [[valDeserializer]] Value deserializer
